 /* Copyright (c) 2011 TNO DIANA BV                              Confidential */
#ifndef _SURFACEDESC_H_
#define _SURFACEDESC_H_

#include <vector>
#include <string>

#include "TetMeshExports.h"

namespace geo {

/*!
  \class CSurfaceDesc
  \brief The surfacedescriptor defines the input surfaces

  The surfacedescriptor can define a normal surface or a slipping surface.
  A slipping surface has a front and back.
  The tetsurfaces generated by the mesher are also linked to source surfacedescriptor.
*/

class ISurface;
class CTetSurface;
class CInterfaceElement;
class CTetMeshBase;
class CElementGroup;
class TETMESH_EXPORT CSurfaceDesc
{
  friend class CTetSurface;
  CTetMeshBase& m_mesh;
  std::vector<const CTetSurface*> m_vcTetSurface;
protected:
  CElementGroup     *m_pElementGroup;
  const ISurface &m_surface;
  std::string     m_name;
public:
  CSurfaceDesc(CTetMeshBase& mesh, const ISurface &surface, const std::string& sName, bool bSlip);

  bool Slip() const;
  void Slip(bool bSlip);

  const CElementGroup& interfaceElements() const;

  void AddInterfaceElement(CInterfaceElement& element);

  bool Flip() const;

  const ISurface &Surface() const;

  int TetSurfaceSize() const;
  const CTetSurface& TetSurface(int nIndex) const;

  const std::string& Name() const;
};

}

#endif
