/* Copyright (c) 2011 TNO DIANA BV                              Confidential */
#ifndef _TETSURFACE_H_
#define _TETSURFACE_H_

#include "BodyGroup.h"

#include "TetMeshExports.h"

namespace geo {
class CSurfaceDesc;

/*!
  \class CTetSurface
  \brief The side surfaces of a bodygroup generated by the mesher.
  The sidesurfaces contain the triangles of the tetrahedron generated by the
  mehser. The sidesurfaces are also related to the CSurfaceDescriptor. The surface descriptors
  define the mesh by surfaces.
*/

class TETMESH_EXPORT CTetSurface : public CBodyGroup::CSideSurface {
  mutable std::vector<int> m_vcPointIndex;
  void FillFaceVec() const;
  void FillPointIndexVec() const;
  CSurfaceDesc &m_descriptor;

public:
  CTetSurface(CSurfaceDesc &desc, CBodyGroup &body_group);
  virtual ~CTetSurface();

  virtual int PointSize() const;
  virtual const IPoint &Point(int nIndex) const;

  const CSurfaceDesc &SurfaceDesc() const { return m_descriptor; }

  virtual const CPtrArray<IFace> FacesAtNode(const IPoint &p) const;
  virtual const IFace &Face(int nIndex) const;
  virtual int FaceSize() const;

  void CreateSurface(const std::vector<int> &vcNode);

  int NrOfNodeIndices() const;
  int NodeIndex(int nIndex) const;

  virtual bool isTiedSurface() const { return false; }
};

} // namespace geo

#endif
