     ********************** POLYGON TEST ************************
     * Geometry test file                                       *
     * testing of the polygon interior/exterior algorithms      *
     * geometry lib                                             *
     ************************************************************

Polygon point
Node 0 (-3, 1, 0)
Node 1 (-1, 1, 0)
Node 2 (-1, 3, 0)
Node 3 (1, 3, 0)
Node 4 (1, 2, 0)
Node 5 (1, 1, 0)
Node 6 (3, 1, 0)
Node 7 (3, 0, 0)
Node 8 (3, -1, 0)
Node 9 (1, -1, 0)
Node 10 (1, -3, 0)
Node 11 (0, -3, 0)
Node 12 (-1, -3, 0)
Node 13 (-1, -1, 0)
Node 14 (-2, -1, 0)
Node 15 (-3, -1, 0)

Sample point
Point    0 (        -3,        -3,         0)                                
Point    1 (        -3,        -2,         0)                                
Point    2 (        -3,        -1,         0)        edge            edge(XY)
Point    3 (        -3,         0,         0)        edge            edge(XY)
Point    4 (        -3,         1,         0)        edge            edge(XY)
Point    5 (        -3,         2,         0)                                
Point    6 (        -3,         3,         0)                                
Point    7 (        -2,        -3,         0)                                
Point    8 (        -2,        -2,         0)                                
Point    9 (        -2,        -1,         0)        edge            edge(XY)
Point   10 (        -2,         0,         0) inside      inside(XY)         
Point   11 (        -2,         1,         0)        edge            edge(XY)
Point   12 (        -2,         2,         0)                                
Point   13 (        -2,         3,         0)                                
Point   14 (        -1,        -3,         0)        edge            edge(XY)
Point   15 (        -1,        -2,         0)        edge            edge(XY)
Point   16 (        -1,        -1,         0)        edge            edge(XY)
Point   17 (        -1,         0,         0) inside      inside(XY)         
Point   18 (        -1,         1,         0)        edge            edge(XY)
Point   19 (        -1,         2,         0)        edge            edge(XY)
Point   20 (        -1,         3,         0)        edge            edge(XY)
Point   21 (         0,        -3,         0)        edge            edge(XY)
Point   22 (         0,        -2,         0) inside      inside(XY)         
Point   23 (         0,        -1,         0) inside      inside(XY)         
Point   24 (         0,         0,         0) inside      inside(XY)         
Point   25 (         0,         1,         0) inside      inside(XY)         
Point   26 (         0,         2,         0) inside      inside(XY)         
Point   27 (         0,         3,         0)        edge            edge(XY)
Point   28 (         1,        -3,         0)        edge            edge(XY)
Point   29 (         1,        -2,         0)        edge            edge(XY)
Point   30 (         1,        -1,         0)        edge            edge(XY)
Point   31 (         1,         0,         0) inside      inside(XY)         
Point   32 (         1,         1,         0)        edge            edge(XY)
Point   33 (         1,         2,         0)        edge            edge(XY)
Point   34 (         1,         3,         0)        edge            edge(XY)
Point   35 (         2,        -3,         0)                                
Point   36 (         2,        -2,         0)                                
Point   37 (         2,        -1,         0)        edge            edge(XY)
Point   38 (         2,         0,         0) inside      inside(XY)         
Point   39 (         2,         1,         0)        edge            edge(XY)
Point   40 (         2,         2,         0)                                
Point   41 (         2,         3,         0)                                
Point   42 (         3,        -3,         0)                                
Point   43 (         3,        -2,         0)                                
Point   44 (         3,        -1,         0)        edge            edge(XY)
Point   45 (         3,         0,         0)        edge            edge(XY)
Point   46 (         3,         1,         0)        edge            edge(XY)
Point   47 (         3,         2,         0)                                
Point   48 (         3,         3,         0)                                


     ******************* END POLYGON TEST ********************
