#!/bin/sh

echo -e "`basename "$0"` : $0 $@\r"

DEBUG_RELEASE=$1
BINARY=$2
FOLDER=$3 #also model
RESULT=$6
LOGFILE=$5
DIANA_LIB=$7
DIANA_SRC=$9 #share

ROOT=../..

MODELS_PATH=$ROOT/Tests/Models/RGI

#rm -rf D0.copy

if [ ! -d "D0.copy" ]; then
	cp -R $MODELS_PATH/D0 D0.copy
	chmod -R +w D0.copy

	cat geomec.ini | perl -pe 's!DIAPATH=diana!DIAPATH="'"$DIANA_LIB/.."'"!g' > D0.copy/geomec.ini
	cat D0.copy/geomec.ini | perl -pe 's!DIASHARE=share!DIASHARE="'"$DIANA_SRC/.."'"!g' > D0.copy/geomec.ini.new
	mv D0.copy/geomec.ini.new D0.copy/geomec.ini
fi

cd D0.copy
ROOT=$ROOT/..

TEMPDIR=$(pwd)
#echo "TEMPDIR:$TEMPDIR"

#cat ../geomec.ini | perl -pe 's!DIAPATH=diana!DIAPATH="'"$DIANA_LIB/.."'"!g' > geomec.ini
#cat geomec.ini | perl -pe 's!DIASHARE=share!DIASHARE="'"$DIANA_SRC/.."'"!g' > geomec.ini.new
#mv geomec.ini.new geomec.ini

USER="$ROOT/UserDLLs"

if [ "$DEBUG_RELEASE" = "debug" ]; then
	USER_=$USER/$DEBUG_RELEASE
else
	USER_=$USER
fi



LD_LIBRARY_PATH_=\
GCC:\
$QTDIR/lib:\
$USER_:\
INTEL:\
$DIANA_LIB:\
$ROOT/lib/tbb/linux/lib/intel64/gcc4.7

echo "`basename "$0"` : LD_LIBRARY_PATH_:$LD_LIBRARY_PATH_"

#echo "LD_PRELOAD=/usr/lib64/libGL.so \
#LD_LIBRARY_PATH=$LD_LIBRARY_PATH_:$LD_LIBRARY_PATH \
#../$BINARY \
#/rockmechfile:$FOLDER \
#/tempdir:$TEMPDIR >& \
#../$LOGFILE"

LD_PRELOAD=/usr/lib64/libGL.so \
LD_LIBRARY_PATH=$LD_LIBRARY_PATH_:$LD_LIBRARY_PATH \
../$BINARY \
/rockmechfile:$FOLDER \
/tempdir:$TEMPDIR >& \
../$LOGFILE

res=$?

cd ..

#rm -rf D0.copy

echo "`basename "$0"` : RESULT"

if [ $res -eq $RESULT ]; then
	echo "TEST SUCCEEDED"
else
	echo "TEST FAILED"
	exit 1
fi