#if !defined(AFX_BAR_H__479D0000_310D_4861_8A12_234D3D22D420__INCLUDED_)
#define AFX_BAR_H__479D0000_310D_4861_8A12_234D3D22D420__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CBar wrapper class

class CBar : public COleDispatchDriver
{
public:
	CBar() {}		// Calls COleDispatchDriver default constructor
	CBar(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CBar(const CBar& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetClusterOverlap();
	void SetClusterOverlap(long);
	long GetClusterWidth();
	void SetClusterWidth(long);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BAR_H__479D0000_310D_4861_8A12_234D3D22D420__INCLUDED_)
