#if !defined(AFX_SLICESTYLE_H__2A619944_3E80_4EA8_886A_3C65E7609788__INCLUDED_)
#define AFX_SLICESTYLE_H__2A619944_3E80_4EA8_886A_3C65E7609788__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDerivedDouble;

/////////////////////////////////////////////////////////////////////////////
// CSliceStyle wrapper class

class CSliceStyle : public COleDispatchDriver
{
public:
	CSliceStyle() {}		// Calls COleDispatchDriver default constructor
	CSliceStyle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSliceStyle(const CSliceStyle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CDerivedDouble GetOffset();
	LPDISPATCH GetParent();
	short GetDisplay();
	void SetDisplay(short);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SLICESTYLE_H__2A619944_3E80_4EA8_886A_3C65E7609788__INCLUDED_)
