// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "fgvview.h"

/////////////////////////////////////////////////////////////////////////////
// CFgvView

IMPLEMENT_DYNCREATE(CFgvView, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CFgvView properties

//##ModelId=3DDA0C540209
CString CFgvView::GetFgvFileName()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54020A
void CFgvView::SetFgvFileName(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

//##ModelId=3DDA0C54020C
BOOL CFgvView::GetShowModel()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54020D
void CFgvView::SetShowModel(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

//##ModelId=3DDA0C54020F
BOOL CFgvView::GetShowFrame()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540210
void CFgvView::SetShowFrame(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540216
BOOL CFgvView::GetShowTableHeaders()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540217
void CFgvView::SetShowTableHeaders(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540219
BOOL CFgvView::GetShowTableContents()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54021A
void CFgvView::SetShowTableContents(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

//##ModelId=3DDA0C54021C
BOOL CFgvView::GetShowResults()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54021D
void CFgvView::SetShowResults(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

//##ModelId=3DDA0C54021F
BOOL CFgvView::GetShowContourLegend()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540226
void CFgvView::SetShowContourLegend(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540228
BOOL CFgvView::GetShowResultsMonitor()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540229
void CFgvView::SetShowResultsMonitor(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

//##ModelId=3DDA0C54022B
BOOL CFgvView::GetShowMeshLabels()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54022C
void CFgvView::SetShowMeshLabels(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

//##ModelId=3DDA0C54022E
BOOL CFgvView::GetShowAxes()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54022F
void CFgvView::SetShowAxes(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540231
BOOL CFgvView::GetShowStatusMonitor()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540235
void CFgvView::SetShowStatusMonitor(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540237
BOOL CFgvView::GetShowAdded()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540238
void CFgvView::SetShowAdded(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

//##ModelId=3DDA0C54023A
double CFgvView::GetFgvBorderRatio()
{
	double result;
	GetProperty(0xd, VT_R8, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54023B
void CFgvView::SetFgvBorderRatio(double propVal)
{
	SetProperty(0xd, VT_R8, propVal);
}

//##ModelId=3DDA0C54023D
double CFgvView::GetZoomFactor()
{
	double result;
	GetProperty(0xe, VT_R8, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54023E
void CFgvView::SetZoomFactor(double propVal)
{
	SetProperty(0xe, VT_R8, propVal);
}

//##ModelId=3DDA0C540245
double CFgvView::GetZoomCenterX()
{
	double result;
	GetProperty(0xf, VT_R8, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540246
void CFgvView::SetZoomCenterX(double propVal)
{
	SetProperty(0xf, VT_R8, propVal);
}

//##ModelId=3DDA0C540248
double CFgvView::GetZoomCenterY()
{
	double result;
	GetProperty(0x10, VT_R8, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540249
void CFgvView::SetZoomCenterY(double propVal)
{
	SetProperty(0x10, VT_R8, propVal);
}

//##ModelId=3DDA0C54024B
double CFgvView::GetFgvUnitsFactor()
{
	double result;
	GetProperty(0x11, VT_R8, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54024C
void CFgvView::SetFgvUnitsFactor(double propVal)
{
	SetProperty(0x11, VT_R8, propVal);
}

//##ModelId=3DDA0C54024E
BOOL CFgvView::GetFgvWhiteBackground()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54024F
void CFgvView::SetFgvWhiteBackground(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540256
BOOL CFgvView::GetDebug()
{
	BOOL result;
	GetProperty(0x13, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540257
void CFgvView::SetDebug(BOOL propVal)
{
	SetProperty(0x13, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540259
long CFgvView::GetHDCWidth()
{
	long result;
	GetProperty(0x14, VT_I4, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54025A
void CFgvView::SetHDCWidth(long propVal)
{
	SetProperty(0x14, VT_I4, propVal);
}

//##ModelId=3DDA0C54025C
BOOL CFgvView::GetShowContextMenu()
{
	BOOL result;
	GetProperty(0x15, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C54025D
void CFgvView::SetShowContextMenu(BOOL propVal)
{
	SetProperty(0x15, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540264
BOOL CFgvView::GetMirrorDrawing()
{
	BOOL result;
	GetProperty(0x1a, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540265
void CFgvView::SetMirrorDrawing(BOOL propVal)
{
	SetProperty(0x1a, VT_BOOL, propVal);
}

//##ModelId=3DDA0C540267
BOOL CFgvView::GetUseDefaultPallette()
{
	BOOL result;
	GetProperty(0x1b, VT_BOOL, (void*)&result);
	return result;
}

//##ModelId=3DDA0C540268
void CFgvView::SetUseDefaultPallette(BOOL propVal)
{
	SetProperty(0x1b, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CFgvView operations

//##ModelId=3DDA0C54026A
void CFgvView::LoadPicture()
{
	InvokeHelper(0x16, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

//##ModelId=3DDA0C54026B
void CFgvView::CopyToClipboard()
{
	InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

//##ModelId=3DDA0C54026C
void CFgvView::Refresh()
{
	InvokeHelper(DISPID_REFRESH, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

//##ModelId=3DDA0C54026D
double CFgvView::GetWidthHeightRatio()
{
	double result;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_R8, (void*)&result, NULL);
	return result;
}

//##ModelId=3DDA0C540274
void CFgvView::DrawToHDC(long hDC, const VARIANT& RelX, const VARIANT& RelY)
{
	static BYTE parms[] =
		VTS_I4 VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hDC, &RelX, &RelY);
}

//##ModelId=3DDA0C540278
void CFgvView::ColorPalletteToUse(long Index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Index);
}

//##ModelId=3DDA0C54027A
void CFgvView::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
