// TetraFormation.h: interface for the CTetraFormation class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_TETRAFORMATION_H__95513568_ED2F_4C9F_A555_FC318F76B2F4__INCLUDED_)
#define AFX_TETRAFORMATION_H__95513568_ED2F_4C9F_A555_FC318F76B2F4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "3DFormation.h"
#include "FormationVolume.h"

class CTetraFormation;
class CTetraModel;
class CTetraHorizonBase;

class CTetraFormationVolume : public CFormationVolume {
  TGraphNodeSet m_identifier;

public:
  // Construction
  CTetraFormationVolume(CTetraFormation &formation, geo::CBodyGroup &group);
  CTetraFormationVolume(CTetraFormation &formation);

  virtual bool CanDestroy() const;

  // Default we have automatic remeshing after is mesh invalidates, but not in the
  // tetra model
  int DisplayListSize() const;
  const geo::IObject &DisplayList(int nIndex) const;

  // Formation volume load
  virtual void LoadStream(TSTREAM &stream, CStreamVersion &version, TPROGRESS &progress);
  virtual void SaveStream(TSTREAM &stream, TPROGRESS &progress);
  virtual long SavedItems() const;

  virtual void OnNeighbourDeleted(const CGraphNode &item);

  void Identifier(const TGraphNodeSet &identifier);
  virtual TGraphNodeSet Identifier() const;

  // get a vector of the horizons that enclose (created) this volume
  typedef std::set<const CTetraHorizonBase *, CGraphNode::CLess> TEnclosingHorizonsSet;
  TEnclosingHorizonsSet GetEnclosingHorizons() const;

  typedef std::map<QString, int> TEnclosingSurfacesMap;
  TEnclosingSurfacesMap GetEnclosingSurfaces() const;

  ACCEPT_GEOMECMODELVISITORS(VisitTetraFormationVolume);
};

// The tetraformation has a few formation volumes. Formation volumes are generated by the
// the tetra mesher. The user can drag the formation volumes between the formations. The
// user can only delete formation when there are no formation volumes attached.
class CTetraFormation : public C3DFormation {
private:
  virtual bool ShowCenterPoints() const;
  void createInitialOrdering();

  unsigned int m_order;

public:
  CTetraFormation(const QString &strName, CModelBase &model);
  CTetraFormation(CFemAppModel &model);
  CTetraFormation(const CTetraFormation &rhs);
  virtual ~CTetraFormation();

  bool operator==(const CTetraFormation &rhs) const;
  CTetraFormation &operator=(const CTetraFormation &rhs);

  bool canMoveDown() const;
  bool canMoveUp() const;

  void moveDown();
  void moveUp();
  unsigned int Order() const;
  void Order(unsigned int order);

  virtual bool Less(const CGraphNode &node) const;

  // Stream
  virtual void LoadStream(TSTREAM &stream, CStreamVersion &version, TPROGRESS &progress);
  virtual void SaveStream(TSTREAM &stream, TPROGRESS &progress);
  virtual long SavedItems() const;

  ACCEPT_GEOMECMODELVISITORS(VisitTetraFormation);
};

class CTetraFormationEntry : public CFormationEntryTempl<CTetraFormation> {
public:
  CTetraFormationEntry(CTetraModel &model);

  ACCEPT_GEOMECMODELVISITORS(VisitTetraFormationEntry);
};

#endif // !defined(AFX_TETRAFORMATION_H__95513568_ED2F_4C9F_A555_FC318F76B2F4__INCLUDED_)
