#if !defined(AFX_INSITU_H__2D863F2E_D854_42F4_9244_101C3D5063DC__INCLUDED_)
#define AFX_INSITU_H__2D863F2E_D854_42F4_9244_101C3D5063DC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CInSitu wrapper class

class CInSitu : public COleDispatchDriver
{
public:
	CInSitu() {}		// Calls COleDispatchDriver default constructor
	CInSitu(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CInSitu(const CInSitu& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	double GetPore();
	void SetPore(double);
	double GetVertical();
	void SetVertical(double);
	double GetMinimum();
	void SetMinimum(double);
	double GetMaximum();
	void SetMaximum(double);
	double GetThermalInsituGradient();
	void SetThermalInsituGradient(double);
	double GetMudTemperatureGradient();
	void SetMudTemperatureGradient(double);
	double GetSurfaceRefTemperature();
	void SetSurfaceRefTemperature(double);
	double GetAzimuth();
	void SetAzimuth(double);
	long GetStressDefinition();
	void SetStressDefinition(long);
	double GetDirectNorthStress();
	void SetDirectNorthStress(double);
	double GetDirectEastStress();
	void SetDirectEastStress(double);
	double GetDirectDepthStress();
	void SetDirectDepthStress(double);
	double GetNorthEastShearStress();
	void SetNorthEastShearStress(double);
	double GetNorthDepthShearStress();
	void SetNorthDepthShearStress(double);
	double GetEastDepthShearStress();
	void SetEastDepthShearStress(double);
	double GetGeneralPorePressure();
	void SetGeneralPorePressure(double);

// Operations
public:
	BOOL GetPrincipalStress(BOOL blnOrder, double* MaxStress, VARIANT* MaxStressDirection, double* MidStress, VARIANT* MidStressDirection, double* MinStress, VARIANT* MinStressDirection);
	BOOL TransferGeneral();
	BOOL TransferVertical();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_INSITU_H__2D863F2E_D854_42F4_9244_101C3D5063DC__INCLUDED_)
