#if !defined(AFX_MESH_H__1BEB5A51_CA3C_4949_B6BE_C64A64D7011A__INCLUDED_)
#define AFX_MESH_H__1BEB5A51_CA3C_4949_B6BE_C64A64D7011A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMesh wrapper class

class CMesh : public COleDispatchDriver {
public:
  CMesh() {} // Calls COleDispatchDriver default constructor
  CMesh(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
  CMesh(const CMesh &dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

  // Attributes
public:
  double GetBoreholeRadius();
  void SetBoreholeRadius(double);
  double GetModelRadius();
  void SetModelRadius(double);
  long GetNrTangential();
  void SetNrTangential(long);
  long GetNrRadial();
  void SetNrRadial(long);
  double GetSizeFactor();
  void SetSizeFactor(double);
  BOOL GetQuarterMesh();
  void SetQuarterMesh(BOOL);

  // Operations
public:
  BOOL SetDefault();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MESH_H__1BEB5A51_CA3C_4949_B6BE_C64A64D7011A__INCLUDED_)
