#if !defined(AFX_MUDWEIGHT_H__BE59F416_BF10_4E6C_B29E_B9017B0E85E6__INCLUDED_)
#define AFX_MUDWEIGHT_H__BE59F416_BF10_4E6C_B29E_B9017B0E85E6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMudWeight wrapper class

class CMudWeight : public COleDispatchDriver {
public:
  CMudWeight() {} // Calls COleDispatchDriver default constructor
  CMudWeight(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
  CMudWeight(const CMudWeight &dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

  // Attributes
public:
  long GetCount();
  void SetCount(long);

  // Operations
public:
  double Item(long itemnr);
  void Remove(long itemnr);
  void Clear();
  long Add(double NewValue);
  void Sort();
  short OrderOfMudweights();
  BOOL GetOptimumMudweightEx(double CriticalPlasticStrain, VARIANT *EpeqResults, double *OptimumMudweight,
                             BOOL *OptimumMudweightFound, short *Case);
  BOOL SetDefaultEx(BOOL *IsDefaultSet);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MUDWEIGHT_H__BE59F416_BF10_4E6C_B29E_B9017B0E85E6__INCLUDED_)
