#if !defined(AFX_OUTPUT_H__FF53CA1F_A3A8_48BD_9D61_DA45637C37C0__INCLUDED_)
#define AFX_OUTPUT_H__FF53CA1F_A3A8_48BD_9D61_DA45637C37C0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COutput wrapper class

class COutput : public COleDispatchDriver {
public:
  COutput() {} // Calls COleDispatchDriver default constructor
  COutput(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
  COutput(const COutput &dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

  // Attributes
public:
  BOOL GetTabulated();
  void SetTabulated(BOOL);
  BOOL GetFemview();
  void SetFemview(BOOL);
  BOOL GetNeutral();
  void SetNeutral(BOOL);
  BOOL GetPlasticity();
  void SetPlasticity(BOOL);
  BOOL GetStress();
  void SetStress(BOOL);
  BOOL GetStrain();
  void SetStrain(BOOL);
  BOOL GetDisplacement();
  void SetDisplacement(BOOL);
  BOOL GetPressure();
  void SetPressure(BOOL);
  BOOL GetTemperature();
  void SetTemperature(BOOL);

  // Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OUTPUT_H__FF53CA1F_A3A8_48BD_9D61_DA45637C37C0__INCLUDED_)
