#if !defined(AFX_PROC_H__76CC655E_C466_4798_8099_9EA2CD3A3056__INCLUDED_)
#define AFX_PROC_H__76CC655E_C466_4798_8099_9EA2CD3A3056__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CProc wrapper class

class CProc : public COleDispatchDriver
{
public:
  CProc() {}		// Calls COleDispatchDriver default constructor
  CProc(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
  CProc(const CProc& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
  long GetMaxIter();
  void SetMaxIter(long);
  double GetCriterium();
  void SetCriterium(double);
  long GetScheme();
  void SetScheme(long);
  long GetTypeCrit();
  void SetTypeCrit(long);

// Operations
public:
  BOOL SetDefault();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PROC_H__76CC655E_C466_4798_8099_9EA2CD3A3056__INCLUDED_)
