#if !defined(AFX_ROCK_H__472B9379_8A6F_4AEB_9EC2_13164E91BF28__INCLUDED_)
#define AFX_ROCK_H__472B9379_8A6F_4AEB_9EC2_13164E91BF28__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRock wrapper class

class CRock : public COleDispatchDriver
{
public:
  CRock() {}		// Calls COleDispatchDriver default constructor
  CRock(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
  CRock(const CRock& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
  double GetYoung1();
  void SetYoung1(double);
  double GetYoung2();
  void SetYoung2(double);
  double GetPoisson();
  void SetPoisson(double);
  double GetCohesion();
  void SetCohesion(double);
  double GetFriction();
  void SetFriction(double);
  double GetDilatation();
  void SetDilatation(double);
  double GetBulkSolid();
  void SetBulkSolid(double);
  double GetBulkFluid();
  void SetBulkFluid(double);
  double GetPorosity();
  void SetPorosity(double);
  double GetPermeability();
  void SetPermeability(double);
  double GetViscosity();
  void SetViscosity(double);
  BOOL GetIsotropy();
  void SetIsotropy(BOOL);
  double GetTensileStrength();
  void SetTensileStrength(double);
  double GetMudExposureTime();
  void SetMudExposureTime(double);
  double GetEquilibriumTime();
  void SetEquilibriumTime(double);
  double GetThermalRockLinearExpansion();
  void SetThermalRockLinearExpansion(double);
  double GetThermalFluidLinearExpansion();
  void SetThermalFluidLinearExpansion(double);
  double GetThermalConductivity();
  void SetThermalConductivity(double);
  long GetHardeningType();
  void SetHardeningType(long);
  double GetFractureEnergy();
  void SetFractureEnergy(double);
  double GetHardeningGradient();
  void SetHardeningGradient(double);
  double GetDipDirection();
  void SetDipDirection(double);
  double GetDipAngle();
  void SetDipAngle(double);
  double GetVolumetricSpecificHeat();
  void SetVolumetricSpecificHeat(double);
  double GetCriticalPlasticStrain();
  void SetCriticalPlasticStrain(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ROCK_H__472B9379_8A6F_4AEB_9EC2_13164E91BF28__INCLUDED_)
