#if !defined(AFX_TIMEPOINTS_H__88AE0F96_75E2_460E_B7D7_EEF4719B71AA__INCLUDED_)
#define AFX_TIMEPOINTS_H__88AE0F96_75E2_460E_B7D7_EEF4719B71AA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTimePoints wrapper class

class CTimePoints : public COleDispatchDriver
{
public:
  CTimePoints() {}		// Calls COleDispatchDriver default constructor
  CTimePoints(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
  CTimePoints(const CTimePoints& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
  long GetCount();
  void SetCount(long);
  double GetMudPressure();
  void SetMudPressure(double);
  double GetInstallTime();
  void SetInstallTime(double);
  BOOL GetPressureCom();
  void SetPressureCom(BOOL);

// Operations
public:
  long Add(double NewValue);
  double Item(long Index);
  void Remove(long Index);
  void Clear();
  void Sort();
  BOOL SetDefault();
  BOOL GetOpenHoleTime(double CriticalPlasticStrain, VARIANT* EpeqResults, double* OpenHoleTime);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TIMEPOINTS_H__88AE0F96_75E2_460E_B7D7_EEF4719B71AA__INCLUDED_)
