#if !defined(AFX_WELL_H__1525BA65_F05D_4409_B265_134EC410A48D__INCLUDED_)
#define AFX_WELL_H__1525BA65_F05D_4409_B265_134EC410A48D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWell wrapper class

class CWell : public COleDispatchDriver
{
public:
	CWell() {}		// Calls COleDispatchDriver default constructor
	CWell(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CWell(const CWell& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	double GetAzimuth();
	void SetAzimuth(double);
	double GetInclination();
	void SetInclination(double);
	double GetVerticalDepth();
	void SetVerticalDepth(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WELL_H__1525BA65_F05D_4409_B265_134EC410A48D__INCLUDED_)
