#! /bin/sh
#
# This utility cats a source file using a specific destination file
# type (native, dos, unix, binary, unknown)
#

usage()
{
	cat >&2 <<EOF
usage: $0 <type> <source file>
where <type> is one of
  binary
  dos
  native
  unix
  unknown
EOF
	exit 1
}

# Main program
#
while getopts ":" option ; do
	case "$option" in
	*)
		usage
		;;
	esac
done
shift $(expr $OPTIND - 1)

[ $# -eq 2 ] || usage

case "$1" in
binary|dos|unix|unknown)
	type=$1
	;;
native)
	case "$(uname)" in
	CYGWIN*)
		type=dos
		;;
	*)
		type=unix
		;;
	esac
	;;
*)
	usage
	;;
esac
file=$2

if ! [ -r "$file" ] ; then
	echo "$0: trouble reading $file" >&2
	exit 1
fi

case "$type" in
dos)
	gawk '
BEGIN {

	# Force binary I/O on exotic platforms; no effect otherwise
	BINMODE=rw
}

{
	# Do not add a carriage return to an incomplete last line
	# note: RT is a gawk extension; it indicates the record separator found
	if (RT == "\n") {
		sub(/^(.*[^\r])?$/, "&\r")
		print
	} else {
		printf "%s", $0
	}
}
' < "$file"
	;;
unix)
	gawk '
BEGIN {

	# Force binary I/O on exotic platforms; no effect otherwise
	BINMODE=rw
}

{
	# Do not remove a carriage return from an incomplete last line
	# note: RT is a gawk extension; it indicates the record separator found
	if (RT == "\n") {
		sub(/\r$/, "")
		print
	} else {
		printf "%s", $0
	}
}
' < "$file"
	;;
*)
	cat -- "$file"
	;;
esac
