#! /bin/sh
#
# This script prints a file's type according to its svn properties
#

# Print usage info and report failure
#
usage()
{
	cat >&2 <<EOF
usage: $0 <file>
prints <file>'s file type according to its svn properties - one of
  unknown   not set
  binary    binary file
  native    text file with native end-of-line markers
  unix      text file with unix end-of-line style
  dos       text file with dos end-of-line style
EOF
	exit 1
}

#
# Main program
#

# Check command line
#
while getopts ":" option ; do
	case "$option" in
	*)
		usage
		;;
	esac
done
shift $(expr $OPTIND - 1)
[ $# -eq 1 ] || usage
file=$1

# Check for a regular file
#
if [ -h "$file" ] || [ ! -f "$file" ] ; then
	echo "$0: $file does not exist, or is not a regular file" >&2
	exit 1
fi

# Map file name to the platform's native syntax
#
case "$(uname)" in
CYGWIN*)
	natfile=$(cygpath --windows -- "$file") || exit 1
	;;
*)
	natfile=$1
	;;
esac

ampersand=$(echo "$natfile" | grep '\@')

if [ "$ampersand" = "" ] ; then
	natfile="$natfile"
else
	natfile="$natfile@"
fi

# Check the svn mime type; if it is set to something other than text/*, 
# assume we have a binary
#
mime_type=$(svn propget -- svn:mime-type "$natfile") || exit 1

if [ -z "$mime_type" ] ; then
	type=unknown
else
	case "$mime_type" in
	text/*)
		type=unkown
		;;
	*)
		type=binary
		;;
	esac
fi

# If we don't know yet, check the svn end-of-line style
#  
if [ "$type" = unknown ] ; then
	eol_style=$(svn propget -- svn:eol-style "$natfile") || exit 1
	case "$eol_style" in
	native)
		type=native
		;;
	LF|lf)
		type=unix
		;;
	CRLF|crlf)
		type=dos
		;;
	*)
		type=unknown
		;;
	esac
fi

echo "$type"
