#! /bin/sh
#
# This script recursively scans a subversion working copy, setting the
# svn file type for files on which the type is not set...
#

usage()
{
	cat >&2 <<EOF
usage: $0 [<option>...] <path> ...
options are:
  -d   dry run
  -N   non-recursive
  -v   verbose
EOF
	exit 1
}

check_file()
{(
	if [ $# -ne 1 ] ; then
		echo "usage: check_file <file>" >&2
		exit 1
	fi

	type=$(svn-file-type -- "$1") || exit 1

	if [ "$type" = unknown ] ; then

		type=$(file-type -- "$1") || exit 1
		case "$type" in
		dos|unix)
			type=native
			;;
		esac

		if [ "$type" = unknown ] ; then

			if [ -n "$verbose" ] ; then
				echo "unable to guess type: $1"
			fi

		else

			echo "type guessed as $type: $1"
			if [ -z "$dry_run" ] ; then
				set-svn-file-type -- "$type" "$1" || exit 1
			fi
		fi

	elif [ -n "$verbose" ] ; then

		echo "type previously set as $type: $1"

	fi
)}
		
check_directory()
{(
	if [ $# -ne 1 ] ; then
		echo "usage: check_directory <directory>" >&2
		exit 1
	fi

	entries=$(ls -U -A -1 -I .svn -- "$1") || exit 1
	if [ -n "$entries" ] ; then
		printf "%s\n" "$entries" | while read entry ; do
			path="$1/$entry"
			if [ -n "$recursive" ] || [ ! -d "$path" ] ; then
				check "$path" || exit 1
			fi
		done
	fi
)}

check()
{
	if [ $# -ne 1 ] ; then
		echo "usage: check <path>" >&2
		exit 1
	elif [ -h "$1" ] ; then
		echo "$0: $1 is a symbolic link" >&2
		exit 1
	elif [ -f "$1" ] ; then
		check_file "$1"
	elif [ -d "$1" ] ; then
		check_directory "$1"
	else
		echo "$0: $1 is not a regular file, and not a directory" >&2
		exit 1
	fi
}

#
# Parse the command line
#
dry_run=""
recursive=yes
verbose=""
while getopts ":dNv" option ; do
	case "$option" in
	d)
		dry_run=yes
		;;
	N)
		recursive=""
		;;
	v)
		verbose=yes
		;;
	*)
		usage
		;;
	esac
done
shift $(expr $OPTIND - 1)
[ $# -gt 0 ] || usage

while [ $# -ne 0 ] ; do
	check "$1" || exit 1
	shift
done

