#!/bin/sh
if [ $# -ne "1" ]; then
	exit 1
fi

echo "cd $1"
cd $1

for i in {0..9}
do
	rm -f TestRGInterface.$i.gm4
	echo "../../../geomec_rgi/$1/geomec_rgi /ROCKMECHFILE:TestRGInterface.$i || exit 1"
	../../../geomec_rgi/$1/geomec_rgi /ROCKMECHFILE:TestRGInterface.$i || exit 1
	echo
done

cd ..
