#if !defined(AFX_AXISX_H__4ED25B0E_FE86_4E09_880F_32004B2D38C9__INCLUDED_)
#define AFX_AXISX_H__4ED25B0E_FE86_4E09_880F_32004B2D38C9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CAxisX wrapper class

class CAxisX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAxisX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5bea0bcb, 0x5a64, 0x4650, { 0xb5, 0x9e, 0xdd, 0x41, 0x8a, 0x9d, 0x61, 0x54 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	unsigned long GetAxisColor();
	void SetAxisColor(unsigned long newValue);
	CString GetXLabel();
	void SetXLabel(LPCTSTR lpszNewValue);
	CString GetYLabel();
	void SetYLabel(LPCTSTR lpszNewValue);
	CString GetZLabel();
	void SetZLabel(LPCTSTR lpszNewValue);
	CString GetTitle();
	void SetTitle(LPCTSTR lpszNewValue);
	CString GetFooter1();
	void SetFooter1(LPCTSTR lpszNewValue);
	CString GetFooter2();
	void SetFooter2(LPCTSTR lpszNewValue);
	CString GetFooter3();
	void SetFooter3(LPCTSTR lpszNewValue);
	CString GetSigmaFooter();
	void SetSigmaFooter(LPCTSTR lpszNewValue);
	BOOL GetHideX();
	void SetHideX(BOOL bNewValue);
	BOOL GetHideY();
	void SetHideY(BOOL bNewValue);
	BOOL GetHideZ();
	void SetHideZ(BOOL bNewValue);
	void RotateX(double* angle);
	void RotateY(double* angle);
	void RotateZ(double* angle);
	void Reset();
	BOOL GetShowOrigin();
	void SetShowOrigin(BOOL bNewValue);
	CString GetXLabelOrigin();
	void SetXLabelOrigin(LPCTSTR lpszNewValue);
	CString GetYLabelOrigin();
	void SetYLabelOrigin(LPCTSTR lpszNewValue);
	CString GetZLabelOrigin();
	void SetZLabelOrigin(LPCTSTR lpszNewValue);
	BOOL GetHideXOrigin();
	void SetHideXOrigin(BOOL bNewValue);
	BOOL GetHideYOrigin();
	void SetHideYOrigin(BOOL bNewValue);
	BOOL GetHideZOrigin();
	void SetHideZOrigin(BOOL bNewValue);
	CPicture GetPicture();
	void SetRefPicture(LPDISPATCH newValue);
	long GetHDC();
	CPicture GetImage();
	short GetBorderStyle();
	void SetBorderStyle(short nNewValue);
	void SetAxisExt(const VARIANT& VecX, const VARIANT& VecY, const VARIANT& VecZ);
	// method 'SetAxis' not emitted because of invalid return type or parameter type
	void RotateOriginView(double AngleX, double AngleY, double AngleZ);
	BOOL GetIsometricView();
	void SetIsometricView(BOOL bNewValue);
	BOOL GetDrawCircle();
	void SetDrawCircle(BOOL bNewValue);
	BOOL GetXBoundingBox();
	void SetXBoundingBox(BOOL bNewValue);
	BOOL GetYBoundingBox();
	void SetYBoundingBox(BOOL bNewValue);
	BOOL GetZBoundingBox();
	void SetZBoundingBox(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXISX_H__4ED25B0E_FE86_4E09_880F_32004B2D38C9__INCLUDED_)
