INCLUDEPATH += $$CREATEFILOS_BASE
INCLUDEPATH += $$MODGMBUS_BASE

INCLUDEPATH += $$GEOMECMODEL_PATH/BaseModel/h
INCLUDEPATH += $$GEOMECMODEL_PATH/Value/h
INCLUDEPATH += $$GEOMECMODEL_PATH/visitor/h
INCLUDEPATH += $$QUANTITY_BASE
INCLUDEPATH += $$GEOMECSTRINGTABLE_BASE
INCLUDEPATH += $$FEMAPPMODEL_BASE
INCLUDEPATH += $$FW_OPENGLFRAME
INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$MFCMODELFRAME_BASE
INCLUDEPATH += $$FW_GUIFRAME
INCLUDEPATH += $$GEOMECMODEL_PATH/Geology/h
INCLUDEPATH += $$GEOMECMODEL_PATH/h
INCLUDEPATH += $$NEWWELLSCHEME_BASE
INCLUDEPATH += $$FW_MODELFRAME
INCLUDEPATH += $$DIANA
          
INCLUDEPATH += $$GEOMECMODEL_PATH/TetraModel/h
  
INCLUDEPATH += $$QUTIL_BASE
INCLUDEPATH += $$UTIL_BASE
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $(QTDIR)/include/QtOpenGL
INCLUDEPATH += $(DIAPATH)/share/src/lb/gc51/classes/include