INCLUDEPATH += $$CUTSURFACEUTILMODEL_BASE
INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$FW_OPENGLFRAME
INCLUDEPATH += $$FW_TRIANGLE
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $$DIANA
INCLUDEPATH += $(QTDIR)/include/QtOpenGL