INCLUDEPATH += $$DCASING_BASE
INCLUDEPATH += $$QUANTITY_BASE
INCLUDEPATH += $$DIANASTARTUP_BASE
INCLUDEPATH += $$QUTIL_BASE # 'Interprocess.h' needed by 'QDIANASTARTUP'
INCLUDEPATH += $$GEOMECMODEL_PATH/h
INCLUDEPATH += $$DIANASIGNALS_BASE
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $$DIANA