INCLUDEPATH += $$DIANACORE_BASE
INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$FW_TENSOR			# FIXME: I found 'FW_TENSO' instaed, check this out
INCLUDEPATH += $$DIANA
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $$QUTIL_BASE
