INCLUDEPATH += $$DIANASTARTUP_BASE
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $$DIANA
INCLUDEPATH += $$MODGMBUS_BASE
INCLUDEPATH += $$QUTIL_BASE
INCLUDEPATH += $$UTIL_BASE
INCLUDEPATH += $$DIANAAPPNEW_BASE