INCLUDEPATH += $$DIANAAPP_BASE
INCLUDEPATH += $$MODGMBUS_BASE
INCLUDEPATH += $$DIANAGLUE_BASE
INCLUDEPATH += $$DIANACORE_BASE
INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$FW_TENSOR
INCLUDEPATH += $$DIANASIGNALS_BASE
INCLUDEPATH += $$DIANASTARTUP_BASE
INCLUDEPATH += $$DIANA
INCLUDEPATH += $$UTIL_BASE 	# ??
INCLUDEPATH += $$QUTIL_BASE # ??
#$(QTDIR)/include\QtANGLE;
INCLUDEPATH += $$QTINCLUDES