INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$DIAINCLUDE
INCLUDEPATH += $$DIANA
INCLUDEPATH += $$MPKERNEL_BASE
INCLUDEPATH += $$TBBDIR/include
INCLUDEPATH += $$GEOMECMODEL_PATH/h
INCLUDEPATH += $$QUTIL_BASE