INCLUDEPATH += $$FW_GUIFRAME

INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$FW_MODELFRAME
INCLUDEPATH += $$FW_OPENGLFRAME

#INCLUDEPATH += $$DIAINCLUDE
#INCLUDEPATH += $(DIASRC)/include
INCLUDEPATH += $$DIANA

# FIXME
INCLUDEPATH += $(QTDIR)/include/QtOpenGL
