INCLUDEPATH += $$GEOMECLAUNCHER_BASE
INCLUDEPATH += $$MODGMBUS_BASE
INCLUDEPATH += $$UTIL_BASE
INCLUDEPATH += $$QUTIL_BASE
INCLUDEPATH += $(QTDIR)/include/QtANGLE;
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $$CONSOLELIBRARY_BASE