INCLUDEPATH += $$GMDIANAAPP_BASE
INCLUDEPATH += $$DIANACORE_BASE
INCLUDEPATH += $$DIANASTARTUP_BASE
INCLUDEPATH += $$DIANA
INCLUDEPATH += $$UTIL_BASE 	# ??
INCLUDEPATH += $$QUTIL_BASE # ??
INCLUDEPATH += $$QTINCLUDES