INCLUDEPATH += $$IT_BASE
INCLUDEPATH += $$PLUGINS_BASE
INCLUDEPATH += $$PYLIB_BASE
INCLUDEPATH += $$QUTIL_BASE
INCLUDEPATH += $$PYTHONROOT\include
INCLUDEPATH += $$PYTHONROOT\Lib\site-packages\numpy\core\include
INCLUDEPATH += $$TBBDIR/include
INCLUDEPATH += $$GEOMEC_IT
