INCLUDEPATH += $$MESHDATACACHER_BASE
INCLUDEPATH += $$GLOBALMESSAGE_BASE
INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$DIANA
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $$TBBDIR/include
INCLUDEPATH += $$QUTIL_BASE