INCLUDEPATH += $$TSMESH_BASE
INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $$DIANA
INCLUDEPATH += $$GLIB2PATH/include/glib-2.0
INCLUDEPATH += $$GLIB2PATH/lib/glib-2.0/include # attention!!! lib64->lib