INCLUDEPATH += $$WELLSCHEME_BASE
INCLUDEPATH += $$COMMONWELLSCHEME_BASE
INCLUDEPATH += $$FW_GEOMETRY
INCLUDEPATH += $$FW_MODELFRAME
INCLUDEPATH += $$FW_FIELDVALUEFILE
INCLUDEPATH += $$QUANTITY_BASE
INCLUDEPATH += $$QTINCLUDES
INCLUDEPATH += $$DIANA
