#if !defined(AFX_DIANAX_H__DB449CD4_0A8D_4DDD_93F5_1B062FD934B3__INCLUDED_)
#define AFX_DIANAX_H__DB449CD4_0A8D_4DDD_93F5_1B062FD934B3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDianaX wrapper class

class CDianaX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDianaX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x3a01bc17, 0xba9f, 0x11d2, { 0xb3, 0xb4, 0x0, 0x10, 0x4b, 0x25, 0x56, 0xd9 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetShowDialog();
	void SetShowDialog(BOOL);
	CString GetSuccessMessageString();
	void SetSuccessMessageString(LPCTSTR);
	long GetNumberOfMessages();
	void SetNumberOfMessages(long);
	BOOL GetDisplayStopMessage();
	void SetDisplayStopMessage(BOOL);
	BOOL GetShowDefaultMessages();
	void SetShowDefaultMessages(BOOL);
	CString GetDialogCaption();
	void SetDialogCaption(LPCTSTR);
	BOOL GetAutoCloseDialog();
	void SetAutoCloseDialog(BOOL);
	BOOL GetAlwaysAutoCloseDialog();
	void SetAlwaysAutoCloseDialog(BOOL);

	BOOL GetProgressIsLifesign();
	void SetProgressIsLifesign(BOOL);
	long GetNumberOfAppSpcMessages();
	void SetNumberOfAppSpcMessages(long);

// Operations
public:
	BOOL SetEnvironmentVar(LPCTSTR VarName, LPCTSTR Value);
	short ExecuteDiana(LPCTSTR ExeName, LPCTSTR WorkingDir, LPCTSTR ComFile, LPCTSTR DatFile, LPCTSTR FilosFile, LPCTSTR BaseName);
	BOOL GetCalculationResult();
	BOOL SetUserMagic(LPCTSTR Leader, LPCTSTR Trailer);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DIANAX_H__DB449CD4_0A8D_4DDD_93F5_1B062FD934B3__INCLUDED_)
