#if !defined(GVTSETTINGS_H_)
#define GVTSETTINGS_H_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "GridDefinition.h"

class CModelBase;
class CGVTSettings;
class CFormationBase;
class CDepletionStage;
class CGVTSeismicGridDefinition;

namespace geo {
class IPoint;
}

#include "ivaluecomponent.h"

#include <map>

#include <qstring.h>
#include <sstream>

#include "GVTData.h"
#include "GVTVelocityModel.h"
#include "GVTVelocityModelFile.h"
#include "QBSettings.h"
#include "StorageNode.h"

class CGVTSettings : public CStorageNode {
  int m_nCurrentGrid;
  std::vector<CGVTSeismicGridDefinition *> m_SeismicGrids;
  CModelBase &m_Model;
  QString m_strOutputPrefix;    // prefix, this will prefix the files generated by GVT
  QString m_strOutputDirectory; // path to output directory for GVT
  bool m_bdVp;                  // input parameter for GVT delta Vp
  bool m_bdt;                   // input parameter for GVT delta t

  bool m_bResultsChanged;
  // indicates whether a pointset should be created by GVT that can be read
  // back into GEOMEC
  bool m_bImportBack;

  // each formation with the velocity model that should be used for it.
  CGVTDataTypes::TFormationVelocityModels m_mpFormation2Model;

  // Time lapses for the GVT analysis
  CGVTDataTypes::TTimeLapses m_vcTimeLapses;

  CGVTData m_data;

  bool m_bForceNewPointSets;
  GVT::CGVTVelocityModelFile m_GVTVelocityModelFile;

  bool PrepareCalculation(IProgressBase &progress);

  typedef enum { INTERNAL = 0, EXTERNAL } eCalculatorType;
  static eCalculatorType CalculatorType();

  void InternalCalculation(IProgressBase &progress);
  void ExternalCalculation(IProgressBase &progress);

  void ClearMemory();

public:
  CGVTSettings(const CGVTSettings &rhs);
  CGVTSettings(CModelBase &model);
  ~CGVTSettings(void);
  CGVTSettings &operator=(const CGVTSettings &rhs);

  int NoOfGrids() const;
  const CGVTSeismicGridDefinition &Grid(int nIndex) const;
  CGVTSeismicGridDefinition &Grid(int nIndex);
  CGVTSeismicGridDefinition *NewGrid();
  void RemoveGrid(CGVTSeismicGridDefinition *m_Grid);
  void SetVelModel(CFormationBase *formation, eVelocityModel model);
  const CGVTVelocityModel *GetVelModel(CFormationBase *formation) const;
  void AddTimeLapse(CDepletionStage *time1, CDepletionStage *time2);
  void RemoveTimeLapse(int nIndex);
  void SetTimeLapse(int nIndex, CDepletionStage *time1, CDepletionStage *time2, TTimeLapseType TLT);
  QString ListObjectName() const;
  const std::vector<std::pair<CDepletionStage *, CDepletionStage *>> &TimeLapses() const;
  const std::vector<const IValueComponentBase *> &DataVec() const { return m_data.DataVec(); }

  CModelBase &Model() { return m_Model; }
  const CModelBase &Model() const { return m_Model; }

  int CurrentGrid() const { return m_nCurrentGrid; }
  int CurrentGrid() { return m_nCurrentGrid; }
  void CurrentGrid(int nValue) { m_nCurrentGrid = nValue; }
  void RemoveGrid(int nIndex);

  const QString &VelocityModelFile() const { return m_GVTVelocityModelFile.velocityModelFile(); }
  void VelocityModelFile(const QString &velmodel) { m_GVTVelocityModelFile.velocityModelFile(velmodel); }

  const QString &OutputPrefix() const { return m_strOutputPrefix; }
  void OutputPrefix(const QString &outppref) { m_strOutputPrefix = outppref; }

  const QString &OutputDirectory() const { return m_strOutputDirectory; }
  void OutputDirectory(const QString &outpdir) { m_strOutputDirectory = outpdir; }

  bool ForceNewPointSets() const { return m_bForceNewPointSets; }
  void ForceNewPointSets(bool bForce) { m_bForceNewPointSets = bForce; }

  bool DeltaVp() const { return m_bdVp; }
  void DeltaVp(bool bValue) { m_bdVp = bValue; }
  bool Deltat() const { return m_bdt; }
  void Deltat(bool bValue) { m_bdt = bValue; }
  bool ImportBack() const { return m_bImportBack; }
  void ImportBack(bool bValue) { m_bImportBack = bValue; }
  int velocitySource() const;
  void velocitySource(int velocitySource);

  const CPointSet *AnalysisPointSet() const { return m_data.AnalysisPointSet(); }

  bool GridReady() const;
  bool TimeLapseReady() const;
  bool VelocityModelFileReady() const;
  bool AnalysisIsGo() const;

  static bool CanCalculate();
  void Calculate();

  std::map<CFormationBase *, CGVTVelocityModel *> &FormationToVelModelMp();

  typedef CStorageNode::TSTREAM TSTREAM;
  typedef CStorageNode::TPROGRESS TPROGRESS;

  virtual void LoadStream(TSTREAM &stream, CStreamVersion &version, TPROGRESS &progress);
  virtual void SaveStream(TSTREAM &stream, TPROGRESS &progress);
  virtual long SavedItems() const { return 0; }
  virtual unsigned int TypeId() const { return 0; }
  virtual unsigned int IconId() const { return 0; }
  virtual bool Empty() const { return false; }
  virtual void OnNeighbourModified(const CGraphNode &node, enum ModifiedHint uHint);
  int IndexOffset() const { return 0; }

  ACCEPT_GEOMECMODELVISITORS(VisitGVTSettings);
};

#endif