#ifndef _GEOMECMODELVISITOR_H_
#define _GEOMECMODELVISITOR_H_

#include "GraphNodeVisitor.h"

#ifdef _WIN32
#define OVERRIDE override
#else
#define OVERRIDE
#endif

#define ACCEPT_GEOMECMODELVISITORS(visit_function)                                  \
  virtual bool Accept(graphnode::IConstVisitor& visitor) const OVERRIDE             \
  {                                                                                 \
  assert(dynamic_cast<IGeomecModelConstVisitor*>(&visitor));                      \
  return (static_cast<IGeomecModelConstVisitor&>(visitor)).visit_function(*this); \
  }                                                                                 \
                                          \
  virtual bool Accept(graphnode::IVisitor& visitor) OVERRIDE                        \
  {                                                                                 \
  assert(dynamic_cast<IGeomecModelVisitor*>(&visitor));                           \
  return (static_cast<IGeomecModelVisitor&>(visitor)).visit_function(*this);      \
  }                                                                                 \


class C3DFormation;
class C3DHorizon;
class C3DModel;
class C3DSupportNode;
class CAnalysisPoint;
class CAnalysisPointEntry;
class CSupportDepletion;
class CBaseSupportNode;
class CBoundaryBase;
class CBoundaryInterfaceDef;
class CCamClayUpscalingNode;
class CColorGradient;
class CColorScaleEntry;
class CCrossSection;
class CCrossSectionEntry;
class CDepletionStage;
class CDepletionStageEntry;
class CDisplacementSupportNode;
class IElementSet;
class CElementSet;
class CExportResultData;
class CExportResultDataEntry;
class CFaultParametersNode;
class CFaultPressureComponent;
class CFaultPressure;
class CFaultPressureGradientComponent;
class CFaultPressureMinComponent;
class CFaultPressureMaxComponent;
class CFaultPressureMaxGradientComponent;
class CGocadElementSet;
class CHomogenizationBox;
class CHomoBoxEntry;
class CHorizonBase;
class CHotSpot;
class CInterfaceBoundary;
class IScalingBox;
class CMeasuredTopDisplacementsNode;
class CMeshObserver;
class CPillarMap;
class CNonMeshedSurface;
class CNonMeshedSurfaceEntry;
class CNonMeshedSurfaceParametersNode;
class CNonMeshedSurfacePressureComponent;
class CNonMeshedSurfacePressure;
class CFormationObserver;
class CStrainLoadGradientComponent;
class CStrainLoadGWCDummyComponent;
class CStrainLoadRepeaterComponent;
class CStrainLoad;
class CThinLayerUpscalingNode;
class IUpscalingNodeBase;
class CUpscalingEntry;
class CUpscalingFormationsBranch;
class IUpscalingPointsetBranchBase;
class CUpscalingPointsetRangesBranch;
class CUpscalingTargetPointsetBranch;
class CValueComponent;
class CVolumetricStrainLoadGradientComponent;
class CVolumetricStrainLoadGWCDummyComponent;
class CVolumetricStrainLoadRepeaterComponent;
class CVolumetricStrainLoad;
class IFormationElementSet;
class CFormationBase;
class CFormationThickness;
class CFormationPlane;
class CFormationVolume;
class CWellFormation;
class CWellFormationEntry;
class CWellFormationVolume;
class CGoCadModel;
class CGoCadSubModelEntry;
class CHexaBoundary;
class CHexaFormationVolume;
class CHexaFormation;
class CHexaFormationEntry;
class CHexaHorizon;
class CHexaHorizonEntry;
class CHexaMesh;
class CHexaMeshRegionBase;
class CHexaMainMeshRegion;
class CHexaSubMeshRegion;
class CHexaMeshRegionEntry;
class CHexaModel;
class CHexaSurface;
class IMaterial;
class IMaterialBase;
class IMaterialRock;
class IMaterialServerBase;
class CInterfaceMaterial;
class CInterfaceMaterialEntry;
class CMaterialAnisotropicCamClay;
class CMaterialCamClay;
class CMaterialCamClayCreep;
class CMaterialCreep;
class CMaterialDualCapLinEla;
class CMaterialEntry;
class CMaterialFractAnisotropy;
class CMaterialFractureAperture;
class CMaterialFractureAperture2;
class CMaterialFractureApertureBase;
class CMaterialLinear;
class CMaterialMCCohesionHard1;
class CMaterialMCCohesionHard2;
class CMaterialMCCohesionHard3;
class CMaterialMCFrictionHard1;
class CMaterialMCFrictionHard2;
class CMaterialMCFrictionHard3;
class CMaterialModMohrCo;
class CMaterialMohrCo;
class CMaterialResult;
class CMaterialResultTree;
class CMaterialRigidity;
class CMaterialServer;
class CMaterialUndrained;
class CMaterialUpscaledAnisotropy;
class CWellCasingCement;
class CWellCasingMaterialServer;
class CWellCasingSteel;
class CWellCasingSteelMaterial;
class CWellCasingSteelMaterialEntry;
class IWellMesh;
class CMeshBase;
class CMeshRegionBase;
class CMeshResult;
class CMeshResultTree;
class CWellCasingMesh;
class CWellZoomInMesh;
class CEclipseModel;
class CEclipseSubModelEntry;
class IWellModel;
class CModelBase;
class CWellCasingModel;
class CWellCasingFormationEntry;
class CWellZoomInModel;
class IPointSet;
class CPointSetEntry;
class CLasPointSet;
class CPointSet;
class CFractureMatrixComponentGWC;
class CFractureMatrixComponentRepeater;
class CFractureMatrixPressure;
class CGlobalPressure;
class CComponentGWC;
class CComponentRepeater;
class CPressure;
class CPressureSupportNode;
class CWellCasingInternalPressure;
class CDerivedResult;
class CDerivedResultGroup;
class IVectorResult;
class CVectorResult;
class CResultGroup;
class IResult;
class IResultComponent;
class IScalarResultComponent;
class CResultTree;
class CStaborResult;
class CGVTSettings;
class CQBSettings;
class CSurfaceBase;
class CSurfaceEntry;
class CCalculatedTemperature;
class CGlobalTemperature;
class CTemperatureGradientComponent;
class CTemperatureGWCDummyComponent;
class CTemperatureRepeaterComponent;
class CTemperature;
class CWellCasingInternalTemperature;
class CFractTensor;
class IStrainTensorGroup;
class IStressTensorGroup;
class ITensorGroup;
class CMatParamsTensor;
class TStressTensor;
class TStrainTensor;
class CTetraBoundary;
class CTetraFormationVolume;
class CTetraFormation;
class CTetraFormationEntry;
class CTetraHorizonBase;
class CTetraMesh;
class CTetraModel;
class CTetraSubBoundary;
class CTetraSubHorizon;
class CTetraSubHorizonEntry;
class CTetraSuperHorizon;
class CTetraSuperHorizonEntry;
class CTetraSurface;
class CGlobalInitialStressNode;
class CResultRegister;
class TStrain;
class CValueType;
class TLengthComponent;
class CSurfaceValueType;
class TPressure;
class TFractureMatrixPressure;
class TTemperature;
class TVolumetricStrain;
class TNormalStrain;
class TLateralStrain;
class TCohesion;
class TBulkStiffness;
class TShearModulus;
class TVelocityP;
class TVelocityS;
class TFrictionAngle;
class TPoissonsRatio;
class TYoungsModulus;
class TDensity;
class TPorosity;
class TInitFriction;
class THardening;
class TPreConsolidation;
class TCapShape;
class TDilatation;
class TLatRatioMax;
class TLatRatioMin;
class TAzimuth;
class TCreepA1;
class TCreepN1;
class TCreepA2;
class TCreepN2;
class TFluidBulkModulus;
class THardCohesion1;
class THardCohesion2;
class THardCohesion3;
class THardFriction1;
class THardFriction2;
class THardFriction3;
class TEquivalentPlasticStrain1;
class TEquivalentPlasticStrain2;
class TEquivalentPlasticStrain3;
class TCreepQR1;
class TCreepQR2;
class TCreepAlpha;
class TTensileStretch;
class TThermalExpansion;
class TRigidParam1;
class TRigidParam2;
class TRigidParam3;
class TRigidParam4;
class TRigidParam5;
class TRigidParam6;
class TRigidParam7;
class TRigidParam8;
class TRigidParam9;
class TRigidParam10;
class TRigidParam11;
class TRigidParam12;
class TRigidParam13;
class TRigidParam14;
class TRigidParam15;
class TRigidParam16;
class TRigidParam17;
class TRigidParam18;
class TRigidParam19;
class TRigidParam20;
class TRigidParam21;
class TElasticHardening;
class TSecondaryPreconsolidation;
class TSecondaryHardening;
class TUniaxialElasticCompressibility;
class TUniaxialPlasticCompressibility;
class TYoungModulusNormal;
class TYoungModulusTransverse;
class TPoissonRatioNormal;
class TPoissonRatioTransverse;
class TLayerNormalIncl;
class TLayerNormalAzi;
class TFractStiffNormal;
class TFractStiffShear;
class TThermLinExpNormal;
class TThermLinExpLateral;
class TThermalConductivity;
class TThermalCapacity;
class THighFractDens;
class THighFractDensIncl;
class THighFractDensAzi;
class TLowFractDens;
class TLowFractDensIncl;
class TLowFractDensAzi;
class TInterFractDens;
class TPermeability;
class TViscosity;
class TYoungsModulusDecompaction;
class TPoissonsRatioDecompaction;
class TFluidThermalExpansionCoefficient;
class TFluidDensity;
class TReferenceStress;
class TApertureParameter;
class TGrainStiffnessParameter;
class TYoungsModulusNormalDecomp;
class TYoungModulusTransDecomp;
class TPoissonRatioNormalDecomp;
class TPoissonRatioTransDecomp;
class TAnisotropicShearModulus;
class TAnisotropicShearModulusDecomp;
class TThomsenEpsilon;
class TThomsenGamma;
class TThomsenDelta;
class TInitialFractureApertureHigh;
class TInitialFractureApertureInter;
class TInitialFractureApertureLow;
class TReferenceAperture;
class TDynamicUniaxialStiffness;
class TDynamicShearStiffness;
class TDisplacementVector;
class TNormalStress;
class TMeanStress;
class TTimeStrain;
class TDeltaV;
class TDeltaT;
class TDisplacementZ;
class TDummyMaterialParameter;
class TBoundaryKradMaterialParameter;
class TBoundaryKtanMaterialParameter;
class CElementValueSet;
class IValueSet;
class CNodalValueSet;
class CRpnValueSet;
class CNewWellPath;
class CNewWellPathEntry;
class CWellCasingCementInterfaceMaterialServer;
class CWellCasingCementInterface;
class CWellCasingNode;
class CWellCasingRTCI;
class CWellCasingRTCIEntry;
class CZoominModelEntry;
class CZoominModelPlaceHolder;
class CGVTResultTree;
class CGVTResultGroup;
class CGVTFactor;

  
class IGeomecModelConstVisitor : public graphnode::IConstVisitor
{
protected:
  IGeomecModelConstVisitor();

public:
  virtual bool Visit3DFormation(const C3DFormation& formation);
  virtual bool Visit3DHorizon(const C3DHorizon& horizon);
  virtual bool Visit3DModel(const C3DModel& model);
  virtual bool Visit3DSupportNode(const C3DSupportNode& node);
  virtual bool VisitAnalysisPoint(const CAnalysisPoint& point);
  virtual bool VisitAnalysisPointEntry(const CAnalysisPointEntry& entry);
  virtual bool VisitSupportDepletion(const CSupportDepletion& supportdepletion);
  virtual bool VisitBaseSupportNode(const CBaseSupportNode& node);
  virtual bool VisitBoundaryBase(const CBoundaryBase& boundary);
  virtual bool VisitBoundaryInterfaceDef(const CBoundaryInterfaceDef& def);
  virtual bool VisitCamClayUpscalingNode(const CCamClayUpscalingNode& node);
  virtual bool VisitColorGradient(const CColorGradient& gradient);
  virtual bool VisitColorScaleEntry(const CColorScaleEntry& entry);
  virtual bool VisitCrossSection(const CCrossSection& crosssection);
  virtual bool VisitCrossSectionEntry(const CCrossSectionEntry& entry);
  virtual bool VisitDepletionStage(const CDepletionStage& stage);
  virtual bool VisitDepletionStageEntry(const CDepletionStageEntry& entry);
  virtual bool VisitDisplacementSupportNode(const CDisplacementSupportNode& node);
  virtual bool VisitIElementSet(const IElementSet& elementset);
  virtual bool VisitElementSet(const CElementSet& elementset);
  virtual bool VisitExportResultData(const CExportResultData& data);
  virtual bool VisitExportResultDataEntry(const CExportResultDataEntry& entry);
  virtual bool VisitFaultParametersNode(const CFaultParametersNode& node);
  virtual bool VisitFaultPressureComponent(const CFaultPressureComponent& component);
  virtual bool VisitFaultPressure(const CFaultPressure& pressure);
  virtual bool VisitFaultPressureGradientComponent(const CFaultPressureGradientComponent& component);
  virtual bool VisitFaultPressureMinComponent(const CFaultPressureMinComponent& component);
  virtual bool VisitFaultPressureMaxComponent(const CFaultPressureMaxComponent& component);
  virtual bool VisitFaultPressureMaxGradientComponent(const CFaultPressureMaxGradientComponent& component);
  virtual bool VisitGocadElementSet(const CGocadElementSet& elementset);
  virtual bool VisitHomogenizationBox(const CHomogenizationBox& box);
  virtual bool VisitHomoBoxEntry(const CHomoBoxEntry& entry);
  virtual bool VisitHorizonBase(const CHorizonBase& horizon);
  virtual bool VisitHotSpot(const CHotSpot& hotspot);
  virtual bool VisitInterfaceBoundary(const CInterfaceBoundary& boundary);
  virtual bool VisitIScalingBox(const IScalingBox& box);
  virtual bool VisitMeasuredTopDisplacementsNode(const CMeasuredTopDisplacementsNode& node);
  virtual bool VisitMeshObserver(const CMeshObserver& observer);
  virtual bool VisitPillarMap(const CPillarMap& map);
  virtual bool VisitNonMeshedSurface(const CNonMeshedSurface& surface);
  virtual bool VisitNonMeshedSurfaceEntry(const CNonMeshedSurfaceEntry& entry);
  virtual bool VisitNonMeshedSurfaceParametersNode(const CNonMeshedSurfaceParametersNode& node);
  virtual bool VisitNonMeshedSurfacePressureComponent(const CNonMeshedSurfacePressureComponent& component);
  virtual bool VisitNonMeshedSurfacePressure(const CNonMeshedSurfacePressure& pressure);
  virtual bool VisitFormationObserver(const CFormationObserver& observer);
  virtual bool VisitStrainLoadGradientComponent(const CStrainLoadGradientComponent& component);
  virtual bool VisitStrainLoadGWCDummyComponent(const CStrainLoadGWCDummyComponent& component);
  virtual bool VisitStrainLoadRepeaterComponent(const CStrainLoadRepeaterComponent& component);
  virtual bool VisitStrainLoad(const CStrainLoad& load);
  virtual bool VisitThinLayerUpscalingNode(const CThinLayerUpscalingNode& node);
  virtual bool VisitIUpscalingNodeBase(const IUpscalingNodeBase& node);
  virtual bool VisitUpscalingEntry(const CUpscalingEntry& entry);
  virtual bool VisitUpscalingFormationsBranch(const CUpscalingFormationsBranch& branch);
  virtual bool VisitIUpscalingPointsetBranchBase(const IUpscalingPointsetBranchBase& branch);
  virtual bool VisitUpscalingPointsetRangesBranch(const CUpscalingPointsetRangesBranch& branch);
  virtual bool VisitUpscalingTargetPointsetBranch(const CUpscalingTargetPointsetBranch& branch);
  virtual bool VisitValueComponent(const CValueComponent& component);
  virtual bool VisitVolumetricStrainLoadGradientComponent(const CVolumetricStrainLoadGradientComponent& component);
  virtual bool VisitVolumetricStrainLoadGWCDummyComponent(const CVolumetricStrainLoadGWCDummyComponent& component);
  virtual bool VisitVolumetricStrainLoadRepeaterComponent(const CVolumetricStrainLoadRepeaterComponent& component);
  virtual bool VisitVolumetricStrainLoad(const CVolumetricStrainLoad& load);
  virtual bool VisitIFormationElementSet(const IFormationElementSet& elementset);
  virtual bool VisitFormationBase(const CFormationBase& formation);
  virtual bool VisitFormationThickness(const CFormationThickness& formationthickness);
  virtual bool VisitFormationPlane(const CFormationPlane& plane);
  virtual bool VisitFormationVolume(const CFormationVolume& volume);
  virtual bool VisitWellFormation(const CWellFormation& formation);
  virtual bool VisitWellFormationEntry(const CWellFormationEntry& entry);
  virtual bool VisitWellFormationVolume(const CWellFormationVolume& volume);
  virtual bool VisitGoCadModel(const CGoCadModel& model);
  virtual bool VisitGoCadSubModelEntry(const CGoCadSubModelEntry& entry);
  virtual bool VisitHexaBoundary(const CHexaBoundary& boundary);
  virtual bool VisitHexaFormationVolume(const CHexaFormationVolume& volume);
  virtual bool VisitHexaFormation(const CHexaFormation& formation);
  virtual bool VisitHexaFormationEntry(const CHexaFormationEntry& entry);
  virtual bool VisitHexaHorizon(const CHexaHorizon& horizon);
  virtual bool VisitHexaHorizonEntry(const CHexaHorizonEntry& entry);
  virtual bool VisitHexaMesh(const CHexaMesh& mesh);
  virtual bool VisitHexaMeshRegionBase(const CHexaMeshRegionBase& region);
  virtual bool VisitHexaMainMeshRegion(const CHexaMainMeshRegion& region);
  virtual bool VisitHexaSubMeshRegion(const CHexaSubMeshRegion& region);
  virtual bool VisitHexaMeshRegionEntry(const CHexaMeshRegionEntry& entry);
  virtual bool VisitHexaModel(const CHexaModel& model);
  virtual bool VisitHexaSurface(const CHexaSurface& surface);
  virtual bool VisitIMaterial(const IMaterial& material);
  virtual bool VisitIMaterialBase(const IMaterialBase& material);
  virtual bool VisitIMaterialRock(const IMaterialRock& material);
  virtual bool VisitIMaterialServerBase(const IMaterialServerBase& server);
  virtual bool VisitInterfaceMaterial(const CInterfaceMaterial& material);
  virtual bool VisitInterfaceMaterialEntry(const CInterfaceMaterialEntry& entry);
  virtual bool VisitMaterialAnisotropicCamClay(const CMaterialAnisotropicCamClay& material);
  virtual bool VisitMaterialCamClay(const CMaterialCamClay& material);
  virtual bool VisitMaterialCamClayCreep(const CMaterialCamClayCreep& material);
  virtual bool VisitMaterialCreep(const CMaterialCreep& material);
  virtual bool VisitMaterialDualCapLinEla(const CMaterialDualCapLinEla& material);
  virtual bool VisitMaterialEntry(const CMaterialEntry& entry);
  virtual bool VisitMaterialFractAnisotropy(const CMaterialFractAnisotropy& material);
  virtual bool VisitMaterialFractureAperture(const CMaterialFractureAperture& material);
  virtual bool VisitMaterialFractureAperture2(const CMaterialFractureAperture2& material);
  virtual bool VisitMaterialFractureApertureBase(const CMaterialFractureApertureBase& material);
  virtual bool VisitMaterialLinear(const CMaterialLinear& material);
  virtual bool VisitMaterialMCCohesionHard1(const CMaterialMCCohesionHard1& material);
  virtual bool VisitMaterialMCCohesionHard2(const CMaterialMCCohesionHard2& material);
  virtual bool VisitMaterialMCCohesionHard3(const CMaterialMCCohesionHard3& material);
  virtual bool VisitMaterialMCFrictionHard1(const CMaterialMCFrictionHard1& material);
  virtual bool VisitMaterialMCFrictionHard2(const CMaterialMCFrictionHard2& material);
  virtual bool VisitMaterialMCFrictionHard3(const CMaterialMCFrictionHard3& material);
  virtual bool VisitMaterialModMohrCo(const CMaterialModMohrCo& material);
  virtual bool VisitMaterialMohrCo(const CMaterialMohrCo& material);
  virtual bool VisitMaterialResult(const CMaterialResult& matresult);
  virtual bool VisitMaterialResultTree(const CMaterialResultTree& tree);
  virtual bool VisitMaterialRigidity(const CMaterialRigidity& material);
  virtual bool VisitMaterialServer(const CMaterialServer& server);
  virtual bool VisitMaterialUndrained(const CMaterialUndrained& material);
  virtual bool VisitMaterialUpscaledAnisotropy(const CMaterialUpscaledAnisotropy& material);
  virtual bool VisitWellCasingCement(const CWellCasingCement& cement);
  virtual bool VisitWellCasingMaterialServer(const CWellCasingMaterialServer& server);
  virtual bool VisitWellCasingSteel(const CWellCasingSteel& steel);
  virtual bool VisitWellCasingSteelMaterial(const CWellCasingSteelMaterial& material);
  virtual bool VisitWellCasingSteelMaterialEntry(const CWellCasingSteelMaterialEntry& entry);
  virtual bool VisitIWellMesh(const IWellMesh& mesh);
  virtual bool VisitMeshBase(const CMeshBase& mesh);
  virtual bool VisitMeshRegionBase(const CMeshRegionBase& region);
  virtual bool VisitMeshResult(const CMeshResult& result);
  virtual bool VisitMeshResultTree(const CMeshResultTree& tree);
  virtual bool VisitWellCasingMesh(const CWellCasingMesh& mesh);
  virtual bool VisitWellZoomInMesh(const CWellZoomInMesh& mesh);
  virtual bool VisitEclipseModel(const CEclipseModel& model);
  virtual bool VisitEclipseSubModelEntry(const CEclipseSubModelEntry& entry);
  virtual bool VisitIWellModel(const IWellModel& model);
  virtual bool VisitModelBase(const CModelBase& model);
  virtual bool VisitWellCasingModel(const CWellCasingModel& model);
  virtual bool VisitWellCasingFormationEntry(const CWellCasingFormationEntry& entry);
  virtual bool VisitWellZoomInModel(const CWellZoomInModel& model);
  virtual bool VisitIPointSet(const IPointSet& pointset);
  virtual bool VisitPointSetEntry(const CPointSetEntry& entry);
  virtual bool VisitLasPointSet(const CLasPointSet& pointset);
  virtual bool VisitPointSet(const CPointSet& pointset);
  virtual bool VisitFractureMatrixComponentGWC(const CFractureMatrixComponentGWC& component);
  virtual bool VisitFractureMatrixComponentRepeater(const CFractureMatrixComponentRepeater& component);
  virtual bool VisitFractureMatrixPressure(const CFractureMatrixPressure& pressure);
  virtual bool VisitGlobalPressure(const CGlobalPressure& pressure);
  virtual bool VisitComponentGWC(const CComponentGWC& component);
  virtual bool VisitComponentRepeater(const CComponentRepeater& component);
  virtual bool VisitPressure(const CPressure& pressure);
  virtual bool VisitPressureSupportNode(const CPressureSupportNode& node);
  virtual bool VisitWellCasingInternalPressure(const CWellCasingInternalPressure& pressure);
  virtual bool VisitDerivedResult(const CDerivedResult& result);
  virtual bool VisitDerivedResultGroup(const CDerivedResultGroup& group);
  virtual bool VisitIVectorResult(const IVectorResult& result);
  virtual bool VisitVectorResult(const CVectorResult& result);
  virtual bool VisitResultGroup(const CResultGroup& group);
  virtual bool VisitIResult(const IResult& result);
  virtual bool VisitIResultComponent(const IResultComponent& component);
  virtual bool VisitIScalarResultComponent(const IScalarResultComponent& component);
  virtual bool VisitResultTree(const CResultTree& tree);
  virtual bool VisitStaborResult(const CStaborResult& result);
  virtual bool VisitGVTSettings(const CGVTSettings& settings);
  virtual bool VisitQBSettings(const CQBSettings& settings);
  virtual bool VisitSurfaceBase(const CSurfaceBase& surface);
  virtual bool VisitSurfaceEntry(const CSurfaceEntry& entry);
  virtual bool VisitCalculatedTemperature(const CCalculatedTemperature& temperature);
  virtual bool VisitGlobalTemperature(const CGlobalTemperature& temperature);
  virtual bool VisitTemperatureGradientComponent(const CTemperatureGradientComponent& component);
  virtual bool VisitTemperatureGWCDummyComponent(const CTemperatureGWCDummyComponent& component);
  virtual bool VisitTemperatureRepeaterComponent(const CTemperatureRepeaterComponent& component);
  virtual bool VisitTemperature(const CTemperature& temperature);
  virtual bool VisitWellCasingInternalTemperature(const CWellCasingInternalTemperature& temperature);
  virtual bool VisitFractTensor(const CFractTensor& tensor);
  virtual bool VisitIStrainTensorGroup(const IStrainTensorGroup& group);
  virtual bool VisitIStressTensorGroup(const IStressTensorGroup& group);
  virtual bool VisitITensorGroup(const ITensorGroup& group);
  virtual bool VisitMatParamsTensor(const CMatParamsTensor& tensor);
  virtual bool VisitTStressTensor(const TStressTensor& tensor);
  virtual bool VisitTStrainTensor(const TStrainTensor& tensor);
  virtual bool VisitTetraBoundary(const CTetraBoundary& boundary);
  virtual bool VisitTetraFormationVolume(const CTetraFormationVolume& volume);
  virtual bool VisitTetraFormation(const CTetraFormation& formation);
  virtual bool VisitTetraFormationEntry(const CTetraFormationEntry& entry);
  virtual bool VisitTetraHorizonBase(const CTetraHorizonBase& horizon);
  virtual bool VisitTetraMesh(const CTetraMesh& mesh);
  virtual bool VisitTetraModel(const CTetraModel& model);
  virtual bool VisitTetraSubBoundary(const CTetraSubBoundary& boundary);
  virtual bool VisitTetraSubHorizon(const CTetraSubHorizon& horizon);
  virtual bool VisitTetraSubHorizonEntry(const CTetraSubHorizonEntry& entry);
  virtual bool VisitTetraSuperHorizon(const CTetraSuperHorizon& horizon);
  virtual bool VisitTetraSuperHorizonEntry(const CTetraSuperHorizonEntry& entry);
  virtual bool VisitTetraSurface(const CTetraSurface& surface);
  virtual bool VisitGlobalInitialStressNode(const CGlobalInitialStressNode& node);
  virtual bool VisitResultRegister(const CResultRegister& resultregister);
  virtual bool VisitTStrain(const TStrain& strain);
  virtual bool VisitValueType(const CValueType& valuetype);
  virtual bool VisitTLengthComponent(const TLengthComponent& component);
  virtual bool VisitSurfaceValueType(const CSurfaceValueType& valuetype);
  virtual bool VisitTPressure(const TPressure& pressure);
  virtual bool VisitTFractureMatrixPressure(const TFractureMatrixPressure& pressure);
  virtual bool VisitTTemperature(const TTemperature& temperature);
  virtual bool VisitTVolumetricStrain(const TVolumetricStrain& strain);
  virtual bool VisitTNormalStrain(const TNormalStrain& strain);
  virtual bool VisitTLateralStrain(const TLateralStrain& strain);
  virtual bool VisitTCohesion(const TCohesion& cohesion);
  virtual bool VisitTBulkStiffness(const TBulkStiffness& stiffness);
  virtual bool VisitTShearModulus(const TShearModulus& modulus);
  virtual bool VisitTVelocityP(const TVelocityP& vp);
  virtual bool VisitTVelocityS(const TVelocityS& vs);
  virtual bool VisitTFrictionAngle(const TFrictionAngle& angle);
  virtual bool VisitTPoissonsRatio(const TPoissonsRatio& ratio);
  virtual bool VisitTYoungsModulus(const TYoungsModulus& modulus);
  virtual bool VisitTDensity(const TDensity& density);
  virtual bool VisitTPorosity(const TPorosity& porosity);
  virtual bool VisitTInitFriction(const TInitFriction& friction);
  virtual bool VisitTHardening(const THardening& hardening);
  virtual bool VisitTPreConsolidation(const TPreConsolidation& preconsolidation);
  virtual bool VisitTCapShape(const TCapShape& capshape);
  virtual bool VisitTDilatation(const TDilatation& dilatation);
  virtual bool VisitTLatRatioMax(const TLatRatioMax& ratio);
  virtual bool VisitTLatRatioMin(const TLatRatioMin& ratio);
  virtual bool VisitTAzimuth(const TAzimuth& azimuth);
  virtual bool VisitTCreepA1(const TCreepA1& a1);
  virtual bool VisitTCreepN1(const TCreepN1& n1);
  virtual bool VisitTCreepA2(const TCreepA2& a2);
  virtual bool VisitTCreepN2(const TCreepN2& n2);
  virtual bool VisitTFluidBulkModulus(const TFluidBulkModulus& modulus);
  virtual bool VisitTHardCohesion1(const THardCohesion1& cohesion);
  virtual bool VisitTHardCohesion2(const THardCohesion2& cohesion);
  virtual bool VisitTHardCohesion3(const THardCohesion3& cohesion);
  virtual bool VisitTHardFriction1(const THardFriction1& friction);
  virtual bool VisitTHardFriction2(const THardFriction2& friction);
  virtual bool VisitTHardFriction3(const THardFriction3& friction);
  virtual bool VisitTEquivalentPlasticStrain1(const TEquivalentPlasticStrain1& strain);
  virtual bool VisitTEquivalentPlasticStrain2(const TEquivalentPlasticStrain2& strain);
  virtual bool VisitTEquivalentPlasticStrain3(const TEquivalentPlasticStrain3& strain);
  virtual bool VisitTCreepQR1(const TCreepQR1& qr1);
  virtual bool VisitTCreepQR2(const TCreepQR2& qr2);
  virtual bool VisitTCreepAlpha(const TCreepAlpha& alpha);
  virtual bool VisitTTensileStretch(const TTensileStretch& tensilestretch);
  virtual bool VisitTThermalExpansion(const TThermalExpansion& expansion);
  virtual bool VisitTRigidParam1(const TRigidParam1& param);
  virtual bool VisitTRigidParam2(const TRigidParam2& param);
  virtual bool VisitTRigidParam3(const TRigidParam3& param);
  virtual bool VisitTRigidParam4(const TRigidParam4& param);
  virtual bool VisitTRigidParam5(const TRigidParam5& param);
  virtual bool VisitTRigidParam6(const TRigidParam6& param);
  virtual bool VisitTRigidParam7(const TRigidParam7& param);
  virtual bool VisitTRigidParam8(const TRigidParam8& param);
  virtual bool VisitTRigidParam9(const TRigidParam9& param);
  virtual bool VisitTRigidParam10(const TRigidParam10& param);
  virtual bool VisitTRigidParam11(const TRigidParam11& param);
  virtual bool VisitTRigidParam12(const TRigidParam12& param);
  virtual bool VisitTRigidParam13(const TRigidParam13& param);
  virtual bool VisitTRigidParam14(const TRigidParam14& param);
  virtual bool VisitTRigidParam15(const TRigidParam15& param);
  virtual bool VisitTRigidParam16(const TRigidParam16& param);
  virtual bool VisitTRigidParam17(const TRigidParam17& param);
  virtual bool VisitTRigidParam18(const TRigidParam18& param);
  virtual bool VisitTRigidParam19(const TRigidParam19& param);
  virtual bool VisitTRigidParam20(const TRigidParam20& param);
  virtual bool VisitTRigidParam21(const TRigidParam21& param);
  virtual bool VisitTElasticHardening(const TElasticHardening& hardening);
  virtual bool VisitTSecondaryPreconsolidation(const TSecondaryPreconsolidation& precon);
  virtual bool VisitTSecondaryHardening(const TSecondaryHardening& hardening);
  virtual bool VisitTUniaxialElasticCompressibility(const TUniaxialElasticCompressibility& comp);
  virtual bool VisitTUniaxialPlasticCompressibility(const TUniaxialPlasticCompressibility& comp);
  virtual bool VisitTYoungModulusNormal(const TYoungModulusNormal& modulus);
  virtual bool VisitTYoungModulusTransverse(const TYoungModulusTransverse& modulus);
  virtual bool VisitTPoissonRatioNormal(const TPoissonRatioNormal& ratio);
  virtual bool VisitTPoissonRatioTransverse(const TPoissonRatioTransverse& ratio);
  virtual bool VisitTLayerNormalIncl(const TLayerNormalIncl& incl);
  virtual bool VisitTLayerNormalAzi(const TLayerNormalAzi& azi);
  virtual bool VisitTFractStiffNormal(const TFractStiffNormal& stiff);
  virtual bool VisitTFractStiffShear(const TFractStiffShear& stiff);
  virtual bool VisitTThermLinExpNormal(const TThermLinExpNormal& exp);
  virtual bool VisitTThermLinExpLateral(const TThermLinExpLateral& exp);
  virtual bool VisitTThermalConductivity(const TThermalConductivity& conduc);
  virtual bool VisitTThermalCapacity(const TThermalCapacity& capacity);
  virtual bool VisitTHighFractDens(const THighFractDens& dens);
  virtual bool VisitTHighFractDensIncl(const THighFractDensIncl& incl);
  virtual bool VisitTHighFractDensAzi(const THighFractDensAzi& azi);
  virtual bool VisitTLowFractDens(const TLowFractDens& dens);
  virtual bool VisitTLowFractDensIncl(const TLowFractDensIncl& incl);
  virtual bool VisitTLowFractDensAzi(const TLowFractDensAzi& azi);
  virtual bool VisitTInterFractDens(const TInterFractDens& dens);
  virtual bool VisitTPermeability(const TPermeability& perm);
  virtual bool VisitTViscosity(const TViscosity& viscosity);
  virtual bool VisitTYoungsModulusDecompaction(const TYoungsModulusDecompaction& modulus);
  virtual bool VisitTPoissonsRatioDecompaction(const TPoissonsRatioDecompaction& ratio);
  virtual bool VisitTFluidThermalExpansionCoefficient(const TFluidThermalExpansionCoefficient& coefficient);
  virtual bool VisitTFluidDensity(const TFluidDensity& density);
  virtual bool VisitTReferenceStress(const TReferenceStress& refstress);
  virtual bool VisitTApertureParameter(const TApertureParameter& param);
  virtual bool VisitTGrainStiffnessParameter(const TGrainStiffnessParameter& param);
  virtual bool VisitTYoungsModulusNormalDecomp(const TYoungsModulusNormalDecomp& modulus);
  virtual bool VisitTYoungModulusTransDecomp(const TYoungModulusTransDecomp& modulus);
  virtual bool VisitTPoissonRatioNormalDecomp(const TPoissonRatioNormalDecomp& ratio);
  virtual bool VisitTPoissonRatioTransDecomp(const TPoissonRatioTransDecomp& ratio);
  virtual bool VisitTAnisotropicShearModulus(const TAnisotropicShearModulus& modulus);
  virtual bool VisitTAnisotropicShearModulusDecomp(const TAnisotropicShearModulusDecomp& modulus);
  virtual bool VisitTThomsenEpsilon(const TThomsenEpsilon& eps);
  virtual bool VisitTThomsenGamma(const TThomsenGamma& gamma);
  virtual bool VisitTThomsenDelta(const TThomsenDelta& delta);
  virtual bool VisitTInitialFractureApertureHigh(const TInitialFractureApertureHigh& ap);
  virtual bool VisitTInitialFractureApertureInter(const TInitialFractureApertureInter& ap);
  virtual bool VisitTInitialFractureApertureLow(const TInitialFractureApertureLow& ap);
  virtual bool VisitTReferenceAperture(const TReferenceAperture& ap);
  virtual bool VisitTDynamicUniaxialStiffness(const TDynamicUniaxialStiffness& stiffness);
  virtual bool VisitTDynamicShearStiffness(const TDynamicShearStiffness& stiffness);
  virtual bool VisitTDisplacementVector(const TDisplacementVector& vector);
  virtual bool VisitTNormalStress(const TNormalStress& value);
  virtual bool VisitTMeanStress(const TMeanStress& value);
  virtual bool VisitTTimeStrain(const TTimeStrain& value);
  virtual bool VisitTDeltaV(const TDeltaV& value);
  virtual bool VisitTDeltaT(const TDeltaT& value);
  virtual bool VisitTDisplacementZ(const TDisplacementZ& value);
  virtual bool VisitTDummyMaterialParameter(const TDummyMaterialParameter& value);
  virtual bool VisitTBoundaryKradMaterialParameter(const TBoundaryKradMaterialParameter& value);
  virtual bool VisitTBoundaryKtanMaterialParameter(const TBoundaryKtanMaterialParameter& value);
  virtual bool VisitElementValueSet(const CElementValueSet& valueset);
  virtual bool VisitIValueSet(const IValueSet& valueset);
  virtual bool VisitNodalValueSet(const CNodalValueSet& valueset);
  virtual bool VisitRpnValueSet(const CRpnValueSet& valueset);
  virtual bool VisitNewWellPath(const CNewWellPath& wellpath);
  virtual bool VisitNewWellPathEntry(const CNewWellPathEntry& entry);
  virtual bool VisitWellCasingCementInterfaceMaterialServer(const CWellCasingCementInterfaceMaterialServer& server);
  virtual bool VisitWellCasingCementInterface(const CWellCasingCementInterface& interf);
  virtual bool VisitWellCasingNode(const CWellCasingNode& node);
  virtual bool VisitWellCasingRTCI(const CWellCasingRTCI& rtci);
  virtual bool VisitWellCasingRTCIEntry(const CWellCasingRTCIEntry& entry);
  virtual bool VisitZoominModelEntry(const CZoominModelEntry& entry);
  virtual bool VisitZoominModelPlaceHolder(const CZoominModelPlaceHolder& placeholder);
  virtual bool VisitGVTResultTree(const CGVTResultTree& tree);
  virtual bool VisitGVTResultGroup(const CGVTResultGroup& group);
  virtual bool VisitGVTFactor(const CGVTFactor& composite);
};

class IGeomecModelVisitor : public graphnode::IVisitor
{
protected:
  IGeomecModelVisitor();

public:
  virtual bool Visit3DFormation(C3DFormation& formation);
  virtual bool Visit3DHorizon(C3DHorizon& horizon);
  virtual bool Visit3DModel(C3DModel& model);
  virtual bool Visit3DSupportNode(C3DSupportNode& node);
  virtual bool VisitAnalysisPoint(CAnalysisPoint& point);
  virtual bool VisitAnalysisPointEntry(CAnalysisPointEntry& entry);
  virtual bool VisitSupportDepletion(CSupportDepletion& supportdepletion);
  virtual bool VisitBaseSupportNode(CBaseSupportNode& node);
  virtual bool VisitBoundaryBase(CBoundaryBase& boundary);
  virtual bool VisitBoundaryInterfaceDef(CBoundaryInterfaceDef& def);
  virtual bool VisitCamClayUpscalingNode(CCamClayUpscalingNode& node);
  virtual bool VisitColorGradient(CColorGradient& gradient);
  virtual bool VisitColorScaleEntry(CColorScaleEntry& entry);
  virtual bool VisitCrossSection(CCrossSection& crosssection);
  virtual bool VisitCrossSectionEntry(CCrossSectionEntry& entry);
  virtual bool VisitDepletionStage(CDepletionStage& stage);
  virtual bool VisitDepletionStageEntry(CDepletionStageEntry& entry);
  virtual bool VisitDisplacementSupportNode(CDisplacementSupportNode& node);
  virtual bool VisitIElementSet(IElementSet& elementset);
  virtual bool VisitElementSet(CElementSet& elementset);
  virtual bool VisitExportResultData(CExportResultData& data);
  virtual bool VisitExportResultDataEntry(CExportResultDataEntry& entry);
  virtual bool VisitFaultParametersNode(CFaultParametersNode& node);
  virtual bool VisitFaultPressureComponent(CFaultPressureComponent& component);
  virtual bool VisitFaultPressure(CFaultPressure& pressure);
  virtual bool VisitFaultPressureGradientComponent(CFaultPressureGradientComponent& component);
  virtual bool VisitFaultPressureMinComponent(CFaultPressureMinComponent& component);
  virtual bool VisitFaultPressureMaxComponent(CFaultPressureMaxComponent& component);
  virtual bool VisitFaultPressureMaxGradientComponent(CFaultPressureMaxGradientComponent& component);
  virtual bool VisitGocadElementSet(CGocadElementSet& elementset);
  virtual bool VisitHomogenizationBox(CHomogenizationBox& box);
  virtual bool VisitHomoBoxEntry(CHomoBoxEntry& entry);
  virtual bool VisitHorizonBase(CHorizonBase& horizon);
  virtual bool VisitHotSpot(CHotSpot& hotspot);
  virtual bool VisitInterfaceBoundary(CInterfaceBoundary& boundary);
  virtual bool VisitIScalingBox(IScalingBox& box);
  virtual bool VisitMeasuredTopDisplacementsNode(CMeasuredTopDisplacementsNode& node);
  virtual bool VisitMeshObserver(CMeshObserver& observer);
  virtual bool VisitPillarMap(CPillarMap& map);
  virtual bool VisitNonMeshedSurface(CNonMeshedSurface& surface);
  virtual bool VisitNonMeshedSurfaceEntry(CNonMeshedSurfaceEntry& entry);
  virtual bool VisitNonMeshedSurfaceParametersNode(CNonMeshedSurfaceParametersNode& node);
  virtual bool VisitNonMeshedSurfacePressureComponent(CNonMeshedSurfacePressureComponent& component);
  virtual bool VisitNonMeshedSurfacePressure(CNonMeshedSurfacePressure& pressure);
  virtual bool VisitFormationObserver(CFormationObserver& observer);
  virtual bool VisitStrainLoadGradientComponent(CStrainLoadGradientComponent& component);
  virtual bool VisitStrainLoadGWCDummyComponent(CStrainLoadGWCDummyComponent& component);
  virtual bool VisitStrainLoadRepeaterComponent(CStrainLoadRepeaterComponent& component);
  virtual bool VisitStrainLoad(CStrainLoad& load);
  virtual bool VisitThinLayerUpscalingNode(CThinLayerUpscalingNode& node);
  virtual bool VisitIUpscalingNodeBase(IUpscalingNodeBase& node);
  virtual bool VisitUpscalingEntry(CUpscalingEntry& entry);
  virtual bool VisitUpscalingFormationsBranch(CUpscalingFormationsBranch& branch);
  virtual bool VisitIUpscalingPointsetBranchBase(IUpscalingPointsetBranchBase& branch);
  virtual bool VisitUpscalingPointsetRangesBranch(CUpscalingPointsetRangesBranch& branch);
  virtual bool VisitUpscalingTargetPointsetBranch(CUpscalingTargetPointsetBranch& branch);
  virtual bool VisitValueComponent(CValueComponent& component);
  virtual bool VisitVolumetricStrainLoadGradientComponent(CVolumetricStrainLoadGradientComponent& component);
  virtual bool VisitVolumetricStrainLoadGWCDummyComponent(CVolumetricStrainLoadGWCDummyComponent& component);
  virtual bool VisitVolumetricStrainLoadRepeaterComponent(CVolumetricStrainLoadRepeaterComponent& component);
  virtual bool VisitVolumetricStrainLoad(CVolumetricStrainLoad& load);
  virtual bool VisitIFormationElementSet(IFormationElementSet& elementset);
  virtual bool VisitFormationBase(CFormationBase& formation);
  virtual bool VisitFormationThickness(CFormationThickness& formationthickness);
  virtual bool VisitFormationPlane(CFormationPlane& plane);
  virtual bool VisitFormationVolume(CFormationVolume& volume);
  virtual bool VisitWellFormation(CWellFormation& formation);
  virtual bool VisitWellFormationEntry(CWellFormationEntry& entry);
  virtual bool VisitWellFormationVolume(CWellFormationVolume& volume);
  virtual bool VisitGoCadModel(CGoCadModel& model);
  virtual bool VisitGoCadSubModelEntry(CGoCadSubModelEntry& entry);
  virtual bool VisitHexaBoundary(CHexaBoundary& boundary);
  virtual bool VisitHexaFormationVolume(CHexaFormationVolume& volume);
  virtual bool VisitHexaFormation(CHexaFormation& formation);
  virtual bool VisitHexaFormationEntry(CHexaFormationEntry& entry);
  virtual bool VisitHexaHorizon(CHexaHorizon& horizon);
  virtual bool VisitHexaHorizonEntry(CHexaHorizonEntry& entry);
  virtual bool VisitHexaMesh(CHexaMesh& mesh);
  virtual bool VisitHexaMeshRegionBase(CHexaMeshRegionBase& region);
  virtual bool VisitHexaMainMeshRegion(CHexaMainMeshRegion& region);
  virtual bool VisitHexaSubMeshRegion(CHexaSubMeshRegion& region);
  virtual bool VisitHexaMeshRegionEntry(CHexaMeshRegionEntry& entry);
  virtual bool VisitHexaModel(CHexaModel& model);
  virtual bool VisitHexaSurface(CHexaSurface& surface);
  virtual bool VisitIMaterial(IMaterial& material);
  virtual bool VisitIMaterialBase(IMaterialBase& material);
  virtual bool VisitIMaterialRock(IMaterialRock& material);
  virtual bool VisitIMaterialServerBase(IMaterialServerBase& server);
  virtual bool VisitInterfaceMaterial(CInterfaceMaterial& material);
  virtual bool VisitInterfaceMaterialEntry(CInterfaceMaterialEntry& entry);
  virtual bool VisitMaterialAnisotropicCamClay(CMaterialAnisotropicCamClay& material);
  virtual bool VisitMaterialCamClay(CMaterialCamClay& material);
  virtual bool VisitMaterialCamClayCreep(CMaterialCamClayCreep& material);
  virtual bool VisitMaterialCreep(CMaterialCreep& material);
  virtual bool VisitMaterialDualCapLinEla(CMaterialDualCapLinEla& material);
  virtual bool VisitMaterialEntry(CMaterialEntry& entry);
  virtual bool VisitMaterialFractAnisotropy(CMaterialFractAnisotropy& material);
  virtual bool VisitMaterialFractureAperture(CMaterialFractureAperture& material);
  virtual bool VisitMaterialFractureAperture2(CMaterialFractureAperture2& material);
  virtual bool VisitMaterialFractureApertureBase(CMaterialFractureApertureBase& material);
  virtual bool VisitMaterialLinear(CMaterialLinear& material);
  virtual bool VisitMaterialMCCohesionHard1(CMaterialMCCohesionHard1& material);
  virtual bool VisitMaterialMCCohesionHard2(CMaterialMCCohesionHard2& material);
  virtual bool VisitMaterialMCCohesionHard3(CMaterialMCCohesionHard3& material);
  virtual bool VisitMaterialMCFrictionHard1(CMaterialMCFrictionHard1& material);
  virtual bool VisitMaterialMCFrictionHard2(CMaterialMCFrictionHard2& material);
  virtual bool VisitMaterialMCFrictionHard3(CMaterialMCFrictionHard3& material);
  virtual bool VisitMaterialModMohrCo(CMaterialModMohrCo& material);
  virtual bool VisitMaterialMohrCo(CMaterialMohrCo& material);
  virtual bool VisitMaterialResult(CMaterialResult& matresult);
  virtual bool VisitMaterialResultTree(CMaterialResultTree& tree);
  virtual bool VisitMaterialRigidity(CMaterialRigidity& material);
  virtual bool VisitMaterialServer(CMaterialServer& server);
  virtual bool VisitMaterialUndrained(CMaterialUndrained& material);
  virtual bool VisitMaterialUpscaledAnisotropy(CMaterialUpscaledAnisotropy& material);
  virtual bool VisitWellCasingCement(CWellCasingCement& cement);
  virtual bool VisitWellCasingMaterialServer(CWellCasingMaterialServer& server);
  virtual bool VisitWellCasingSteel(CWellCasingSteel& steel);
  virtual bool VisitWellCasingSteelMaterial(CWellCasingSteelMaterial& material);
  virtual bool VisitWellCasingSteelMaterialEntry(CWellCasingSteelMaterialEntry& entry);
  virtual bool VisitIWellMesh(IWellMesh& mesh);
  virtual bool VisitMeshBase(CMeshBase& mesh);
  virtual bool VisitMeshRegionBase(CMeshRegionBase& region);
  virtual bool VisitMeshResult(CMeshResult& result);
  virtual bool VisitMeshResultTree(CMeshResultTree& tree);
  virtual bool VisitWellCasingMesh(CWellCasingMesh& mesh);
  virtual bool VisitWellZoomInMesh(CWellZoomInMesh& mesh);
  virtual bool VisitEclipseModel(CEclipseModel& model);
  virtual bool VisitEclipseSubModelEntry(CEclipseSubModelEntry& entry);
  virtual bool VisitIWellModel(IWellModel& model);
  virtual bool VisitModelBase(CModelBase& model);
  virtual bool VisitWellCasingModel(CWellCasingModel& model);
  virtual bool VisitWellCasingFormationEntry(CWellCasingFormationEntry& entry);
  virtual bool VisitWellZoomInModel(CWellZoomInModel& model);
  virtual bool VisitIPointSet(IPointSet& pointset);
  virtual bool VisitPointSetEntry(CPointSetEntry& entry);
  virtual bool VisitLasPointSet(CLasPointSet& pointset);
  virtual bool VisitPointSet(CPointSet& pointset);
  virtual bool VisitFractureMatrixComponentGWC(CFractureMatrixComponentGWC& component);
  virtual bool VisitFractureMatrixComponentRepeater(CFractureMatrixComponentRepeater& component);
  virtual bool VisitFractureMatrixPressure(CFractureMatrixPressure& pressure);
  virtual bool VisitGlobalPressure(CGlobalPressure& pressure);
  virtual bool VisitComponentGWC(CComponentGWC& component);
  virtual bool VisitComponentRepeater(CComponentRepeater& component);
  virtual bool VisitPressure(CPressure& pressure);
  virtual bool VisitPressureSupportNode(CPressureSupportNode& node);
  virtual bool VisitWellCasingInternalPressure(CWellCasingInternalPressure& pressure);
  virtual bool VisitDerivedResult(CDerivedResult& result);
  virtual bool VisitDerivedResultGroup(CDerivedResultGroup& group);
  virtual bool VisitIVectorResult(IVectorResult& result);
  virtual bool VisitVectorResult(CVectorResult& result);
  virtual bool VisitResultGroup(CResultGroup& group);
  virtual bool VisitIResult(IResult& result);
  virtual bool VisitIResultComponent(IResultComponent& component);
  virtual bool VisitIScalarResultComponent(IScalarResultComponent& component);
  virtual bool VisitResultTree(CResultTree& tree);
  virtual bool VisitStaborResult(CStaborResult& result);
  virtual bool VisitGVTSettings(CGVTSettings& settings);
  virtual bool VisitQBSettings(CQBSettings& settings);
  virtual bool VisitSurfaceBase(CSurfaceBase& surface);
  virtual bool VisitSurfaceEntry(CSurfaceEntry& entry);
  virtual bool VisitCalculatedTemperature(CCalculatedTemperature& temperature);
  virtual bool VisitGlobalTemperature(CGlobalTemperature& temperature);
  virtual bool VisitTemperatureGradientComponent(CTemperatureGradientComponent& component);
  virtual bool VisitTemperatureGWCDummyComponent(CTemperatureGWCDummyComponent& component);
  virtual bool VisitTemperatureRepeaterComponent(CTemperatureRepeaterComponent& component);
  virtual bool VisitTemperature(CTemperature& temperature);
  virtual bool VisitWellCasingInternalTemperature(CWellCasingInternalTemperature& temperature);
  virtual bool VisitFractTensor(CFractTensor& tensor);
  virtual bool VisitIStrainTensorGroup(IStrainTensorGroup& group);
  virtual bool VisitIStressTensorGroup(IStressTensorGroup& group);
  virtual bool VisitITensorGroup(ITensorGroup& group);
  virtual bool VisitMatParamsTensor(CMatParamsTensor& tensor);
  virtual bool VisitTStressTensor(TStressTensor& tensor);
  virtual bool VisitTStrainTensor(TStrainTensor& tensor);
  virtual bool VisitTetraBoundary(CTetraBoundary& boundary);
  virtual bool VisitTetraFormationVolume(CTetraFormationVolume& volume);
  virtual bool VisitTetraFormation(CTetraFormation& formation);
  virtual bool VisitTetraFormationEntry(CTetraFormationEntry& entry);
  virtual bool VisitTetraHorizonBase(CTetraHorizonBase& horizon);
  virtual bool VisitTetraMesh(CTetraMesh& mesh);
  virtual bool VisitTetraModel(CTetraModel& model);
  virtual bool VisitTetraSubBoundary(CTetraSubBoundary& boundary);
  virtual bool VisitTetraSubHorizon(CTetraSubHorizon& horizon);
  virtual bool VisitTetraSubHorizonEntry(CTetraSubHorizonEntry& entry);
  virtual bool VisitTetraSuperHorizon(CTetraSuperHorizon& horizon);
  virtual bool VisitTetraSuperHorizonEntry(CTetraSuperHorizonEntry& entry);
  virtual bool VisitTetraSurface(CTetraSurface& surface);
  virtual bool VisitGlobalInitialStressNode(CGlobalInitialStressNode& node);
  virtual bool VisitResultRegister(CResultRegister& resultregister);
  virtual bool VisitTStrain(TStrain& strain);
  virtual bool VisitValueType(CValueType& valuetype);
  virtual bool VisitTLengthComponent(TLengthComponent& component);
  virtual bool VisitSurfaceValueType(CSurfaceValueType& valuetype);
  virtual bool VisitTPressure(TPressure& pressure);
  virtual bool VisitTFractureMatrixPressure(TFractureMatrixPressure& pressure);
  virtual bool VisitTTemperature(TTemperature& temperature);
  virtual bool VisitTVolumetricStrain(TVolumetricStrain& strain);
  virtual bool VisitTNormalStrain(TNormalStrain& strain);
  virtual bool VisitTLateralStrain(TLateralStrain& strain);
  virtual bool VisitTCohesion(TCohesion& cohesion);
  virtual bool VisitTBulkStiffness(TBulkStiffness& stiffness);
  virtual bool VisitTShearModulus(TShearModulus& modulus);
  virtual bool VisitTVelocityP(TVelocityP& vp);
  virtual bool VisitTVelocityS(TVelocityS& vs);
  virtual bool VisitTFrictionAngle(TFrictionAngle& angle);
  virtual bool VisitTPoissonsRatio(TPoissonsRatio& ratio);
  virtual bool VisitTYoungsModulus(TYoungsModulus& modulus);
  virtual bool VisitTDensity(TDensity& density);
  virtual bool VisitTPorosity(TPorosity& porosity);
  virtual bool VisitTInitFriction(TInitFriction& friction);
  virtual bool VisitTHardening(THardening& hardening);
  virtual bool VisitTPreConsolidation(TPreConsolidation& preconsolidation);
  virtual bool VisitTCapShape(TCapShape& capshape);
  virtual bool VisitTDilatation(TDilatation& dilatation);
  virtual bool VisitTLatRatioMax(TLatRatioMax& ratio);
  virtual bool VisitTLatRatioMin(TLatRatioMin& ratio);
  virtual bool VisitTAzimuth(TAzimuth& azimuth);
  virtual bool VisitTCreepA1(TCreepA1& a1);
  virtual bool VisitTCreepN1(TCreepN1& n1);
  virtual bool VisitTCreepA2(TCreepA2& a2);
  virtual bool VisitTCreepN2(TCreepN2& n2);
  virtual bool VisitTFluidBulkModulus(TFluidBulkModulus& modulus);
  virtual bool VisitTHardCohesion1(THardCohesion1& cohesion);
  virtual bool VisitTHardCohesion2(THardCohesion2& cohesion);
  virtual bool VisitTHardCohesion3(THardCohesion3& cohesion);
  virtual bool VisitTHardFriction1(THardFriction1& friction);
  virtual bool VisitTHardFriction2(THardFriction2& friction);
  virtual bool VisitTHardFriction3(THardFriction3& friction);
  virtual bool VisitTEquivalentPlasticStrain1(TEquivalentPlasticStrain1& strain);
  virtual bool VisitTEquivalentPlasticStrain2(TEquivalentPlasticStrain2& strain);
  virtual bool VisitTEquivalentPlasticStrain3(TEquivalentPlasticStrain3& strain);
  virtual bool VisitTCreepQR1(TCreepQR1& qr1);
  virtual bool VisitTCreepQR2(TCreepQR2& qr2);
  virtual bool VisitTCreepAlpha(TCreepAlpha& alpha);
  virtual bool VisitTTensileStretch(TTensileStretch& tensilestretch);
  virtual bool VisitTThermalExpansion(TThermalExpansion& expansion);
  virtual bool VisitTRigidParam1(TRigidParam1& param);
  virtual bool VisitTRigidParam2(TRigidParam2& param);
  virtual bool VisitTRigidParam3(TRigidParam3& param);
  virtual bool VisitTRigidParam4(TRigidParam4& param);
  virtual bool VisitTRigidParam5(TRigidParam5& param);
  virtual bool VisitTRigidParam6(TRigidParam6& param);
  virtual bool VisitTRigidParam7(TRigidParam7& param);
  virtual bool VisitTRigidParam8(TRigidParam8& param);
  virtual bool VisitTRigidParam9(TRigidParam9& param);
  virtual bool VisitTRigidParam10(TRigidParam10& param);
  virtual bool VisitTRigidParam11(TRigidParam11& param);
  virtual bool VisitTRigidParam12(TRigidParam12& param);
  virtual bool VisitTRigidParam13(TRigidParam13& param);
  virtual bool VisitTRigidParam14(TRigidParam14& param);
  virtual bool VisitTRigidParam15(TRigidParam15& param);
  virtual bool VisitTRigidParam16(TRigidParam16& param);
  virtual bool VisitTRigidParam17(TRigidParam17& param);
  virtual bool VisitTRigidParam18(TRigidParam18& param);
  virtual bool VisitTRigidParam19(TRigidParam19& param);
  virtual bool VisitTRigidParam20(TRigidParam20& param);
  virtual bool VisitTRigidParam21(TRigidParam21& param);
  virtual bool VisitTElasticHardening(TElasticHardening& hardening);
  virtual bool VisitTSecondaryPreconsolidation(TSecondaryPreconsolidation& precon);
  virtual bool VisitTSecondaryHardening(TSecondaryHardening& hardening);
  virtual bool VisitTUniaxialElasticCompressibility(TUniaxialElasticCompressibility& comp);
  virtual bool VisitTUniaxialPlasticCompressibility(TUniaxialPlasticCompressibility& comp);
  virtual bool VisitTYoungModulusNormal(TYoungModulusNormal& modulus);
  virtual bool VisitTYoungModulusTransverse(TYoungModulusTransverse& modulus);
  virtual bool VisitTPoissonRatioNormal(TPoissonRatioNormal& ratio);
  virtual bool VisitTPoissonRatioTransverse(TPoissonRatioTransverse& ratio);
  virtual bool VisitTLayerNormalIncl(TLayerNormalIncl& incl);
  virtual bool VisitTLayerNormalAzi(TLayerNormalAzi& azi);
  virtual bool VisitTFractStiffNormal(TFractStiffNormal& stiff);
  virtual bool VisitTFractStiffShear(TFractStiffShear& stiff);
  virtual bool VisitTThermLinExpNormal(TThermLinExpNormal& exp);
  virtual bool VisitTThermLinExpLateral(TThermLinExpLateral& exp);
  virtual bool VisitTThermalConductivity(TThermalConductivity& conduc);
  virtual bool VisitTThermalCapacity(TThermalCapacity& capacity);
  virtual bool VisitTHighFractDens(THighFractDens& dens);
  virtual bool VisitTHighFractDensIncl(THighFractDensIncl& incl);
  virtual bool VisitTHighFractDensAzi(THighFractDensAzi& azi);
  virtual bool VisitTLowFractDens(TLowFractDens& dens);
  virtual bool VisitTLowFractDensIncl(TLowFractDensIncl& incl);
  virtual bool VisitTLowFractDensAzi(TLowFractDensAzi& azi);
  virtual bool VisitTInterFractDens(TInterFractDens& dens);
  virtual bool VisitTPermeability(TPermeability& perm);
  virtual bool VisitTViscosity(TViscosity& viscosity);
  virtual bool VisitTYoungsModulusDecompaction(TYoungsModulusDecompaction& modulus);
  virtual bool VisitTPoissonsRatioDecompaction(TPoissonsRatioDecompaction& ratio);
  virtual bool VisitTFluidThermalExpansionCoefficient(TFluidThermalExpansionCoefficient& coefficient);
  virtual bool VisitTFluidDensity(TFluidDensity& density);
  virtual bool VisitTReferenceStress(TReferenceStress& refstress);
  virtual bool VisitTApertureParameter(TApertureParameter& param);
  virtual bool VisitTGrainStiffnessParameter(TGrainStiffnessParameter& param);
  virtual bool VisitTYoungsModulusNormalDecomp(TYoungsModulusNormalDecomp& modulus);
  virtual bool VisitTYoungModulusTransDecomp(TYoungModulusTransDecomp& modulus);
  virtual bool VisitTPoissonRatioNormalDecomp(TPoissonRatioNormalDecomp& ratio);
  virtual bool VisitTPoissonRatioTransDecomp(TPoissonRatioTransDecomp& ratio);
  virtual bool VisitTAnisotropicShearModulus(TAnisotropicShearModulus& modulus);
  virtual bool VisitTAnisotropicShearModulusDecomp(TAnisotropicShearModulusDecomp& modulus);
  virtual bool VisitTThomsenEpsilon(TThomsenEpsilon& eps);
  virtual bool VisitTThomsenGamma(TThomsenGamma& gamma);
  virtual bool VisitTThomsenDelta(TThomsenDelta& delta);
  virtual bool VisitTInitialFractureApertureHigh(TInitialFractureApertureHigh& ap);
  virtual bool VisitTInitialFractureApertureInter(TInitialFractureApertureInter& ap);
  virtual bool VisitTInitialFractureApertureLow(TInitialFractureApertureLow& ap);
  virtual bool VisitTReferenceAperture(TReferenceAperture& ap);
  virtual bool VisitTDynamicUniaxialStiffness(TDynamicUniaxialStiffness& stiffness);
  virtual bool VisitTDynamicShearStiffness(TDynamicShearStiffness& stiffness);
  virtual bool VisitTDisplacementVector(TDisplacementVector& vector);
  virtual bool VisitTNormalStress(TNormalStress& value);
  virtual bool VisitTMeanStress(TMeanStress& value);
  virtual bool VisitTTimeStrain(TTimeStrain& value);
  virtual bool VisitTDeltaV(TDeltaV& value);
  virtual bool VisitTDeltaT(TDeltaT& value);
  virtual bool VisitTDisplacementZ(TDisplacementZ& value);
  virtual bool VisitTDummyMaterialParameter(TDummyMaterialParameter& value);
  virtual bool VisitTBoundaryKradMaterialParameter(TBoundaryKradMaterialParameter& value);
  virtual bool VisitTBoundaryKtanMaterialParameter(TBoundaryKtanMaterialParameter& value);
  virtual bool VisitElementValueSet(CElementValueSet& valueset);
  virtual bool VisitIValueSet(IValueSet& valueset);
  virtual bool VisitNodalValueSet(CNodalValueSet& valueset);
  virtual bool VisitRpnValueSet(CRpnValueSet& valueset);
  virtual bool VisitNewWellPath(CNewWellPath& wellpath);
  virtual bool VisitNewWellPathEntry(CNewWellPathEntry& entry);
  virtual bool VisitWellCasingCementInterfaceMaterialServer(CWellCasingCementInterfaceMaterialServer& server);
  virtual bool VisitWellCasingCementInterface(CWellCasingCementInterface& interf);
  virtual bool VisitWellCasingNode(CWellCasingNode& node);
  virtual bool VisitWellCasingRTCI(CWellCasingRTCI& rtci);
  virtual bool VisitWellCasingRTCIEntry(CWellCasingRTCIEntry& entry);
  virtual bool VisitZoominModelEntry(CZoominModelEntry& entry);
  virtual bool VisitZoominModelPlaceHolder(CZoominModelPlaceHolder& placeholder);
  virtual bool VisitGVTResultTree(CGVTResultTree& tree);
  virtual bool VisitGVTResultGroup(CGVTResultGroup& group);
  virtual bool VisitGVTFactor(CGVTFactor& composite);
};

#endif // _GEOMECMODELVISITOR_H_
