// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "wellspreadsheet.h"

// Dispatch interfaces referenced by this interface
#include "Picture.h"
#include "Font.h"

/////////////////////////////////////////////////////////////////////////////
// CWellSpreadSheet

IMPLEMENT_DYNCREATE(CWellSpreadSheet, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CWellSpreadSheet properties

short CWellSpreadSheet::GetAction()
{
  short result;
  GetProperty(0x1, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetAction(short propVal)
{
  SetProperty(0x1, VT_I2, propVal);
}

long CWellSpreadSheet::GetActiveCol()
{
  long result;
  GetProperty(0x2, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetActiveCol(long propVal)
{
  SetProperty(0x2, VT_I4, propVal);
}

long CWellSpreadSheet::GetActiveRow()
{
  long result;
  GetProperty(0x3, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetActiveRow(long propVal)
{
  SetProperty(0x3, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetAllowCellOverflow()
{
  BOOL result;
  GetProperty(0x4, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetAllowCellOverflow(BOOL propVal)
{
  SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetAllowDragDrop()
{
  BOOL result;
  GetProperty(0x5, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetAllowDragDrop(BOOL propVal)
{
  SetProperty(0x5, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetAllowMultiBlocks()
{
  BOOL result;
  GetProperty(0x6, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetAllowMultiBlocks(BOOL propVal)
{
  SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetAllowUserFormulas()
{
  BOOL result;
  GetProperty(0x7, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetAllowUserFormulas(BOOL propVal)
{
  SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetArrowsExitEditMode()
{
  BOOL result;
  GetProperty(0x8, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetArrowsExitEditMode(BOOL propVal)
{
  SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetAutoCalc()
{
  BOOL result;
  GetProperty(0x9, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetAutoCalc(BOOL propVal)
{
  SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetAutoClipboard()
{
  BOOL result;
  GetProperty(0xa, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetAutoClipboard(BOOL propVal)
{
  SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetAutoSize()
{
  BOOL result;
  GetProperty(0xb, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetAutoSize(BOOL propVal)
{
  SetProperty(0xb, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetBlockMode()
{
  BOOL result;
  GetProperty(0xc, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetBlockMode(BOOL propVal)
{
  SetProperty(0xc, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetButtonDrawMode()
{
  short result;
  GetProperty(0xd, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetButtonDrawMode(short propVal)
{
  SetProperty(0xd, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetCalcDependencies()
{
  BOOL result;
  GetProperty(0xe, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCalcDependencies(BOOL propVal)
{
  SetProperty(0xe, VT_BOOL, propVal);
}

unsigned long CWellSpreadSheet::GetCellBorderColor()
{
  unsigned long result;
  GetProperty(0xf, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCellBorderColor(unsigned long propVal)
{
  SetProperty(0xf, VT_I4, propVal);
}

short CWellSpreadSheet::GetCellBorderStyle()
{
  short result;
  GetProperty(0x10, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCellBorderStyle(short propVal)
{
  SetProperty(0x10, VT_I2, propVal);
}

short CWellSpreadSheet::GetCellBorderType()
{
  short result;
  GetProperty(0x11, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCellBorderType(short propVal)
{
  SetProperty(0x11, VT_I2, propVal);
}

short CWellSpreadSheet::GetCellType()
{
  short result;
  GetProperty(0x12, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCellType(short propVal)
{
  SetProperty(0x12, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetChangeMade()
{
  BOOL result;
  GetProperty(0x13, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetChangeMade(BOOL propVal)
{
  SetProperty(0x13, VT_BOOL, propVal);
}

CString CWellSpreadSheet::GetClip()
{
  CString result;
  GetProperty(0x14, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetClip(LPCTSTR propVal)
{
  SetProperty(0x14, VT_BSTR, propVal);
}

CString CWellSpreadSheet::GetClipValue()
{
  CString result;
  GetProperty(0x15, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetClipValue(LPCTSTR propVal)
{
  SetProperty(0x15, VT_BSTR, propVal);
}

long CWellSpreadSheet::GetCol()
{
  long result;
  GetProperty(0x16, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCol(long propVal)
{
  SetProperty(0x16, VT_I4, propVal);
}

long CWellSpreadSheet::GetCol2()
{
  long result;
  GetProperty(0x17, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCol2(long propVal)
{
  SetProperty(0x17, VT_I4, propVal);
}

long CWellSpreadSheet::GetColHeaderDisplay()
{
  long result;
  GetProperty(0x18, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetColHeaderDisplay(long propVal)
{
  SetProperty(0x18, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetColHidden()
{
  BOOL result;
  GetProperty(0x19, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetColHidden(BOOL propVal)
{
  SetProperty(0x19, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetColPageBreak()
{
  BOOL result;
  GetProperty(0x1a, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetColPageBreak(BOOL propVal)
{
  SetProperty(0x1a, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetColsFrozen()
{
  long result;
  GetProperty(0x1b, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetColsFrozen(long propVal)
{
  SetProperty(0x1b, VT_I4, propVal);
}

short CWellSpreadSheet::GetCursorStyle()
{
  short result;
  GetProperty(0x1c, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCursorStyle(short propVal)
{
  SetProperty(0x1c, VT_I2, propVal);
}

short CWellSpreadSheet::GetCursorType()
{
  short result;
  GetProperty(0x1d, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetCursorType(short propVal)
{
  SetProperty(0x1d, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetDataChanged()
{
  BOOL result;
  GetProperty(0x1e, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDataChanged(BOOL propVal)
{
  SetProperty(0x1e, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetDataColCnt()
{
  long result;
  GetProperty(0x1f, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDataColCnt(long propVal)
{
  SetProperty(0x1f, VT_I4, propVal);
}

CString CWellSpreadSheet::GetDataField()
{
  CString result;
  GetProperty(0x20, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDataField(LPCTSTR propVal)
{
  SetProperty(0x20, VT_BSTR, propVal);
}

BOOL CWellSpreadSheet::GetDataFillEvent()
{
  BOOL result;
  GetProperty(0x21, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDataFillEvent(BOOL propVal)
{
  SetProperty(0x21, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetDataRowCnt()
{
  long result;
  GetProperty(0x22, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDataRowCnt(long propVal)
{
  SetProperty(0x22, VT_I4, propVal);
}

LPUNKNOWN CWellSpreadSheet::GetDataSource()
{
  LPUNKNOWN result;
  GetProperty(0x23, VT_UNKNOWN, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDataSource(LPUNKNOWN propVal)
{
  SetProperty(0x23, VT_UNKNOWN, propVal);
}

BOOL CWellSpreadSheet::GetDAutoCellTypes()
{
  BOOL result;
  GetProperty(0x24, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDAutoCellTypes(BOOL propVal)
{
  SetProperty(0x24, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetDAutoFill()
{
  BOOL result;
  GetProperty(0x25, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDAutoFill(BOOL propVal)
{
  SetProperty(0x25, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetDAutoHeadings()
{
  BOOL result;
  GetProperty(0x26, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDAutoHeadings(BOOL propVal)
{
  SetProperty(0x26, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetDAutoSave()
{
  BOOL result;
  GetProperty(0x27, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDAutoSave(BOOL propVal)
{
  SetProperty(0x27, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetDAutoSizeCols()
{
  long result;
  GetProperty(0x28, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDAutoSizeCols(long propVal)
{
  SetProperty(0x28, VT_I4, propVal);
}

long CWellSpreadSheet::GetDestCol()
{
  long result;
  GetProperty(0x29, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDestCol(long propVal)
{
  SetProperty(0x29, VT_I4, propVal);
}

long CWellSpreadSheet::GetDestRow()
{
  long result;
  GetProperty(0x2a, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDestRow(long propVal)
{
  SetProperty(0x2a, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetDInformActiveRowChange()
{
  BOOL result;
  GetProperty(0x2b, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDInformActiveRowChange(BOOL propVal)
{
  SetProperty(0x2b, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetDisplayColHeaders()
{
  BOOL result;
  GetProperty(0x2c, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDisplayColHeaders(BOOL propVal)
{
  SetProperty(0x2c, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetDisplayRowHeaders()
{
  BOOL result;
  GetProperty(0x2d, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetDisplayRowHeaders(BOOL propVal)
{
  SetProperty(0x2d, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetEditEnterAction()
{
  long result;
  GetProperty(0x2e, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetEditEnterAction(long propVal)
{
  SetProperty(0x2e, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetEditMode()
{
  BOOL result;
  GetProperty(0x2f, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetEditMode(BOOL propVal)
{
  SetProperty(0x2f, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetEditModePermanent()
{
  BOOL result;
  GetProperty(0x30, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetEditModePermanent(BOOL propVal)
{
  SetProperty(0x30, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetEditModeReplace()
{
  BOOL result;
  GetProperty(0x31, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetEditModeReplace(BOOL propVal)
{
  SetProperty(0x31, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetFileNum()
{
  short result;
  GetProperty(0x32, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFileNum(short propVal)
{
  SetProperty(0x32, VT_I2, propVal);
}

short CWellSpreadSheet::GetFloatDefCurrencyChar()
{
  short result;
  GetProperty(0x33, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFloatDefCurrencyChar(short propVal)
{
  SetProperty(0x33, VT_I2, propVal);
}

short CWellSpreadSheet::GetFloatDefDecimalChar()
{
  short result;
  GetProperty(0x34, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFloatDefDecimalChar(short propVal)
{
  SetProperty(0x34, VT_I2, propVal);
}

short CWellSpreadSheet::GetFloatDefSepChar()
{
  short result;
  GetProperty(0x35, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFloatDefSepChar(short propVal)
{
  SetProperty(0x35, VT_I2, propVal);
}

CString CWellSpreadSheet::GetFormula()
{
  CString result;
  GetProperty(0x36, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFormula(LPCTSTR propVal)
{
  SetProperty(0x36, VT_BSTR, propVal);
}

unsigned long CWellSpreadSheet::GetGrayAreaBackColor()
{
  unsigned long result;
  GetProperty(0x37, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetGrayAreaBackColor(unsigned long propVal)
{
  SetProperty(0x37, VT_I4, propVal);
}

unsigned long CWellSpreadSheet::GetGridColor()
{
  unsigned long result;
  GetProperty(0x38, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetGridColor(unsigned long propVal)
{
  SetProperty(0x38, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetGridShowHoriz()
{
  BOOL result;
  GetProperty(0x39, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetGridShowHoriz(BOOL propVal)
{
  SetProperty(0x39, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetGridShowVert()
{
  BOOL result;
  GetProperty(0x3a, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetGridShowVert(BOOL propVal)
{
  SetProperty(0x3a, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetGridSolid()
{
  BOOL result;
  GetProperty(0x3b, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetGridSolid(BOOL propVal)
{
  SetProperty(0x3b, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetHDCPrinter()
{
  long result;
  GetProperty(0x3c, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetHDCPrinter(long propVal)
{
  SetProperty(0x3c, VT_I4, propVal);
}

short CWellSpreadSheet::GetInterfaceDesigner()
{
  short result;
  GetProperty(0x3d, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetInterfaceDesigner(short propVal)
{
  SetProperty(0x3d, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetIsBlockSelected()
{
  BOOL result;
  GetProperty(0x3e, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetIsBlockSelected(BOOL propVal)
{
  SetProperty(0x3e, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetLeftCol()
{
  long result;
  GetProperty(0x3f, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetLeftCol(long propVal)
{
  SetProperty(0x3f, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetLock()
{
  BOOL result;
  GetProperty(0x40, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetLock(BOOL propVal)
{
  SetProperty(0x40, VT_BOOL, propVal);
}

unsigned long CWellSpreadSheet::GetLockBackColor()
{
  unsigned long result;
  GetProperty(0x41, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetLockBackColor(unsigned long propVal)
{
  SetProperty(0x41, VT_I4, propVal);
}

unsigned long CWellSpreadSheet::GetLockForeColor()
{
  unsigned long result;
  GetProperty(0x42, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetLockForeColor(unsigned long propVal)
{
  SetProperty(0x42, VT_I4, propVal);
}

long CWellSpreadSheet::GetMaxCols()
{
  long result;
  GetProperty(0x43, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetMaxCols(long propVal)
{
  SetProperty(0x43, VT_I4, propVal);
}

long CWellSpreadSheet::GetMaxRows()
{
  long result;
  GetProperty(0x44, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetMaxRows(long propVal)
{
  SetProperty(0x44, VT_I4, propVal);
}

double CWellSpreadSheet::GetMaxTextCellHeight()
{
  double result;
  GetProperty(0x45, VT_R8, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetMaxTextCellHeight(double propVal)
{
  SetProperty(0x45, VT_R8, propVal);
}

double CWellSpreadSheet::GetMaxTextCellWidth()
{
  double result;
  GetProperty(0x46, VT_R8, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetMaxTextCellWidth(double propVal)
{
  SetProperty(0x46, VT_R8, propVal);
}

BOOL CWellSpreadSheet::GetMoveActiveOnFocus()
{
  BOOL result;
  GetProperty(0x47, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetMoveActiveOnFocus(BOOL propVal)
{
  SetProperty(0x47, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetMultiSelCount()
{
  long result;
  GetProperty(0x48, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetMultiSelCount(long propVal)
{
  SetProperty(0x48, VT_I4, propVal);
}

long CWellSpreadSheet::GetMultiSelIndex()
{
  long result;
  GetProperty(0x49, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetMultiSelIndex(long propVal)
{
  SetProperty(0x49, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetNoBeep()
{
  BOOL result;
  GetProperty(0x4a, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetNoBeep(BOOL propVal)
{
  SetProperty(0x4a, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetNoBorder()
{
  BOOL result;
  GetProperty(0x4b, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetNoBorder(BOOL propVal)
{
  SetProperty(0x4b, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetOperationMode()
{
  long result;
  GetProperty(0x4c, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetOperationMode(long propVal)
{
  SetProperty(0x4c, VT_I4, propVal);
}

long CWellSpreadSheet::GetPosition()
{
  long result;
  GetProperty(0x4d, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPosition(long propVal)
{
  SetProperty(0x4d, VT_I4, propVal);
}

CString CWellSpreadSheet::GetPrintAbortMsg()
{
  CString result;
  GetProperty(0x4e, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintAbortMsg(LPCTSTR propVal)
{
  SetProperty(0x4e, VT_BSTR, propVal);
}

BOOL CWellSpreadSheet::GetPrintBorder()
{
  BOOL result;
  GetProperty(0x4f, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintBorder(BOOL propVal)
{
  SetProperty(0x4f, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetPrintColHeaders()
{
  BOOL result;
  GetProperty(0x50, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintColHeaders(BOOL propVal)
{
  SetProperty(0x50, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetPrintColor()
{
  BOOL result;
  GetProperty(0x51, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintColor(BOOL propVal)
{
  SetProperty(0x51, VT_BOOL, propVal);
}

CString CWellSpreadSheet::GetPrintFooter()
{
  CString result;
  GetProperty(0x52, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintFooter(LPCTSTR propVal)
{
  SetProperty(0x52, VT_BSTR, propVal);
}

BOOL CWellSpreadSheet::GetPrintGrid()
{
  BOOL result;
  GetProperty(0x53, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintGrid(BOOL propVal)
{
  SetProperty(0x53, VT_BOOL, propVal);
}

CString CWellSpreadSheet::GetPrintHeader()
{
  CString result;
  GetProperty(0x54, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintHeader(LPCTSTR propVal)
{
  SetProperty(0x54, VT_BSTR, propVal);
}

CString CWellSpreadSheet::GetPrintJobName()
{
  CString result;
  GetProperty(0x55, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintJobName(LPCTSTR propVal)
{
  SetProperty(0x55, VT_BSTR, propVal);
}

long CWellSpreadSheet::GetPrintMarginBottom()
{
  long result;
  GetProperty(0x56, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintMarginBottom(long propVal)
{
  SetProperty(0x56, VT_I4, propVal);
}

long CWellSpreadSheet::GetPrintMarginLeft()
{
  long result;
  GetProperty(0x57, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintMarginLeft(long propVal)
{
  SetProperty(0x57, VT_I4, propVal);
}

long CWellSpreadSheet::GetPrintMarginRight()
{
  long result;
  GetProperty(0x58, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintMarginRight(long propVal)
{
  SetProperty(0x58, VT_I4, propVal);
}

long CWellSpreadSheet::GetPrintMarginTop()
{
  long result;
  GetProperty(0x59, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintMarginTop(long propVal)
{
  SetProperty(0x59, VT_I4, propVal);
}

short CWellSpreadSheet::GetPrintPageEnd()
{
  short result;
  GetProperty(0x5a, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintPageEnd(short propVal)
{
  SetProperty(0x5a, VT_I2, propVal);
}

short CWellSpreadSheet::GetPrintPageStart()
{
  short result;
  GetProperty(0x5b, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintPageStart(short propVal)
{
  SetProperty(0x5b, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetPrintRowHeaders()
{
  BOOL result;
  GetProperty(0x5c, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintRowHeaders(BOOL propVal)
{
  SetProperty(0x5c, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetPrintShadows()
{
  BOOL result;
  GetProperty(0x5d, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintShadows(BOOL propVal)
{
  SetProperty(0x5d, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetPrintType()
{
  short result;
  GetProperty(0x5e, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintType(short propVal)
{
  SetProperty(0x5e, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetPrintUseDataMax()
{
  BOOL result;
  GetProperty(0x5f, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintUseDataMax(BOOL propVal)
{
  SetProperty(0x5f, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetProcessTab()
{
  BOOL result;
  GetProperty(0x60, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetProcessTab(BOOL propVal)
{
  SetProperty(0x60, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetProtect()
{
  BOOL result;
  GetProperty(0x61, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetProtect(BOOL propVal)
{
  SetProperty(0x61, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetReDraw()
{
  BOOL result;
  GetProperty(0x62, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetReDraw(BOOL propVal)
{
  SetProperty(0x62, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetRestrictCols()
{
  BOOL result;
  GetProperty(0x63, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRestrictCols(BOOL propVal)
{
  SetProperty(0x63, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetRestrictRows()
{
  BOOL result;
  GetProperty(0x64, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRestrictRows(BOOL propVal)
{
  SetProperty(0x64, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetRetainSelBlock()
{
  BOOL result;
  GetProperty(0x65, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRetainSelBlock(BOOL propVal)
{
  SetProperty(0x65, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetRow()
{
  long result;
  GetProperty(0x66, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRow(long propVal)
{
  SetProperty(0x66, VT_I4, propVal);
}

long CWellSpreadSheet::GetRow2()
{
  long result;
  GetProperty(0x67, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRow2(long propVal)
{
  SetProperty(0x67, VT_I4, propVal);
}

long CWellSpreadSheet::GetRowHeaderDisplay()
{
  long result;
  GetProperty(0x68, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRowHeaderDisplay(long propVal)
{
  SetProperty(0x68, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetRowHidden()
{
  BOOL result;
  GetProperty(0x69, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRowHidden(BOOL propVal)
{
  SetProperty(0x69, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetRowPageBreak()
{
  BOOL result;
  GetProperty(0x6a, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRowPageBreak(BOOL propVal)
{
  SetProperty(0x6a, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetRowsFrozen()
{
  long result;
  GetProperty(0x6b, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetRowsFrozen(long propVal)
{
  SetProperty(0x6b, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetScrollBarExtMode()
{
  BOOL result;
  GetProperty(0x6c, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetScrollBarExtMode(BOOL propVal)
{
  SetProperty(0x6c, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetScrollBarMaxAlign()
{
  BOOL result;
  GetProperty(0x6d, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetScrollBarMaxAlign(BOOL propVal)
{
  SetProperty(0x6d, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetScrollBars()
{
  long result;
  GetProperty(0x6e, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetScrollBars(long propVal)
{
  SetProperty(0x6e, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetScrollBarShowMax()
{
  BOOL result;
  GetProperty(0x6f, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetScrollBarShowMax(BOOL propVal)
{
  SetProperty(0x6f, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetSelBlockCol()
{
  long result;
  GetProperty(0x70, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelBlockCol(long propVal)
{
  SetProperty(0x70, VT_I4, propVal);
}

long CWellSpreadSheet::GetSelBlockCol2()
{
  long result;
  GetProperty(0x71, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelBlockCol2(long propVal)
{
  SetProperty(0x71, VT_I4, propVal);
}

long CWellSpreadSheet::GetSelBlockRow()
{
  long result;
  GetProperty(0x72, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelBlockRow(long propVal)
{
  SetProperty(0x72, VT_I4, propVal);
}

long CWellSpreadSheet::GetSelBlockRow2()
{
  long result;
  GetProperty(0x73, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelBlockRow2(long propVal)
{
  SetProperty(0x73, VT_I4, propVal);
}

short CWellSpreadSheet::GetSelectBlockOptions()
{
  short result;
  GetProperty(0x74, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelectBlockOptions(short propVal)
{
  SetProperty(0x74, VT_I2, propVal);
}

long CWellSpreadSheet::GetSelLength()
{
  long result;
  GetProperty(0x75, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelLength(long propVal)
{
  SetProperty(0x75, VT_I4, propVal);
}

long CWellSpreadSheet::GetSelModeIndex()
{
  long result;
  GetProperty(0x76, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelModeIndex(long propVal)
{
  SetProperty(0x76, VT_I4, propVal);
}

long CWellSpreadSheet::GetSelModeSelCount()
{
  long result;
  GetProperty(0x77, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelModeSelCount(long propVal)
{
  SetProperty(0x77, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetSelModeSelected()
{
  BOOL result;
  GetProperty(0x78, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelModeSelected(BOOL propVal)
{
  SetProperty(0x78, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetSelStart()
{
  long result;
  GetProperty(0x79, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelStart(long propVal)
{
  SetProperty(0x79, VT_I4, propVal);
}

CString CWellSpreadSheet::GetSelText()
{
  CString result;
  GetProperty(0x7a, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSelText(LPCTSTR propVal)
{
  SetProperty(0x7a, VT_BSTR, propVal);
}

unsigned long CWellSpreadSheet::GetShadowColor()
{
  unsigned long result;
  GetProperty(0x7b, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetShadowColor(unsigned long propVal)
{
  SetProperty(0x7b, VT_I4, propVal);
}

unsigned long CWellSpreadSheet::GetShadowDark()
{
  unsigned long result;
  GetProperty(0x7c, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetShadowDark(unsigned long propVal)
{
  SetProperty(0x7c, VT_I4, propVal);
}

unsigned long CWellSpreadSheet::GetShadowText()
{
  unsigned long result;
  GetProperty(0x7d, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetShadowText(unsigned long propVal)
{
  SetProperty(0x7d, VT_I4, propVal);
}

short CWellSpreadSheet::GetSortBy()
{
  short result;
  GetProperty(0x7e, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetSortBy(short propVal)
{
  SetProperty(0x7e, VT_I2, propVal);
}

long CWellSpreadSheet::GetStartingColNumber()
{
  long result;
  GetProperty(0x7f, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetStartingColNumber(long propVal)
{
  SetProperty(0x7f, VT_I4, propVal);
}

long CWellSpreadSheet::GetStartingRowNumber()
{
  long result;
  GetProperty(0x80, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetStartingRowNumber(long propVal)
{
  SetProperty(0x80, VT_I4, propVal);
}

long CWellSpreadSheet::GetTopRow()
{
  long result;
  GetProperty(0x81, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTopRow(long propVal)
{
  SetProperty(0x81, VT_I4, propVal);
}

short CWellSpreadSheet::GetTypeButtonAlign()
{
  short result;
  GetProperty(0x82, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonAlign(short propVal)
{
  SetProperty(0x82, VT_I2, propVal);
}

unsigned long CWellSpreadSheet::GetTypeButtonBorderColor()
{
  unsigned long result;
  GetProperty(0x83, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonBorderColor(unsigned long propVal)
{
  SetProperty(0x83, VT_I4, propVal);
}

unsigned long CWellSpreadSheet::GetTypeButtonColor()
{
  unsigned long result;
  GetProperty(0x84, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonColor(unsigned long propVal)
{
  SetProperty(0x84, VT_I4, propVal);
}

unsigned long CWellSpreadSheet::GetTypeButtonDarkColor()
{
  unsigned long result;
  GetProperty(0x85, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonDarkColor(unsigned long propVal)
{
  SetProperty(0x85, VT_I4, propVal);
}

unsigned long CWellSpreadSheet::GetTypeButtonLightColor()
{
  unsigned long result;
  GetProperty(0x86, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonLightColor(unsigned long propVal)
{
  SetProperty(0x86, VT_I4, propVal);
}

CPicture CWellSpreadSheet::GetTypeButtonPicture()
{
  LPDISPATCH pDispatch;
  GetProperty(0x87, VT_DISPATCH, (void*)&pDispatch);
  return CPicture(pDispatch);
}

void CWellSpreadSheet::SetTypeButtonPicture(LPDISPATCH propVal)
{
  SetProperty(0x87, VT_DISPATCH, propVal);
}

CPicture CWellSpreadSheet::GetTypeButtonPictureDown()
{
  LPDISPATCH pDispatch;
  GetProperty(0x88, VT_DISPATCH, (void*)&pDispatch);
  return CPicture(pDispatch);
}

void CWellSpreadSheet::SetTypeButtonPictureDown(LPDISPATCH propVal)
{
  SetProperty(0x88, VT_DISPATCH, propVal);
}

short CWellSpreadSheet::GetTypeButtonShadowSize()
{
  short result;
  GetProperty(0x89, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonShadowSize(short propVal)
{
  SetProperty(0x89, VT_I2, propVal);
}

CString CWellSpreadSheet::GetTypeButtonText()
{
  CString result;
  GetProperty(0x8a, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonText(LPCTSTR propVal)
{
  SetProperty(0x8a, VT_BSTR, propVal);
}

unsigned long CWellSpreadSheet::GetTypeButtonTextColor()
{
  unsigned long result;
  GetProperty(0x8b, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonTextColor(unsigned long propVal)
{
  SetProperty(0x8b, VT_I4, propVal);
}

short CWellSpreadSheet::GetTypeButtonType()
{
  short result;
  GetProperty(0x8c, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeButtonType(short propVal)
{
  SetProperty(0x8c, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetTypeCheckCenter()
{
  BOOL result;
  GetProperty(0x8d, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeCheckCenter(BOOL propVal)
{
  SetProperty(0x8d, VT_BOOL, propVal);
}

CString CWellSpreadSheet::GetTypeCheckText()
{
  CString result;
  GetProperty(0x8e, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeCheckText(LPCTSTR propVal)
{
  SetProperty(0x8e, VT_BSTR, propVal);
}

short CWellSpreadSheet::GetTypeCheckTextAlign()
{
  short result;
  GetProperty(0x8f, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeCheckTextAlign(short propVal)
{
  SetProperty(0x8f, VT_I2, propVal);
}

short CWellSpreadSheet::GetTypeComboBoxCount()
{
  short result;
  GetProperty(0x90, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeComboBoxCount(short propVal)
{
  SetProperty(0x90, VT_I2, propVal);
}

short CWellSpreadSheet::GetTypeComboBoxCurSel()
{
  short result;
  GetProperty(0x91, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeComboBoxCurSel(short propVal)
{
  SetProperty(0x91, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetTypeComboBoxEditable()
{
  BOOL result;
  GetProperty(0x92, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeComboBoxEditable(BOOL propVal)
{
  SetProperty(0x92, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetTypeComboBoxIndex()
{
  short result;
  GetProperty(0x93, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeComboBoxIndex(short propVal)
{
  SetProperty(0x93, VT_I2, propVal);
}

CString CWellSpreadSheet::GetTypeComboBoxList()
{
  CString result;
  GetProperty(0x94, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeComboBoxList(LPCTSTR propVal)
{
  SetProperty(0x94, VT_BSTR, propVal);
}

CString CWellSpreadSheet::GetTypeComboBoxString()
{
  CString result;
  GetProperty(0x95, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeComboBoxString(LPCTSTR propVal)
{
  SetProperty(0x95, VT_BSTR, propVal);
}

BOOL CWellSpreadSheet::GetTypeDateCentury()
{
  BOOL result;
  GetProperty(0x96, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeDateCentury(BOOL propVal)
{
  SetProperty(0x96, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetTypeDateFormat()
{
  short result;
  GetProperty(0x97, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeDateFormat(short propVal)
{
  SetProperty(0x97, VT_I2, propVal);
}

CString CWellSpreadSheet::GetTypeDateMax()
{
  CString result;
  GetProperty(0x98, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeDateMax(LPCTSTR propVal)
{
  SetProperty(0x98, VT_BSTR, propVal);
}

CString CWellSpreadSheet::GetTypeDateMin()
{
  CString result;
  GetProperty(0x99, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeDateMin(LPCTSTR propVal)
{
  SetProperty(0x99, VT_BSTR, propVal);
}

short CWellSpreadSheet::GetTypeDateSeparator()
{
  short result;
  GetProperty(0x9a, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeDateSeparator(short propVal)
{
  SetProperty(0x9a, VT_I2, propVal);
}

short CWellSpreadSheet::GetTypeEditCharCase()
{
  short result;
  GetProperty(0x9b, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeEditCharCase(short propVal)
{
  SetProperty(0x9b, VT_I2, propVal);
}

short CWellSpreadSheet::GetTypeEditCharSet()
{
  short result;
  GetProperty(0x9c, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeEditCharSet(short propVal)
{
  SetProperty(0x9c, VT_I2, propVal);
}

long CWellSpreadSheet::GetTypeEditLen()
{
  long result;
  GetProperty(0x9d, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeEditLen(long propVal)
{
  SetProperty(0x9d, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetTypeEditMultiLine()
{
  BOOL result;
  GetProperty(0x9e, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeEditMultiLine(BOOL propVal)
{
  SetProperty(0x9e, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetTypeEditPassword()
{
  BOOL result;
  GetProperty(0x9f, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeEditPassword(BOOL propVal)
{
  SetProperty(0x9f, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetTypeFloatCurrencyChar()
{
  short result;
  GetProperty(0xa0, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeFloatCurrencyChar(short propVal)
{
  SetProperty(0xa0, VT_I2, propVal);
}

short CWellSpreadSheet::GetTypeFloatDecimalChar()
{
  short result;
  GetProperty(0xa1, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeFloatDecimalChar(short propVal)
{
  SetProperty(0xa1, VT_I2, propVal);
}

short CWellSpreadSheet::GetTypeFloatDecimalPlaces()
{
  short result;
  GetProperty(0xa2, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeFloatDecimalPlaces(short propVal)
{
  SetProperty(0xa2, VT_I2, propVal);
}

double CWellSpreadSheet::GetTypeFloatMax()
{
  double result;
  GetProperty(0xa3, VT_R8, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeFloatMax(double propVal)
{
  SetProperty(0xa3, VT_R8, propVal);
}

double CWellSpreadSheet::GetTypeFloatMin()
{
  double result;
  GetProperty(0xa4, VT_R8, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeFloatMin(double propVal)
{
  SetProperty(0xa4, VT_R8, propVal);
}

BOOL CWellSpreadSheet::GetTypeFloatMoney()
{
  BOOL result;
  GetProperty(0xa5, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeFloatMoney(BOOL propVal)
{
  SetProperty(0xa5, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetTypeFloatSeparator()
{
  BOOL result;
  GetProperty(0xa6, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeFloatSeparator(BOOL propVal)
{
  SetProperty(0xa6, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetTypeFloatSepChar()
{
  short result;
  GetProperty(0xa7, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeFloatSepChar(short propVal)
{
  SetProperty(0xa7, VT_I2, propVal);
}

short CWellSpreadSheet::GetTypeHAlign()
{
  short result;
  GetProperty(0xa8, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeHAlign(short propVal)
{
  SetProperty(0xa8, VT_I2, propVal);
}

long CWellSpreadSheet::GetTypeIntegerMax()
{
  long result;
  GetProperty(0xa9, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeIntegerMax(long propVal)
{
  SetProperty(0xa9, VT_I4, propVal);
}

long CWellSpreadSheet::GetTypeIntegerMin()
{
  long result;
  GetProperty(0xaa, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeIntegerMin(long propVal)
{
  SetProperty(0xaa, VT_I4, propVal);
}

long CWellSpreadSheet::GetTypeIntegerSpinInc()
{
  long result;
  GetProperty(0xab, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeIntegerSpinInc(long propVal)
{
  SetProperty(0xab, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetTypeIntegerSpinWrap()
{
  BOOL result;
  GetProperty(0xac, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeIntegerSpinWrap(BOOL propVal)
{
  SetProperty(0xac, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetTypeOwnerDrawStyle()
{
  long result;
  GetProperty(0xad, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeOwnerDrawStyle(long propVal)
{
  SetProperty(0xad, VT_I4, propVal);
}

CString CWellSpreadSheet::GetTypePicDefaultText()
{
  CString result;
  GetProperty(0xae, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypePicDefaultText(LPCTSTR propVal)
{
  SetProperty(0xae, VT_BSTR, propVal);
}

CString CWellSpreadSheet::GetTypePicMask()
{
  CString result;
  GetProperty(0xaf, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypePicMask(LPCTSTR propVal)
{
  SetProperty(0xaf, VT_BSTR, propVal);
}

BOOL CWellSpreadSheet::GetTypePictCenter()
{
  BOOL result;
  GetProperty(0xb0, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypePictCenter(BOOL propVal)
{
  SetProperty(0xb0, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetTypePictMaintainScale()
{
  BOOL result;
  GetProperty(0xb1, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypePictMaintainScale(BOOL propVal)
{
  SetProperty(0xb1, VT_BOOL, propVal);
}

CPicture CWellSpreadSheet::GetTypePictPicture()
{
  LPDISPATCH pDispatch;
  GetProperty(0xb2, VT_DISPATCH, (void*)&pDispatch);
  return CPicture(pDispatch);
}

void CWellSpreadSheet::SetTypePictPicture(LPDISPATCH propVal)
{
  SetProperty(0xb2, VT_DISPATCH, propVal);
}

BOOL CWellSpreadSheet::GetTypePictStretch()
{
  BOOL result;
  GetProperty(0xb3, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypePictStretch(BOOL propVal)
{
  SetProperty(0xb3, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetTypeSpin()
{
  BOOL result;
  GetProperty(0xb4, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeSpin(BOOL propVal)
{
  SetProperty(0xb4, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetTypeTextAlignVert()
{
  short result;
  GetProperty(0xb5, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTextAlignVert(short propVal)
{
  SetProperty(0xb5, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetTypeTextPrefix()
{
  BOOL result;
  GetProperty(0xb6, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTextPrefix(BOOL propVal)
{
  SetProperty(0xb6, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetTypeTextShadow()
{
  BOOL result;
  GetProperty(0xb7, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTextShadow(BOOL propVal)
{
  SetProperty(0xb7, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetTypeTextShadowIn()
{
  BOOL result;
  GetProperty(0xb8, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTextShadowIn(BOOL propVal)
{
  SetProperty(0xb8, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetTypeTextWordWrap()
{
  BOOL result;
  GetProperty(0xb9, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTextWordWrap(BOOL propVal)
{
  SetProperty(0xb9, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetTypeTime24Hour()
{
  short result;
  GetProperty(0xba, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTime24Hour(short propVal)
{
  SetProperty(0xba, VT_I2, propVal);
}

CString CWellSpreadSheet::GetTypeTimeMax()
{
  CString result;
  GetProperty(0xbb, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTimeMax(LPCTSTR propVal)
{
  SetProperty(0xbb, VT_BSTR, propVal);
}

CString CWellSpreadSheet::GetTypeTimeMin()
{
  CString result;
  GetProperty(0xbc, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTimeMin(LPCTSTR propVal)
{
  SetProperty(0xbc, VT_BSTR, propVal);
}

BOOL CWellSpreadSheet::GetTypeTimeSeconds()
{
  BOOL result;
  GetProperty(0xbd, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTimeSeconds(BOOL propVal)
{
  SetProperty(0xbd, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetTypeTimeSeparator()
{
  short result;
  GetProperty(0xbe, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeTimeSeparator(short propVal)
{
  SetProperty(0xbe, VT_I2, propVal);
}

long CWellSpreadSheet::GetUnitType()
{
  long result;
  GetProperty(0xbf, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetUnitType(long propVal)
{
  SetProperty(0xbf, VT_I4, propVal);
}

short CWellSpreadSheet::GetUserResize()
{
  short result;
  GetProperty(0xc0, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetUserResize(short propVal)
{
  SetProperty(0xc0, VT_I2, propVal);
}

short CWellSpreadSheet::GetUserResizeCol()
{
  short result;
  GetProperty(0xc1, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetUserResizeCol(short propVal)
{
  SetProperty(0xc1, VT_I2, propVal);
}

short CWellSpreadSheet::GetUserResizeRow()
{
  short result;
  GetProperty(0xc2, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetUserResizeRow(short propVal)
{
  SetProperty(0xc2, VT_I2, propVal);
}

CString CWellSpreadSheet::GetValue()
{
  CString result;
  GetProperty(0xc3, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetValue(LPCTSTR propVal)
{
  SetProperty(0xc3, VT_BSTR, propVal);
}

long CWellSpreadSheet::GetVirtualCurRowCount()
{
  long result;
  GetProperty(0xc4, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVirtualCurRowCount(long propVal)
{
  SetProperty(0xc4, VT_I4, propVal);
}

long CWellSpreadSheet::GetVirtualCurTop()
{
  long result;
  GetProperty(0xc5, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVirtualCurTop(long propVal)
{
  SetProperty(0xc5, VT_I4, propVal);
}

long CWellSpreadSheet::GetVirtualMaxRows()
{
  long result;
  GetProperty(0xc6, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVirtualMaxRows(long propVal)
{
  SetProperty(0xc6, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetVirtualMode()
{
  BOOL result;
  GetProperty(0xc7, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVirtualMode(BOOL propVal)
{
  SetProperty(0xc7, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetVirtualOverlap()
{
  long result;
  GetProperty(0xc8, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVirtualOverlap(long propVal)
{
  SetProperty(0xc8, VT_I4, propVal);
}

long CWellSpreadSheet::GetVirtualRows()
{
  long result;
  GetProperty(0xc9, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVirtualRows(long propVal)
{
  SetProperty(0xc9, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetVirtualScrollBuffer()
{
  BOOL result;
  GetProperty(0xca, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVirtualScrollBuffer(BOOL propVal)
{
  SetProperty(0xca, VT_BOOL, propVal);
}

long CWellSpreadSheet::GetVisibleCols()
{
  long result;
  GetProperty(0xcb, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVisibleCols(long propVal)
{
  SetProperty(0xcb, VT_I4, propVal);
}

long CWellSpreadSheet::GetVisibleRows()
{
  long result;
  GetProperty(0xcc, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVisibleRows(long propVal)
{
  SetProperty(0xcc, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetVScrollSpecial()
{
  BOOL result;
  GetProperty(0xcd, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVScrollSpecial(BOOL propVal)
{
  SetProperty(0xcd, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetVScrollSpecialType()
{
  short result;
  GetProperty(0xce, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetVScrollSpecialType(short propVal)
{
  SetProperty(0xce, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetFontBold()
{
  BOOL result;
  GetProperty(0xcf, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFontBold(BOOL propVal)
{
  SetProperty(0xcf, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetFontItalic()
{
  BOOL result;
  GetProperty(0xd0, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFontItalic(BOOL propVal)
{
  SetProperty(0xd0, VT_BOOL, propVal);
}

CString CWellSpreadSheet::GetFontName()
{
  CString result;
  GetProperty(0xd1, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFontName(LPCTSTR propVal)
{
  SetProperty(0xd1, VT_BSTR, propVal);
}

float CWellSpreadSheet::GetFontSize()
{
  float result;
  GetProperty(0xd2, VT_R4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFontSize(float propVal)
{
  SetProperty(0xd2, VT_R4, propVal);
}

BOOL CWellSpreadSheet::GetFontStrikethru()
{
  BOOL result;
  GetProperty(0xd3, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFontStrikethru(BOOL propVal)
{
  SetProperty(0xd3, VT_BOOL, propVal);
}

BOOL CWellSpreadSheet::GetFontUnderline()
{
  BOOL result;
  GetProperty(0xd4, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFontUnderline(BOOL propVal)
{
  SetProperty(0xd4, VT_BOOL, propVal);
}

CPicture CWellSpreadSheet::GetCursorIcon()
{
  LPDISPATCH pDispatch;
  GetProperty(0xd5, VT_DISPATCH, (void*)&pDispatch);
  return CPicture(pDispatch);
}

void CWellSpreadSheet::SetCursorIcon(LPDISPATCH propVal)
{
  SetProperty(0xd5, VT_DISPATCH, propVal);
}

short CWellSpreadSheet::GetPrintOrientation()
{
  short result;
  GetProperty(0xd6, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetPrintOrientation(short propVal)
{
  SetProperty(0xd6, VT_I2, propVal);
}

long CWellSpreadSheet::GetBackColorStyle()
{
  long result;
  GetProperty(0xd7, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetBackColorStyle(long propVal)
{
  SetProperty(0xd7, VT_I4, propVal);
}

BOOL CWellSpreadSheet::GetFormulaSync()
{
  BOOL result;
  GetProperty(0xd8, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetFormulaSync(BOOL propVal)
{
  SetProperty(0xd8, VT_BOOL, propVal);
}

short CWellSpreadSheet::GetTypeCheckType()
{
  short result;
  GetProperty(0x110, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetTypeCheckType(short propVal)
{
  SetProperty(0x110, VT_I2, propVal);
}

OLE_COLOR CWellSpreadSheet::GetBackColor()
{
  OLE_COLOR result;
  GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetBackColor(OLE_COLOR propVal)
{
  SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

short CWellSpreadSheet::GetBorderStyle()
{
  short result;
  GetProperty(DISPID_BORDERSTYLE, VT_I2, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetBorderStyle(short propVal)
{
  SetProperty(DISPID_BORDERSTYLE, VT_I2, propVal);
}

BOOL CWellSpreadSheet::GetEnabled()
{
  BOOL result;
  GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetEnabled(BOOL propVal)
{
  SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

COleFont CWellSpreadSheet::GetFont()
{
  LPDISPATCH pDispatch;
  GetProperty(DISPID_FONT, VT_DISPATCH, (void*)&pDispatch);
  return COleFont(pDispatch);
}

void CWellSpreadSheet::SetFont(LPDISPATCH propVal)
{
  SetProperty(DISPID_FONT, VT_DISPATCH, propVal);
}

OLE_COLOR CWellSpreadSheet::GetForeColor()
{
  OLE_COLOR result;
  GetProperty(DISPID_FORECOLOR, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetForeColor(OLE_COLOR propVal)
{
  SetProperty(DISPID_FORECOLOR, VT_I4, propVal);
}

OLE_HANDLE CWellSpreadSheet::GetHWnd()
{
  OLE_HANDLE result;
  GetProperty(DISPID_HWND, VT_I4, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetHWnd(OLE_HANDLE propVal)
{
  SetProperty(DISPID_HWND, VT_I4, propVal);
}

CString CWellSpreadSheet::GetText()
{
  CString result;
  GetProperty(DISPID_TEXT, VT_BSTR, (void*)&result);
  return result;
}

void CWellSpreadSheet::SetText(LPCTSTR propVal)
{
  SetProperty(DISPID_TEXT, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CWellSpreadSheet operations

double CWellSpreadSheet::GetColWidth(long lCol)
{
  double result;
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0xd9, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms,
    lCol);
  return result;
}

void CWellSpreadSheet::SetColWidth(long lCol, double newValue)
{
  static BYTE parms[] =
    VTS_I4 VTS_R8;
  InvokeHelper(0xd9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
     lCol, newValue);
}

double CWellSpreadSheet::GetMaxTextColWidth(long lCol)
{
  double result;
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0xda, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms,
    lCol);
  return result;
}

void CWellSpreadSheet::SetMaxTextColWidth(long lCol, double newValue)
{
  static BYTE parms[] =
    VTS_I4 VTS_R8;
  InvokeHelper(0xda, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
     lCol, newValue);
}

double CWellSpreadSheet::GetMaxTextRowHeight(long lRow)
{
  double result;
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0xdb, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms,
    lRow);
  return result;
}

void CWellSpreadSheet::SetMaxTextRowHeight(long lRow, double newValue)
{
  static BYTE parms[] =
    VTS_I4 VTS_R8;
  InvokeHelper(0xdb, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
     lRow, newValue);
}

double CWellSpreadSheet::GetRowHeight(long lRow)
{
  double result;
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0xdc, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms,
    lRow);
  return result;
}

void CWellSpreadSheet::SetRowHeight(long lRow, double newValue)
{
  static BYTE parms[] =
    VTS_I4 VTS_R8;
  InvokeHelper(0xdc, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
     lRow, newValue);
}

long CWellSpreadSheet::GetSortKey(short nIndex)
{
  long result;
  static BYTE parms[] =
    VTS_I2;
  InvokeHelper(0xdd, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
    nIndex);
  return result;
}

void CWellSpreadSheet::SetSortKey(short nIndex, long nNewValue)
{
  static BYTE parms[] =
    VTS_I2 VTS_I4;
  InvokeHelper(0xdd, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
     nIndex, nNewValue);
}

short CWellSpreadSheet::GetSortKeyOrder(short nIndex)
{
  short result;
  static BYTE parms[] =
    VTS_I2;
  InvokeHelper(0xde, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
    nIndex);
  return result;
}

void CWellSpreadSheet::SetSortKeyOrder(short nIndex, short nNewValue)
{
  static BYTE parms[] =
    VTS_I2 VTS_I2;
  InvokeHelper(0xde, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
     nIndex, nNewValue);
}

CPicture CWellSpreadSheet::GetTypeCheckPicture(short Index)
{
  LPDISPATCH pDispatch;
  static BYTE parms[] =
    VTS_I2;
  InvokeHelper(0xdf, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
    Index);
  return CPicture(pDispatch);
}

void CWellSpreadSheet::SetTypeCheckPicture(short Index, LPDISPATCH newValue)
{
  static BYTE parms[] =
    VTS_I2 VTS_DISPATCH;
  InvokeHelper(0xdf, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
     Index, newValue);
}

BOOL CWellSpreadSheet::AddCustomFunction(LPCTSTR FunctionName, short ParameterCnt)
{
  BOOL result;
  static BYTE parms[] =
    VTS_BSTR VTS_I2;
  InvokeHelper(0xe0, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    FunctionName, ParameterCnt);
  return result;
}

BOOL CWellSpreadSheet::AddCustomFunctionExt(LPCTSTR FunctionName, short MinParamCnt, short MaxParamCnt, long Flags)
{
  BOOL result;
  static BYTE parms[] =
    VTS_BSTR VTS_I2 VTS_I2 VTS_I4;
  InvokeHelper(0xe1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    FunctionName, MinParamCnt, MaxParamCnt, Flags);
  return result;
}

void CWellSpreadSheet::CFGetCellParam(short Param, long* Col, long* Row)
{
  static BYTE parms[] =
    VTS_I2 VTS_PI4 VTS_PI4;
  InvokeHelper(0xe2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Param, Col, Row);
}

double CWellSpreadSheet::CFGetDoubleParam(short Param)
{
  double result;
  static BYTE parms[] =
    VTS_I2;
  InvokeHelper(0xe3, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
    Param);
  return result;
}

double CWellSpreadSheet::CFGetDoubleParamExt(short Param, double* ParamValue)
{
  double result;
  static BYTE parms[] =
    VTS_I2 VTS_PR8;
  InvokeHelper(0xe4, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
    Param, ParamValue);
  return result;
}

long CWellSpreadSheet::CFGetLongParam(short Param)
{
  long result;
  static BYTE parms[] =
    VTS_I2;
  InvokeHelper(0xe5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
    Param);
  return result;
}

BOOL CWellSpreadSheet::CFGetParamInfo(short Param, short* Type, short* Status)
{
  BOOL result;
  static BYTE parms[] =
    VTS_I2 VTS_PI2 VTS_PI2;
  InvokeHelper(0xe6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Param, Type, Status);
  return result;
}

void CWellSpreadSheet::CFGetRangeParam(short Param, long* Col, long* Row, long* Col2, long* Row2)
{
  static BYTE parms[] =
    VTS_I2 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
  InvokeHelper(0xe7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Param, Col, Row, Col2, Row2);
}

CString CWellSpreadSheet::CFGetStringParam(short Param)
{
  CString result;
  static BYTE parms[] =
    VTS_I2;
  InvokeHelper(0xe8, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
    Param);
  return result;
}

void CWellSpreadSheet::CFSetResult(const VARIANT& Var)
{
  static BYTE parms[] =
    VTS_VARIANT;
  InvokeHelper(0xe9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     &Var);
}

CString CWellSpreadSheet::ColNumberToLetter(long HeaderNumber)
{
  CString result;
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0xea, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
    HeaderNumber);
  return result;
}

void CWellSpreadSheet::ColWidthToTwips(float Width, long* Twips)
{
  static BYTE parms[] =
    VTS_R4 VTS_PI4;
  InvokeHelper(0xeb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Width, Twips);
}

void CWellSpreadSheet::GetBottomRightCell(long* Col, long* Row)
{
  static BYTE parms[] =
    VTS_PI4 VTS_PI4;
  InvokeHelper(0xec, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Col, Row);
}

BOOL CWellSpreadSheet::GetCellDirtyFlag(long Col, long Row)
{
  BOOL result;
  static BYTE parms[] =
    VTS_I4 VTS_I4;
  InvokeHelper(0xed, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Col, Row);
  return result;
}

void CWellSpreadSheet::GetCellFromScreenCoord(long* Col, long* Row, long x, long y)
{
  static BYTE parms[] =
    VTS_PI4 VTS_PI4 VTS_I4 VTS_I4;
  InvokeHelper(0xee, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Col, Row, x, y);
}

BOOL CWellSpreadSheet::GetCellPos(long Col, long Row, long* x, long* y, long* Width, long* Height)
{
  BOOL result;
  static BYTE parms[] =
    VTS_I4 VTS_I4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
  InvokeHelper(0xef, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Col, Row, x, y, Width, Height);
  return result;
}

void CWellSpreadSheet::GetClientArea(long* Width, long* Height)
{
  static BYTE parms[] =
    VTS_PI4 VTS_PI4;
  InvokeHelper(0xf0, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Width, Height);
}

long CWellSpreadSheet::GetColItemData(long Col)
{
  long result;
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0xf1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
    Col);
  return result;
}

CString CWellSpreadSheet::QueryCustomName(LPCTSTR Name)
{
  CString result;
  static BYTE parms[] =
    VTS_BSTR;
  InvokeHelper(0xf2, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
    Name);
  return result;
}

CString CWellSpreadSheet::GetCustomName(LPCTSTR Name)
{
  CString result;
  static BYTE parms[] =
    VTS_BSTR;
  InvokeHelper(0xf3, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
    Name);
  return result;
}

BOOL CWellSpreadSheet::GetDataFillData(VARIANT* Var, short VarType)
{
  BOOL result;
  static BYTE parms[] =
    VTS_PVARIANT VTS_I2;
  InvokeHelper(0xf4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Var, VarType);
  return result;
}

void CWellSpreadSheet::GetFirstValidCell(long* Col, long* Row)
{
  static BYTE parms[] =
    VTS_PI4 VTS_PI4;
  InvokeHelper(0xf5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Col, Row);
}

long CWellSpreadSheet::GetItemData()
{
  long result;
  InvokeHelper(0xf6, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
  return result;
}

BOOL CWellSpreadSheet::GetIteration(short* MaxIterations, double* MaxChange)
{
  BOOL result;
  static BYTE parms[] =
    VTS_PI2 VTS_PR8;
  InvokeHelper(0xf7, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    MaxIterations, MaxChange);
  return result;
}

void CWellSpreadSheet::GetLastValidCell(long* Col, long* Row)
{
  static BYTE parms[] =
    VTS_PI4 VTS_PI4;
  InvokeHelper(0xf8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Col, Row);
}

long CWellSpreadSheet::GetMultiSelItem(long SelPrev)
{
  long result;
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0xf9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
    SelPrev);
  return result;
}

short CWellSpreadSheet::GetRefStyle()
{
  short result;
  InvokeHelper(0xfa, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
  return result;
}

long CWellSpreadSheet::GetRowItemData(long Row)
{
  long result;
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0xfb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
    Row);
  return result;
}

BOOL CWellSpreadSheet::GetText(long Col, long Row, VARIANT* Var)
{
  BOOL result;
  static BYTE parms[] =
    VTS_I4 VTS_I4 VTS_PVARIANT;
  InvokeHelper(0xfc, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Col, Row, Var);
  return result;
}

BOOL CWellSpreadSheet::IsCellSelected(long Col, long Row)
{
  BOOL result;
  static BYTE parms[] =
    VTS_I4 VTS_I4;
  InvokeHelper(0xfd, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Col, Row);
  return result;
}

BOOL CWellSpreadSheet::IsFormulaValid(LPCTSTR Formula)
{
  BOOL result;
  static BYTE parms[] =
    VTS_BSTR;
  InvokeHelper(0xfe, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Formula);
  return result;
}

BOOL CWellSpreadSheet::IsVisible(long Col, long Row, BOOL Partial)
{
  BOOL result;
  static BYTE parms[] =
    VTS_I4 VTS_I4 VTS_BOOL;
  InvokeHelper(0xff, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Col, Row, Partial);
  return result;
}

BOOL CWellSpreadSheet::LoadFromFile(LPCTSTR FileName)
{
  BOOL result;
  static BYTE parms[] =
    VTS_BSTR;
  InvokeHelper(0x100, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    FileName);
  return result;
}

BOOL CWellSpreadSheet::LoadTabFile(LPCTSTR FileName)
{
  BOOL result;
  static BYTE parms[] =
    VTS_BSTR;
  InvokeHelper(0x101, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    FileName);
  return result;
}

void CWellSpreadSheet::RowHeightToTwips(long Row, float Height, long* Twips)
{
  static BYTE parms[] =
    VTS_I4 VTS_R4 VTS_PI4;
  InvokeHelper(0x102, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Row, Height, Twips);
}

BOOL CWellSpreadSheet::SaveTabFile(LPCTSTR FileName)
{
  BOOL result;
  static BYTE parms[] =
    VTS_BSTR;
  InvokeHelper(0x103, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    FileName);
  return result;
}

BOOL CWellSpreadSheet::SaveToFile(LPCTSTR FileName, BOOL DataOnly)
{
  BOOL result;
  static BYTE parms[] =
    VTS_BSTR VTS_BOOL;
  InvokeHelper(0x104, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    FileName, DataOnly);
  return result;
}

BOOL CWellSpreadSheet::SetCellDirtyFlag(long Col, long Row, BOOL Dirty)
{
  BOOL result;
  static BYTE parms[] =
    VTS_I4 VTS_I4 VTS_BOOL;
  InvokeHelper(0x105, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Col, Row, Dirty);
  return result;
}

void CWellSpreadSheet::SetColItemData(long Col, long Value)
{
  static BYTE parms[] =
    VTS_I4 VTS_I4;
  InvokeHelper(0x106, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Col, Value);
}

BOOL CWellSpreadSheet::SetCustomName(LPCTSTR Name, LPCTSTR Value)
{
  BOOL result;
  static BYTE parms[] =
    VTS_BSTR VTS_BSTR;
  InvokeHelper(0x107, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    Name, Value);
  return result;
}

BOOL CWellSpreadSheet::SetDataFillData(const VARIANT& Var)
{
  BOOL result;
  static BYTE parms[] =
    VTS_VARIANT;
  InvokeHelper(0x108, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
    &Var);
  return result;
}

void CWellSpreadSheet::SetItemData(long Value)
{
  static BYTE parms[] =
    VTS_I4;
  InvokeHelper(0x109, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Value);
}

void CWellSpreadSheet::SetIteration(BOOL Iteration, short MaxIterations, double MaxChange)
{
  static BYTE parms[] =
    VTS_BOOL VTS_I2 VTS_R8;
  InvokeHelper(0x10a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Iteration, MaxIterations, MaxChange);
}

void CWellSpreadSheet::SetRefStyle(short RefStyle)
{
  static BYTE parms[] =
    VTS_I2;
  InvokeHelper(0x10b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     RefStyle);
}

void CWellSpreadSheet::SetRowItemData(long Row, long Value)
{
  static BYTE parms[] =
    VTS_I4 VTS_I4;
  InvokeHelper(0x10c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Row, Value);
}

void CWellSpreadSheet::SetText(long Col, long Row, const VARIANT& Var)
{
  static BYTE parms[] =
    VTS_I4 VTS_I4 VTS_VARIANT;
  InvokeHelper(0x10d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Col, Row, &Var);
}

void CWellSpreadSheet::TwipsToColWidth(long Twips, float* ColWidth)
{
  static BYTE parms[] =
    VTS_I4 VTS_PR4;
  InvokeHelper(0x10e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Twips, ColWidth);
}

void CWellSpreadSheet::TwipsToRowHeight(long Row, long Twips, float* RowHeight)
{
  static BYTE parms[] =
    VTS_I4 VTS_I4 VTS_PR4;
  InvokeHelper(0x10f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
     Row, Twips, RowHeight);
}

void CWellSpreadSheet::Refresh()
{
  InvokeHelper(DISPID_REFRESH, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CWellSpreadSheet::AboutBox()
{
  InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
