
#include <cassert>
#include <qobject.h>
#include <map>

#include "GeomecStringTable.h"
#include "resource.h"
#include "sharedResource.h"
#include "resourceIDS.h"
#include "resourceIDP.h"

CValueTypeIdContainer *CValueTypeIdContainer::obj= 0; //singleton

namespace
{

// this doesn't fix our problem with extended characters (namely that we may end up with garbage)
// but it does show the intended character in the garbage
//#pragma execution_character_set("utf-8")

typedef std::map <int, const char *> GeomecStringTable;

const GeomecStringTable::value_type rawData[] = {
  GeomecStringTable::value_type(0 /* is a special case! */         ,             ""),
  /* 1 - 87 */
  GeomecStringTable::value_type(IDS_ET_YOUNGMODULUS_TRANS          , "YoungModulusTrans"),
  GeomecStringTable::value_type(IDS_ET_POISSONRATIO_NORM           , "PoissonRatioNorm"),
  /* ID_CLOSE */
  GeomecStringTable::value_type(IDS_ET_POISSONRATIO_TRANS          , "PoissonRatioTrans"),
  GeomecStringTable::value_type(IDS_ET_LAYER_NORMAL_INCL           , "LayerNormalIncl"),
  GeomecStringTable::value_type(IDS_ET_LAYER_NORMAL_AZI            , "LayerNormalAzi"),
  GeomecStringTable::value_type(IDS_ET_FRACT_STIFF_NORMAL          , "FractStiffNormal"),
  GeomecStringTable::value_type(IDS_ET_FRACT_STIFF_SHEAR           , "FractStiffShear"),
  GeomecStringTable::value_type(IDS_ET_HIGH_FRACT_DENS             , "HighFractDens"),
  GeomecStringTable::value_type(IDS_ET_HIGH_FRACT_DENS_INCL        , "HighFractDensIncl"),
  GeomecStringTable::value_type(IDS_ET_HIGH_FRACT_DENS_AZI         , "HighFractDensAzi"),
  GeomecStringTable::value_type(IDS_ET_LOW_FRACT_DENS              , "LowFractDens"),
  GeomecStringTable::value_type(IDS_ET_LOW_FRACT_DENS_INCL         , "LowFractDensIncl"),
  GeomecStringTable::value_type(IDS_ET_LOW_FRACT_DENS_AZI          , "LowFractDensAzi"),
  GeomecStringTable::value_type(IDS_ET_INTER_FRACT_DENS            , "InterFractDens"),
  GeomecStringTable::value_type(IDS_ET_THERM_LIN_EXP_NORM          , "ThermLinExpNorm"),
  GeomecStringTable::value_type(IDS_ET_THERM_LIN_EXP_LAT           , "ThermLinExpLat"),
  GeomecStringTable::value_type(IDS_ET_THERM_CONDUCT               , "ThermConduct"),
  GeomecStringTable::value_type(IDS_ET_THERM_CAPACI                , "ThermCapac"),
  GeomecStringTable::value_type(IDS_VALUENAME_LAYER_NORMAL_AZI     , "Layer normal azimuth"),
  GeomecStringTable::value_type(IDS_VALUENAME_FRACT_STIFF_NORMAL   , "Fracture stiffness normal"),
  GeomecStringTable::value_type(IDS_VALUENAME_FRACT_STIFF_SHEAR    , "Fracture stiffness shear"),
  GeomecStringTable::value_type(IDS_VALUENAME_HIGH_FRACT_DENS      , "Highest Fracture Density"),
  GeomecStringTable::value_type(IDS_VALUENAME_HIGH_FRACT_DENS_INCL , "Highest Fracture Density inclination"),
  GeomecStringTable::value_type(IDS_VALUENAME_HIGH_FRACT_DENS_AZI  , "Highest Fracture Density azimuth"),
  GeomecStringTable::value_type(IDS_VALUENAME_LOW_FRACT_DENS       , "Lowest Fracture Density"),
  GeomecStringTable::value_type(IDS_VALUENAME_LOW_FRACT_DENS_INCL  , "Lowest Fracture Density inclination"),
  GeomecStringTable::value_type(IDS_VALUENAME_LOW_FRACT_DENS_AZI   , "Lowest Fracture Density azimuth"),
  GeomecStringTable::value_type(IDS_VALUENAME_INTER_FRACT_DENS     , "Intermediate Fracture Density"),
  GeomecStringTable::value_type(IDS_VALUENAME_THERM_LIN_EXP_NORM   , "Thermal Linear expansion normal"),
  GeomecStringTable::value_type(IDS_VALUENAME_THERM_LIN_EXP_LAT    , "Thermal Linear expansion lateral"),
  GeomecStringTable::value_type(IDS_VALUENAME_THERM_CONDUCT        , "Thermal Conductivity"),
  GeomecStringTable::value_type(IDS_VALUENAME_THERM_CAPACI         , "Thermal Capacity"),
  GeomecStringTable::value_type(IDS_VALUENAME_YOUNGMODULUS_NORM    , "Young's Modulus normal"),
  GeomecStringTable::value_type(IDS_VALUENAME_YOUNGMODULUS_TRANS   , "Young's Modulus transverse"),
  GeomecStringTable::value_type(IDS_VALUENAME_POISSONRATIO_NORM    , "Poisson's ratio normal"),
  GeomecStringTable::value_type(IDS_VALUENAME_POISSONRATIO_TRANS   , "Poisson's ratio transverse"),
  GeomecStringTable::value_type(IDS_VALUENAME_LAYER_NORMAL_INCL    , "Layer normal dip"),
  GeomecStringTable::value_type(IDS_UNIT_SI_THERM_CONDUCT          , "W/(m,K)"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_THERM_CONDUCT       , "W/(ft,K)"),
  GeomecStringTable::value_type(IDS_UNIT_SI_THERM_CAPACI           , "J/(kg,K)"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_THERM_CAPACI        , "J/(lb,K)"),
  GeomecStringTable::value_type(IDS_UNIT_SI_STRESSGRADIENT         , "MPa/m"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_STRESSGRADIENT      , "psi/ft"),
  GeomecStringTable::value_type(IDS_UNIT_SI_PERLENGTH              , "1/m"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_PERLENGTH           , "1/ft"),
  GeomecStringTable::value_type(IDS_VALUENAME_FRACT_TENSOR         , "Fracture Intensity"),
  GeomecStringTable::value_type(IDS_ET_FRACT_TENSOR                , "FractIntens"),
  GeomecStringTable::value_type(IDS_UNIT_SI_PERMEA                 , "mD"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_PERMEA              , "mD"),
  GeomecStringTable::value_type(IDS_ET_PERMEA                      , "Permeability"),
  GeomecStringTable::value_type(IDS_VALUENAME_PERMEA               , "Permeability"),
  GeomecStringTable::value_type(IDS_VALUENAME_POISSON_DECOMP       , "Poisson's Ratio in decompaction"),
  GeomecStringTable::value_type(IDS_VALUENAME_YOUNG_DECOMP         , "Young's Modulus in decompaction"),
  GeomecStringTable::value_type(IDS_ET_POISSON_DECOMP              , "PoissonRatioDecomp"),
  GeomecStringTable::value_type(IDS_ET_YOUNG_DECOMP                , "YoungsModulusDecomp"),
  GeomecStringTable::value_type(IDS_ET_VISCOSITY                   , "Viscosity"),
  GeomecStringTable::value_type(IDS_VALUENAME_VISCOSITY            , "Viscosity"),
  GeomecStringTable::value_type(IDS_UNIT_SI_VISCOSITY              , "cP"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_VISCOSITY           , "cP"),
  GeomecStringTable::value_type(IDS_UPSCALING                      , "Upscaling"),
  GeomecStringTable::value_type(IDP_ZOOMINNOBOUNDARYLOADS          , "Warning: Interface elements applied at model boundary. No boundary conditions assigned. Potential mistake.\n\nIs this what you want?"),
  GeomecStringTable::value_type(IDS_ET_VOLUMETRICSTRAIN            , "VolumetricStrain"),
  GeomecStringTable::value_type(IDS_VALUENAME_VOLUMETRICSTRAIN     , "Volumetric Strain"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_FLUIDX            , "FluidThermalExpansionCoeff"),
  GeomecStringTable::value_type(IDS_VALUENAME_FLUIDX               , "Fluid Thermal Expansion Coefficient"),
  
  GeomecStringTable::value_type(IDS_COMPONENT_VOLSTRAIN_GRADIENT   , "Single value"),
  GeomecStringTable::value_type(IDS_COMPONENT_VOLSTRAIN_REPEATER   , "Same as previous"),
  GeomecStringTable::value_type(IDS_ET_NRMSTRAIN                   , "NormalStrain"),
  GeomecStringTable::value_type(IDS_VALUENAME_NRMSTRAIN            , "Normal Strain"),
  GeomecStringTable::value_type(IDS_COMPONENT_NRMSTRAIN_GRADIENT   , "Single value"),
  GeomecStringTable::value_type(IDS_COMPONENT_NRMSTRAIN_REPEATER   , "Same as previous"),
  GeomecStringTable::value_type(IDS_ET_LATSTRAIN                   , "LateralStrain"),
  GeomecStringTable::value_type(IDS_VALUENAME_LATSTRAIN            , "Lateral Strain"),
  GeomecStringTable::value_type(IDS_COMPONENT_LATSTRAIN_GRADIENT   , "Single value"),
  GeomecStringTable::value_type(IDS_COMPONENT_LATSTRAIN_REPEATER   , "Same as previous"),
  GeomecStringTable::value_type(IDS_VALUENAME_STRAIN               , "Strains"),
  GeomecStringTable::value_type(IDS_ET_VOLUMETRIC_STRAIN           , "Volumetric"),
  GeomecStringTable::value_type(IDS_ET_NORMAL_STRAIN               , "Normal"),
  GeomecStringTable::value_type(IDS_ET_LATERAL_STRAIN              , "Lateral"),
  GeomecStringTable::value_type(IDS_COMPONENT_VOLUMETRIC_STRAIN    , "Volumetric"),
  GeomecStringTable::value_type(IDS_COMPONENT_NORMAL_STRAIN        , "Normal"),
  GeomecStringTable::value_type(IDS_COMPONENT_LATERAL_STRAIN       , "Lateral"),

  GeomecStringTable::value_type(IDS_RG_WPAXIALSTRAIN               , "Wellpath Axial Strain"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_FLUID_DENSITY     , "FluidDensity"),
  GeomecStringTable::value_type(IDS_VALUENAME_FLUID_DENSITY        , "Fluid Density"),
  GeomecStringTable::value_type(IDP_ONLYSMOOTHEDRESULTS            , "This model was saved with smoothed results only. To view the original (non-smoothed) results either load the original model or rerun the analysis."),
  GeomecStringTable::value_type(IDS_RG_WPSTRESS                    , "Wellpath stress"),
  GeomecStringTable::value_type(IDS_RC_AXIAL                       , "Axial"),
  GeomecStringTable::value_type(IDS_RC_RADIAL_MIN                  , "Minimum principal radial"),
  GeomecStringTable::value_type(IDS_RC_RADIAL_MAX                  , "Maximum principal radial"),
  GeomecStringTable::value_type(IDS_RG_THICKNESS                   , "Formation Thickness"),
  GeomecStringTable::value_type(IDS_ET_THICKNESS                   , "Thickness"),
  GeomecStringTable::value_type(IDS_ET_THICKNESS_CHANGE            , "Dlt_Thickness"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_REFERENCESTRESS   , "ReferenceStress"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_APERTUREPARAM     , "ApertureParameter"),
  GeomecStringTable::value_type(IDS_VALUENAME_REFERENCESTRESS      , "Reference Stress"),
  GeomecStringTable::value_type(IDS_VALUENAME_APERTUREPARAM        , "Aperture Parameter"),
  GeomecStringTable::value_type(IDS_ET_CASINGINTERNALTEMPERATURE   , "CasingInternalTemperature"),
  GeomecStringTable::value_type(IDS_ET_CASINGINTERNALPRESSURE      , "CasingInternalPressure"),
  GeomecStringTable::value_type(IDP_LOAD_FRACTURE_APERTURE_LOCKED  , "The Fracture Aperture material model is locked in this version. The model you are loading contains Fracture Aperture material. The material(s) will be removed from the formation(s)"),
  GeomecStringTable::value_type(IDS_RG_RTCI                        , "RTCI"),
  /* 115 - 120 */
  GeomecStringTable::value_type(CG_IDS_TIPOFTHEDAY                 , "Displays a Tip of the Day. "),
  GeomecStringTable::value_type(CG_IDS_TIPOFTHEDAYMENU             , "Ti&p of the Day..."),
  GeomecStringTable::value_type(CG_IDS_DIDYOUKNOW                  , "Did you know..."),
  GeomecStringTable::value_type(CG_IDS_FILE_ABSENT                 , "Tips file does not exist in the prescribed directory"),
  GeomecStringTable::value_type(CG_IDP_FILE_CORRUPT                , "Trouble reading the tips file"),
  GeomecStringTable::value_type(CG_IDS_TIPOFTHEDAYHELP             , "&Help"),
  /* 122 - 122 */
  GeomecStringTable::value_type(IDR_MAINFRAME                      , "GEOMEC\nUntitled\nGEOMEC\nGEOMEC 5 Projects (*.gm5)\n.gm5\nGeomec5.Document\nGEOMEC 5 Project"),
  /* verified up to 500 (inclusive) */
  /* 32771 - 32771 */
  GeomecStringTable::value_type(IDS_UNIT                           , "Unit"),
  GeomecStringTable::value_type(ID_NEW_SURFACE                     , "Insert surface"),
  GeomecStringTable::value_type(ID_EDIT_DELETE                     , "Delete the selected item\nDelete"),
  GeomecStringTable::value_type(ID_INSERT_FAULT                    , "Insert fault\nInsert fault\n"),
  GeomecStringTable::value_type(IDM_REMOVE_ALL                     , "Remove All"),
  GeomecStringTable::value_type(IDM_PROPERTIES                     , "Attributes"),
  GeomecStringTable::value_type(ID_ANALYSIS_LINEAR_DEPLETION       , "Performs the linear depletion analysis\nLinear Depletion"),
  GeomecStringTable::value_type(ID_ROTATE_RIGHT                    , "Rotate model right"),
  GeomecStringTable::value_type(ID_ROTATE_LEFT                     , "Rotate model left"),
  GeomecStringTable::value_type(ID_ZOOM_IN                         , "Zoom in on model\nZoom In [Ctrl +]"),
  GeomecStringTable::value_type(ID_ZOOM_OUT                        , "Zoom out on model\nZoom Out [Ctrl -]"),
  GeomecStringTable::value_type(ID_VIEW_BIRDEYEVIEW                , "Insert a new bird eye"),
  GeomecStringTable::value_type(IDS_HOMGENBOX                      , "Homogenization Boxes"),
  GeomecStringTable::value_type(ID_ZOOM_IN2                        , "Zoom in on model\nZoom in [Ctrl +]"),
  GeomecStringTable::value_type(ID_ZOOM_OUT2                       , "Zoom out on the model\nZoom out [Ctrl -]"),
  GeomecStringTable::value_type(ID_FILE_MODEL_PROPERTIES           , "Attributes of current model\nModel Attributes"),
  GeomecStringTable::value_type(ID_REMOVE_ITEM                     , "Removes selected item"),
  GeomecStringTable::value_type(ID_VIEW_TOOLBAR_ANALYSIS           , "Toolbar for analysis"),
  GeomecStringTable::value_type(IDS_INSERT_NODAL_VALUESET          , "Insert nodal property"),
  GeomecStringTable::value_type(IDS_INSERT_ELEMENT_VALUESET        , "Insert element property"),
  GeomecStringTable::value_type(ID_VIEW_PERSPECTIVE                , "Show the model in perspective mode\nToggle Perspective Mode"),
  GeomecStringTable::value_type(ID_VIEW_ROTATE                     , "Enable or disable dynamic rotation\nToggle Dynamic Rotation"),
  GeomecStringTable::value_type(ID_VIEW_BOUNDARY                   , "Show the bounding box of the model\nToggle Model Bounding Box"),
  GeomecStringTable::value_type(ID_VIEW_AXIS                       , "Show or hide the sundial\nToggle Sundial"),
  GeomecStringTable::value_type(ID_COORD_AXIS                      , "Show or hide the coord. axes\nToggle Coord. Axes"),
  GeomecStringTable::value_type(ID_VIEW_TOOLBAR_VIEW               , "Hide or show the view tool bar\nToggle View Toolbar"),
  GeomecStringTable::value_type(ID_VIEW_DEPTH                      , "Displays the depth in color gradient\nShow depth"),
  GeomecStringTable::value_type(ID_VIEW_COLOR                      , "Show the colors of geological objects\nShow Geology"),
  GeomecStringTable::value_type(ID_VIEW_VALUE                      , "Displays the value in color gradient\nShow value"),
  GeomecStringTable::value_type(ID_VIEW_HOTSPOT                    , "Show hotspots\nHotspot"),
  GeomecStringTable::value_type(ID_VIEW_GLOBAL                     , "Use the global colorscale\nGlobal Colorscale"),
  GeomecStringTable::value_type(ID_VIEW_LOCAL                      , "Use the local colorscale\nLocal Colorscale"),
  GeomecStringTable::value_type(ID_HIDELEGEND                      , "Hide Legend\nHide Legend"),
  GeomecStringTable::value_type(ID_VIEW_ATTRIBUTES_GLOBAL          , "Attributes of the global colorscale\nGlobal Colorscale Attributes"),
  GeomecStringTable::value_type(ID_VIEW_ATTRIBUTES_LOCAL           , "Attributes of the local colorscale\nLocal Colorscale Attributes"),
  GeomecStringTable::value_type(ID_VIEW_ATTRIBUTES_HOTSPOT         , "Attributes of the hotspot colorscale\nHotspot Attributes"),
  GeomecStringTable::value_type(ID_VIEW_OPTIONS                    , "Displays view options\nView Options"),
  GeomecStringTable::value_type(ID_ZOOM_DRAG                       , "Zoom in on a window\nZoom Window"),
  GeomecStringTable::value_type(ID_ZOOM_RESET                      , "Zoom to entire model\nZoom All [Ctrl 0]"),
  GeomecStringTable::value_type(ID_VIEW_LOCK_X                     , "Lock rotation around the easting axis\nLock Easting"),
  GeomecStringTable::value_type(ID_VIEW_LOCK_Y                     , "Lock rotation around the northing axis\nLock Northing"),
  GeomecStringTable::value_type(ID_VIEW_LOCK_Z                     , "Lock rotation around the depth axis\nLock Depth"),
  GeomecStringTable::value_type(ID_UNLOCK_AXES                     , "Unlock all rotation axes\nUnlock"),
  GeomecStringTable::value_type(IDS_RC_INVPRESS                    , "Pressure"),
  GeomecStringTable::value_type(ID_VIEW_TOOLBAR_GENERAL            , "Hide or show the general tool bar\nToggle General Toolbar"),
  GeomecStringTable::value_type(IDS_SCALINGBOXES                   , "Scaling boxes"),
  GeomecStringTable::value_type(ID_VIEW_PERSPECTIVE2               , "Shows the model in perspective\nToggles perspective"),
  GeomecStringTable::value_type(ID_VIEW_ROTATE2                    , "Enable or disables dynamic rotate\nToggles dynamic rotate"),
  GeomecStringTable::value_type(ID_VIEW_BOUNDARY2                  , "Shows the boundingbox of the model\nModel boudingbox"),
  GeomecStringTable::value_type(ID_VIEW_FILL                       , "Show the model in fill mode\nToggle Fill Mode"),
  GeomecStringTable::value_type(ID_VIEW_AXIS2                      , "Shows the position of axis\nToggles the axis"),
  GeomecStringTable::value_type(ID_VIEW_DEPTH2                     , "Displays the depth in color gradient\nDisplay depth"),
  GeomecStringTable::value_type(ID_VIEW_COLOR2                     , "Shows the color of geological objects\nColor of geological objects"),
  GeomecStringTable::value_type(IDS_RC_TRESCA                      , "Tresca"),
  GeomecStringTable::value_type(IDS_RC_MEANSTR                     , "Mean stress"),
  GeomecStringTable::value_type(IDS_RC_INVVOLSTR                   , "Volumetric strain"),
  GeomecStringTable::value_type(ID_VIEW_VALUE2                     , "Displays a result\nResult"),
  GeomecStringTable::value_type(ID_VIEW_HOTSPOT2                   , "View hotspot\nHotspot\n"),
  GeomecStringTable::value_type(ID_VIEW_GLOBAL2                    , "Global color scale\nGlobal color scale\n"),
  GeomecStringTable::value_type(ID_VIEW_LOCAL2                     , "Local color scale\nLocal color scale\n"),
  GeomecStringTable::value_type(ID_VIEW_OPTIONS2                   , "Attributes of the current view\nAttributes"),
  GeomecStringTable::value_type(ID_ZOOM_DRAG2                      , "Zoom in user specified rectangular area\nRectangular zoom"),
  GeomecStringTable::value_type(ID_ZOOM_RESET2                     , "Resets zoom the zoom factor\nReset zoom"),
  GeomecStringTable::value_type(ID_VIEW_LOCK_X2                    , "Rotation around the X-axis\nLock X-axis"),
  GeomecStringTable::value_type(ID_VIEW_LIGHTING                   , "Show the model with lighting\nToggles Lighting"),
  GeomecStringTable::value_type(ID_FILE_IMPORT                     , "Import file\nImport"),
  GeomecStringTable::value_type(ID_VIEW_Z_DIREC                    , "View model in depth direction\nView Depth Direction"),
  GeomecStringTable::value_type(ID_VIEW_E_DIREC                    , "View model in easting direction\nView Easting Direction"),
  GeomecStringTable::value_type(ID_VIEW_N_DIREC                    , "View model in northing direction\nView Northing Direction"),
  GeomecStringTable::value_type(ID_VIEW_BE_DIREC                   , "View model in birdeye view\nBirdeye View"),
  GeomecStringTable::value_type(ID_VIEW_LOCK_Y2                    , "Rotation around the Y-axis\nLock Y-axis"),
  GeomecStringTable::value_type(ID_VIEW_LOCK_Z2                    , "Rotation around the Z-axis\nLock Z-axis"),
  GeomecStringTable::value_type(ID_BUTTON_ZOOMWINDOW               , "Zoom in on a window\nZoom Window"),
  GeomecStringTable::value_type(ID_INSERT_VERTICAL_WELL_PATH       , "Insert a vertical wellpath\nInsert Vertical Wellpath"),
  GeomecStringTable::value_type(ID_UNLOCK_AXES2                    , "Unlock all rotation axis\nUnlock"),
  GeomecStringTable::value_type(ID_BUTTON32847                     , "Model in perspective\nPerspective\n"),
  GeomecStringTable::value_type(ID_BUTTON32848                     , "Fills surfaces\nFill\n"),
  GeomecStringTable::value_type(ID_ANALYSIS_NONLINEAR_CALC_PARAMS  , "Nonlinear calculation parameters\nNonlinear Calculation Parameters"),
  GeomecStringTable::value_type(ID_ANALYSIS_NONLINEAR_CALCULATION  , "Performs the nonlinear depletion analysis\nNonlinear Depletion"),
  GeomecStringTable::value_type(ID_VIEW_FILL2                      , "Show fill colors\nShow fill colors"),
  GeomecStringTable::value_type(ID_VIEW_BOUDARY2                   , "View bounding box\nBounding box\n"),
  GeomecStringTable::value_type(IDS_RPN_FORMULA_NOT_COMPLETED2     , "The formula is not valid or not completed"),
  GeomecStringTable::value_type(IDS_NAME_FIELD_EMPTY2              , "Supply a name "),
  GeomecStringTable::value_type(ID_VIEW_LIGHTING2                  , "Show lighting\nShow lighting"),
  GeomecStringTable::value_type(ID_VIEW_Z_DIREC2                   , "View Z direction"),
  GeomecStringTable::value_type(ID_VIEW_E_DIREC2                   , "View E direction"),
  GeomecStringTable::value_type(IDS_TREE_DATA_STORAGE              , "Data storage"),
  GeomecStringTable::value_type(IDS_TREE_MESH                      , "Mesh"),
  GeomecStringTable::value_type(IDS_TREE_RESULTS                   , "Results"),
  GeomecStringTable::value_type(IDS_TREE_VIEWS                     , "Views"),
  GeomecStringTable::value_type(IDS_TREE_REPORT                    , "Report"),
  GeomecStringTable::value_type(IDS_TREE_SURFACES                  , "Surfaces"),
  GeomecStringTable::value_type(IDS_TREE_POINTSETS                 , "Point/Element sets"),
  GeomecStringTable::value_type(IDS_TREE_HORIZONS                  , "Horizons"),
  GeomecStringTable::value_type(IDS_TREE_FAULTS                    , "Faults"),
  GeomecStringTable::value_type(IDS_TREE_FORMATIONS                , "Formations"),
  GeomecStringTable::value_type(IDS_MENU_PASTE                     , "&Paste"),
  GeomecStringTable::value_type(IDS_MENU_PROPERTIES                , "&Attributes"),
  GeomecStringTable::value_type(IDS_MENU_COPY                      , "&Copy"),
  GeomecStringTable::value_type(IDS_TOTAL_PROGRESS                 , "Total progress"),
  GeomecStringTable::value_type(IDS_CANCEL_PROGRESS                , "Do you want to cancel this operation?"),
  GeomecStringTable::value_type(IDS_TREE_BIRDEYE                   , "BirdEyes"),
  GeomecStringTable::value_type(IDS_NO_MODEL_SELECTED              , "Please, select a model ..."),
  GeomecStringTable::value_type(ID_VIEW_N_DIREC2                   , "View N direction"),
  GeomecStringTable::value_type(IDS_LABEL_MEAN                     , "Mean"),
  GeomecStringTable::value_type(IDS_TREE_MODEL                     , "Model"),
  GeomecStringTable::value_type(ID_VIEW_BE_DIREC2                  , "Bird eye view"),
  GeomecStringTable::value_type(IDS_LABEL_MAX                      , "Max"),
  GeomecStringTable::value_type(IDS_TREE_DEPLETION_STAGES          , "Depletion stages"),
  GeomecStringTable::value_type(IDS_BOUNDARY                       , "Boundary"),
  GeomecStringTable::value_type(IDS_TYPE_SURFACE                   , "Surface"),
  GeomecStringTable::value_type(IDS_TYPE_PRESSURE                  , "Pressure"),
  GeomecStringTable::value_type(IDS_TYPE_STRESS                    , "Stress"),
  GeomecStringTable::value_type(IDS_MODEL_PROPERTIES               , "Model attributes"),
  GeomecStringTable::value_type(IDS_FIELD_UNIT                     , "Field"),
  GeomecStringTable::value_type(IDS_SI_UNIT                        , "SI"),
  GeomecStringTable::value_type(ID_BUTTON_ZOOMWINDOW2              , "Zoom window in on model\nZoom window "),
  GeomecStringTable::value_type(IDS_UNIT_SI_COHESION               , "MPa/m"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_COHESION            , "psi/ft"),
  GeomecStringTable::value_type(IDS_UNIT_SI_PRESSURE               , "MPa"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_PRESSURE            , "psi"),
  GeomecStringTable::value_type(IDS_UNIT_SI_STRESS                 , "MPa"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_STRESS              , "psi"),
  GeomecStringTable::value_type(IDS_UNIT_DIMENSIONLESS             , " -"),
  GeomecStringTable::value_type(IDS_UNIT_SI_YOUNGS_MODULUS         , "N/m2"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_YOUNGS_MODULUS      , "N/ft2"),
  GeomecStringTable::value_type(IDS_UNIT_SI_VELOCITY               , "m/s"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_VELOCITY            , "ft/s"),
  GeomecStringTable::value_type(IDS_UNIT_SI_ANGLE                  , "Degree"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_ANGLE               , "Degree"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_LENGTH              , "ft"),
  GeomecStringTable::value_type(IDS_UNIT_SI_LENGTH                 , "m"),
  GeomecStringTable::value_type(IDS_PROPERTY_NAME                  , "Property %1"),
  GeomecStringTable::value_type(IDS_VALUENAME_YOUNGS_MODULUS       , "Young's Modulus"),
  GeomecStringTable::value_type(IDS_VALUENAME_POISSONS_RATIO       , "Poisson's Ratio"),
  GeomecStringTable::value_type(IDS_VALUENAME_COHESION             , "Cohesion"),
  GeomecStringTable::value_type(IDS_VALUENAME_FRICTION_ANGLE       , "Friction Angle"),
  GeomecStringTable::value_type(IDS_VALUENAME_POROSITY             , "Porosity"),
  GeomecStringTable::value_type(IDS_VALUENAME_BULKSTIFFNESS        , "Bulk Modulus"),
  GeomecStringTable::value_type(IDS_VALUENAME_FLUID_BULK_MOD       , "Fluid bulk modulus"),
  GeomecStringTable::value_type(IDS_VALUENAME_SHEARMODULUS         , "Shear Modulus"),
  GeomecStringTable::value_type(IDS_VALUENAME_RHOB                 , "Density"),
  GeomecStringTable::value_type(IDS_VALUENAME_DISPLACEMENT         , "Displacement"),
  GeomecStringTable::value_type(IDS_VALUENAME_PRESSURE             , "Pressure"),
  GeomecStringTable::value_type(IDS_VALUENAME_STRESS_TENSOR        , "Stress Tensor"),
  GeomecStringTable::value_type(IDS_VALUENAME_SURFACE              , "Surface"),
  GeomecStringTable::value_type(IDS_VALUENAME_PRINCIPAL_STRESS     , "Principal Stress"),
  GeomecStringTable::value_type(IDS_VALUENAME_STRAIN_TENSOR        , "Strain Tensor"),
  GeomecStringTable::value_type(IDS_VALUENAME_PRINCIPLE_STREAIN    , "Principal Strain"),
  GeomecStringTable::value_type(IDS_VALUENAME_DEPTH                , "Depth"),
  GeomecStringTable::value_type(IDS_VALUENAME_DISP_VECTOR          , "Displacement Vector"),
  GeomecStringTable::value_type(IDS_VALUENAME_VELOCITYP            , "Vp"),
  GeomecStringTable::value_type(IDS_VALUENAME_VELOCITYS            , "Vs"),
  GeomecStringTable::value_type(IDS_VALUENAME_INITFRICTION         , "Initial Friction Angle"),
  GeomecStringTable::value_type(IDS_VALUENAME_HARDENING            , "Hardening Parameter"),
  GeomecStringTable::value_type(IDS_VALUENAME_PRECONSOLIDATION     , "Preconsolidation Pressure"),
  GeomecStringTable::value_type(IDS_VALUENAME_CAPSHAPE             , "Cap Shape Factor"),
  GeomecStringTable::value_type(IDS_VALUENAME_DILATATION           , "Dilatation Angle"),
  GeomecStringTable::value_type(IDS_COMPONENT_PRESSURE_DISTRIBUTED , "Distributed"),
  GeomecStringTable::value_type(IDS_COMPONENT_PRESSURE_REPEAT      , "Same as previous"),
  GeomecStringTable::value_type(IDS_COMPONENT_PRESSURE_CONSTANT    , "Constant"),
  GeomecStringTable::value_type(IDS_COMPONENT_PRESSURE_GWC         , "GWC - OWC"),
  GeomecStringTable::value_type(IDS_COMPONENT_X                    , "N"),
  GeomecStringTable::value_type(IDS_COMPONENT_Y                    , "E"),
  GeomecStringTable::value_type(IDS_COMPONENT_Z                    , "Z"),
  GeomecStringTable::value_type(IDS_COMPONENT_XX                   , "NN"),
  GeomecStringTable::value_type(IDS_COMPONENT_YY                   , "EE"),
  GeomecStringTable::value_type(IDS_COMPONENT_ZZ                   , "DD"),
  GeomecStringTable::value_type(IDS_COMPONENT_XY                   , "NE"),
  GeomecStringTable::value_type(IDS_COMPONENT_YZ                   , "ED"),
  GeomecStringTable::value_type(IDS_COMPONENT_XZ                   , "ND"),
  GeomecStringTable::value_type(IDS_COMPONENT_DEFAULT              , "Value"),
  GeomecStringTable::value_type(IDS_VALUENAME_LATRATIO_MAX         , "SHtot/Svtot_ini"),
  GeomecStringTable::value_type(IDS_VALUENAME_LATRATIO_MIN         , "Shtot/Svtot_ini"),
  GeomecStringTable::value_type(IDS_VALUENAME_AZIMUTH              , "SHtotAZimuth_ini"),
  GeomecStringTable::value_type(IDS_VALUENAME_INIPORO              , "Initial Porosity"),
  GeomecStringTable::value_type(IDS_VALUENAME_CREEP_A1             , "A1"),
  GeomecStringTable::value_type(IDS_VALUENAME_CREEP_A2             , "A2"),
  GeomecStringTable::value_type(IDS_VALUENAME_CREEP_N1             , "n1"),
  GeomecStringTable::value_type(IDS_VALUENAME_CREEP_N2             , "n2"),
  GeomecStringTable::value_type(IDS_VALUENAME_DENSITY              , "Density"),
  GeomecStringTable::value_type(IDS_LOG_DATA_IMPORT                , "Log data files (*.clf)|*.clf|All Files (*.*)|*.*|"),
  GeomecStringTable::value_type(IDS_RAT_DATA_IMPORT                , "Radioactive tag data files (*.rag)|*.rag|All Files (*.*)|*.*|"),
  GeomecStringTable::value_type(IDP_NODIAPATHFOUND                 , "The path to the DIANA kernel could not be found in the registry. Please reinstall GEOMEC."),
  GeomecStringTable::value_type(IDS_FILE_OPEN_FILTER               , "GEOMEC 5 Projects (*.gm5)|*.gm5|GEOMEC 4 Projects (*.gm4)|*.gm4|GEOMEC 3 Projects (*.gmp)|*.gmp|GEOMEC 2 Databases (*.gm3)|*.gm3|GEOMEC 2 Databases (*.gm2)|*.gm2|All Files (*.*)|*.*||"),
  GeomecStringTable::value_type(IDS_FILE_SAVE_FILTER               , "GEOMEC 5 Projects (*.gm5)|*.gm5|GEOMEC 4 Projects (*.gm4)|*.gm4|All Files (*.*)|*.*||"),
  GeomecStringTable::value_type(IDS_IMPORT_FILTER                  , "ASCII Files (*.txt, *.dat, *.xyz)|*.txt; *.dat; *.xyz|GoCAD Files (*.ts, *.mx, *.so, *.vs)|*.ts; *.mx; *.so; *.vs|Excel Files (*.xls;*.xls*)|*.xls;*.xls*|Shell File Format (*.vt)|*.vt|All Files (*.*)|*.*||"),
  GeomecStringTable::value_type(IDS_IMPORT_GOCAD_FILTER            , "GoCAD Files (*.ts, *.mx, *.so, *.vs)|*.ts; *.mx; *.so; *.vs|ASCII Files (*.txt, *.dat, *.xyz)|*.txt; *.dat; *.xyz|Excel Files (*.xls;*.xls*)|*.xls;*.xls*|All Files (*.*)|*.*||"),
  GeomecStringTable::value_type(IDP_SAVE_BEFORE_ANALYSIS           , "The model has to be saved to a database before the analysis can be started."),
  GeomecStringTable::value_type(IDS_TREE_XSECTIONS                 , "Cross-sections"),
  GeomecStringTable::value_type(IDS_TREE_WELLPATHS                 , "Wellpaths"),
  GeomecStringTable::value_type(IDS_TREE_WELL_PATHS                , "Well Paths"),
  GeomecStringTable::value_type(IDS_WELLPATH_IMPORT                , "Deviated Well Files (*.mwr;*.mx;*.txt;*.xls;*.xls*)|*.mwr;*.mx;*.txt;*.xls;*.xls*|Mores Reports (*.mwr)|*.mwr|GoCAD Well Files (*.mx)|*.mx|ASCII Well Files (*.txt)|*.txt|Excell Well Files (*.xls;*.xls*)|*.xls;*.xls*|All Files (*.*)|*.*|"),
  GeomecStringTable::value_type(IDS_TREE_GRAPHS                    , "Graphs"),
  GeomecStringTable::value_type(IDS_USE_EXISTING_RESULTS           , "This model already contains results. Do you want to use these?"),
  GeomecStringTable::value_type(IDS_FORMATIONPLANE                 , "Formation plane"),
  GeomecStringTable::value_type(IDS_PLANE_MIDDLE                   , "Middle plane"),
  GeomecStringTable::value_type(IDS_PLANE_TOP                      , "Top plane"),
  GeomecStringTable::value_type(IDS_PLANE_BOTTOM                   , "Bottom plane"),
  GeomecStringTable::value_type(IDS_PLANE_EXPORT                   , "Export formation plane"),
  GeomecStringTable::value_type(IDS_PLANE_DELETE                   , "Delete formation plane"),
  GeomecStringTable::value_type(IDS_ET_UNKNOWN                     , "Unknown"),
  GeomecStringTable::value_type(IDS_ET_PRESSURE                    , "Pressure"),
  GeomecStringTable::value_type(IDS_ET_SURFACE                     , "Surface"),
  GeomecStringTable::value_type(IDS_ET_YOUNG_MODULUS               , "YoungsModulus"),
  GeomecStringTable::value_type(IDS_ET_POISSON_RATIO               , "PoissonRatio"),
  GeomecStringTable::value_type(IDS_ET_COHESION                    , "Cohesion"),
  GeomecStringTable::value_type(IDS_ET_FRICTION_ANGLE              , "FrictionAngle"),
  GeomecStringTable::value_type(IDS_ET_POROSITY                    , "Porosity"),
  GeomecStringTable::value_type(IDS_ET_INIT_FRICTION_ANLGE         , "InitFriction"),
  GeomecStringTable::value_type(IDS_ET_HARDENING                   , "Hardening"),
  GeomecStringTable::value_type(IDS_ET_PRECONSOLIDATION            , "PreConsolidation"),
  GeomecStringTable::value_type(IDS_ET_CAPSHAPE                    , "CapShape"),
  GeomecStringTable::value_type(IDS_ET_DILATATION                  , "Dilatation"),
  GeomecStringTable::value_type(IDS_ET_A1                          , "A1"),
  GeomecStringTable::value_type(IDS_ET_N1                          , "n1"),
  GeomecStringTable::value_type(IDS_ET_A2                          , "A2"),
  GeomecStringTable::value_type(IDS_ET_N2                          , "n2"),
  GeomecStringTable::value_type(IDS_ET_LATRATIO_MAX                , "LatRatioMax"),
  GeomecStringTable::value_type(IDS_ET_LATRATIO_MIN                , "LatRatioMin"),
  GeomecStringTable::value_type(IDS_ET_AZIMUTH                     , "LatRatioMaxAzimuth"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_2                , "InvI2"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_3                , "InvI3"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_VON_MISES        , "InvVonMises"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_TRESCA           , "InvTresca"),
  GeomecStringTable::value_type(IDS_ET_SHEAR_CAPACITY              , "ShearCap"),
  GeomecStringTable::value_type(IDS_ET_COMPACTION_CAPACITY         , "CompactionCap"),
  GeomecStringTable::value_type(IDS_ET_PLASTIC                     , "Plastic"),
  GeomecStringTable::value_type(IDS_ET_DELTA_EFF_MAX_PRINC_STRESS  , "Dlt_EPStress1"),
  GeomecStringTable::value_type(IDS_ET_DELTA_EFF_MED_PRINC_STRESS  , "Dlt_EPStress2"),
  GeomecStringTable::value_type(IDS_ET_DELTA_EFF_MIN_PRINC_STRESS  , "Dlt_EPStress3"),
  GeomecStringTable::value_type(IDS_ET_PORE_PRESSURE               , "Pressure"),
  GeomecStringTable::value_type(IDS_ET_NORM_STRESS_FAULT           , "NormalStress"),
  GeomecStringTable::value_type(IDS_ET_DELTA_SHEAR_STRESS_FAULT    , "Dlt_MaxInPlaneStress"),
  GeomecStringTable::value_type(IDS_ET_DELTA_NORM_STRESS_FAULT     , "Dlt_NormalStress"),
  GeomecStringTable::value_type(IDS_ET_SHEAR_CAPACITY_FAULT        , "SHEAR_CAPACITY_FLT"),
  GeomecStringTable::value_type(IDS_ET_SLIP_FAULT                  , "SLIP_FLT"),
  GeomecStringTable::value_type(IDS_ET_GAMMA_MED                   , "GammaInt"),
  GeomecStringTable::value_type(IDS_ET_GAMMA_MIN                   , "GammaMin"),
  GeomecStringTable::value_type(IDS_ET_GAMMA_VOLUME                , "GammaVol"),
  GeomecStringTable::value_type(IDS_ET_NAN                         , "NAN"),
  GeomecStringTable::value_type(IDS_ET_FAULT_DISPLACEMENT          , "FaultDisplacement"),
  GeomecStringTable::value_type(IDS_ET_YOUNGMODULUS_NORM           , "YoungModulusNorm"),
  GeomecStringTable::value_type(IDS_ET_FAULT_DILATATION            , "FaultDilatation"),
  GeomecStringTable::value_type(IDS_ET_DSTABOR                     , "Mud"),
  GeomecStringTable::value_type(IDS_ET_HOTSPOT_HOT                 , "HOT"),
  GeomecStringTable::value_type(IDS_ET_FAULT_EFF_NORMAL_STRESS     , "FaultEStressNormal"),
  GeomecStringTable::value_type(IDS_ET_HOTSPOT_COLD                , "COLD"),
  GeomecStringTable::value_type(IDS_ET_FAULT_SHEAR_STRESS          , "FaultStressShear"),
  GeomecStringTable::value_type(IDS_ET_HOTSPOT_MIN                 , "MIN_HOT"),
  GeomecStringTable::value_type(IDS_ET_HOTSPOT_MAX                 , "MAX_HOT"),
  GeomecStringTable::value_type(IDS_ET_HOTSPOT_MIN_VAL             , "MIN_VALUE"),
  GeomecStringTable::value_type(IDS_ET_FAULT_TOTAL_NORMAL_STRESS   , "FaultTStressNormal"),
  GeomecStringTable::value_type(IDS_ET_HOTSPOT_MAX_VAL             , "MAX_VALUE"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_FLUID_SHEAR_MOD   , "BulkFluidModulus"),
  GeomecStringTable::value_type(IDM_INSERT_ITEM                    , "Insert Item"),
  GeomecStringTable::value_type(ID_ANALYSIS_PROPERTIES             , "Analysis options\nAnalysis Options"),
  GeomecStringTable::value_type(ID_VIEW_TOOLBAR_CALC               , "Hide or show the analysis tool bar\nToggle Analysis Toolbar"),
  GeomecStringTable::value_type(IDP_EXCELNOTAVAILABLE_EXPORT       , "Create tetramesh"),
  GeomecStringTable::value_type(ID_ANALYSISLOG                     , "Show a log of the last analysis\nAnalysis Log"),
  GeomecStringTable::value_type(IDP_EXCELNOTINSTALLED              , "Excel must be installed in order to read Excel files."),
  GeomecStringTable::value_type(ID_VIEW_ZOOMWINDOW                 , "Zoom to a window\nZoom Window"),
  GeomecStringTable::value_type(IDP_CANNOTOPENFILE                 , "Could not open file '%s'."),
  GeomecStringTable::value_type(IDP_NOVALIDSHEETS                  , "No valid sheets found in file '%s'."),
  GeomecStringTable::value_type(IDP_INVALIDFORMATEXCELSHEET        , "The sheet named '%s' has an invalid format."),
  GeomecStringTable::value_type(ID_INSERT_MESH_REGION_POLY         , "Insert a polygonal meshregion\nPolygonal Mesh Region"),
  GeomecStringTable::value_type(ID_INSERT_MESH_REGION_RECT         , "Insert a rectangular meshregion\nRectangular Mesh Region"),
  GeomecStringTable::value_type(IDP_INVALIDFORMATEXCELCELL         , "Cell (%d, %d) of sheet '%s' contains an invalid value."),
  GeomecStringTable::value_type(IDP_INVALIDFORMATEXCELHEADER       , "Invalid header found in sheet '%s'."),
  GeomecStringTable::value_type(ID_INSERT_X_SECTION                , "Insert a cross-section\nInsert Cross-section"),
  GeomecStringTable::value_type(IDP_ERRORRUNNINGANALYSIS           , "An error occurred running the DIANA kernel"),
  GeomecStringTable::value_type(ID_VIEW_MESH_DLGBAR                , "Hide or show the mesh selecter toolbar\n Mesh Selecter toolbar"),
  GeomecStringTable::value_type(IDS_DISPLACEMENT_SUPPORT_NODE      , "Prescribed Displacements"),
  GeomecStringTable::value_type(IDS_PRESSURE_SUPPORT_NODE          , "Boundary Conditions"),
  GeomecStringTable::value_type(IDP_GLOBALTENSORVERTICAL           , "This will set the shear terms with respect to the vertical direction (NV and EV) to zero. Continue?"),
  GeomecStringTable::value_type(ID_CREATE_MESH                     , "Create the mesh\nCreate Mesh"),
  GeomecStringTable::value_type(IDP_SUPPORT_NODE_APPLYTOALL        , "The settings for this corner node for all depletion stages will be applied to all other corner nodes in the model. Continue?"),
  GeomecStringTable::value_type(ID_INVALIDATE_MESH                 , "Invalidate the mesh\nInvalidate Mesh"),
  GeomecStringTable::value_type(IDP_SUPPORT_RESETGLOBALTENSOR      , "The definition for one or more depletion stages was reset to 'Undefined'. Any references to those tensors will be reset as well. Continue?"),
  GeomecStringTable::value_type(IDP_SUPPORT_FACE_APPLYTOALL        , "The settings for this face for all depletion stages will be applied to all other faces in the model. Continue?"),
  GeomecStringTable::value_type(IDP_MULTIPLEDEPLETIONSTAGESNEEDED  , "At least one depletion stage (other than initial) is needed for this operation."),
  GeomecStringTable::value_type(ID_COPYPICTURE                     , "Copy the picture to the clipboard\nCopy Picture"),
  GeomecStringTable::value_type(IDP_INVALIDTEMPPATH                , "The location for temporary files is invalid."),
  GeomecStringTable::value_type(IDP_TEMPVARINVALID                 , "The TEMP environment variable is not valid."),
  GeomecStringTable::value_type(IDP_EXCELILLEGALUNITVALUE          , "Illegal unit value. Use SI or FIELD"),
  GeomecStringTable::value_type(IDP_EXCELILLEGALDIMVALUE           , "Illegal dimension value in sheet. Use 2 or 3."),
  GeomecStringTable::value_type(IDP_EXCELINVALIDHEADER             , "Invalid header in sheet."),
  GeomecStringTable::value_type(IDP_EXCELILLEGALELEMENTTYPE        , "Illegal element type in sheet %s in cell %s%d"),
  GeomecStringTable::value_type(IDS_RC_INV2                        , "I2"),
  GeomecStringTable::value_type(IDS_RC_INV3                        , "I3"),
  GeomecStringTable::value_type(IDS_RC_VONMIS                      , "Von Mises"),
  GeomecStringTable::value_type(IDS_UNIT_SI_PERTIME                , "1/s"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_PERTIME             , "1/s"),
  GeomecStringTable::value_type(IDS_UNIT_SI_TIME                   , "s"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_TIME                , "s"),
  GeomecStringTable::value_type(IDS_FILE_TAG_STRESS_TENSOR_XX2, "Stressxx"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_XX                   , "NN"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM1                    , "KNNNN"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM2                    , "KNNEE"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_YY                   , "EE"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_ZZ                   , "VV"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_XY                   , "NE"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_XZ                   , "NV"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_YZ                   , "EV"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_MAX                  , "1"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_MED                  , "2"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_MIN                  , "3"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_MEAN             , "InvMean"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_VOLUME           , "InvVolumetric"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_PRESSURE         , "InvPressure"),
  GeomecStringTable::value_type(IDS_ET_VECTOR_X                    , "N"),
  GeomecStringTable::value_type(IDS_ET_VECTOR_Y                    , "E"),
  GeomecStringTable::value_type(IDS_ET_VECTOR_Z                    , "V"),
  GeomecStringTable::value_type(IDS_ET_VECTOR_LENGTH               , "L"),
  GeomecStringTable::value_type(IDS_ET_VECTOR_FULL                 , ""), //empty
  GeomecStringTable::value_type(IDS_ET_EFFECTIVE                   , "E"),
  GeomecStringTable::value_type(IDS_ET_STRAIN                      , "Strain"),
  GeomecStringTable::value_type(IDS_ET_DISPLACEMENT                , "Displacement"),
  GeomecStringTable::value_type(IDS_ET_EFFECTIVE_CHANGE            , "Dlt_E"),
  GeomecStringTable::value_type(IDS_ET_CHANGE                      , "Dlt_"),
  GeomecStringTable::value_type(IDS_ET_PORE_PRESSURE_CHANGE        , "Dlt_Pressure"),
  GeomecStringTable::value_type(IDS_ET_GAMMA_VERTICAL              , "GammaV"),
  GeomecStringTable::value_type(IDS_ET_GAMMA_MAX                   , "GammaMax"),
  GeomecStringTable::value_type(IDP_NOHELPAVAILABLE                , "No help is available for this item"),
  GeomecStringTable::value_type(ID_INSERT_CROSS_SECTION            , "Insert a cross section\nCross section"),
  GeomecStringTable::value_type(IDP_DEPLETINGWITHUNDRAINEDMAT      , "The following formations are depleting and use Undrained Elastic material, which is not allowed. The analysis can not be performed."),
  GeomecStringTable::value_type(IDP_UNKNOWNFILEEXTENSIONIMPORT     , "The extension of the file '%s' could not be recognised. This file will not be imported."),
  GeomecStringTable::value_type(IDP_FAILUREPARSING                 , "Could not parse the file '%s' as %s."),
  GeomecStringTable::value_type(IDS_CREATINGSURFACE                , "Generating surface..."),
  GeomecStringTable::value_type(IDP_LOAD_QUADRATIC_WITH_CSHE       , "Quadratic elements in combination with Enhanced Assumed Strain method is not allowed. The Enhanced Assumed Strain method will be disabled."),
  GeomecStringTable::value_type(IDP_CANNOTOVERWRITE                , "Unable to overwrite file '%s'"),
  GeomecStringTable::value_type(IDP_ERRORDURINGANALYSIS            , "Analysis failed, no results will be available. For EXPERT use: copy the filos file, save the model, and try loading partial results."),
  GeomecStringTable::value_type(IDS_ET_HARD_COHESION1              , "HardCohesion1"),
  GeomecStringTable::value_type(ID_FORMATIONSKIN                   , "Show formation skin only\nFormation Skin"),
  GeomecStringTable::value_type(IDS_ET_HARD_COHESION2              , "HardCohesion2"),
  GeomecStringTable::value_type(IDS_ET_HARD_COHESION3              , "HardCohesion3"),
  GeomecStringTable::value_type(IDS_ET_HARD_FRICTION1              , "HardFriction1"),
  GeomecStringTable::value_type(IDS_ET_HARD_FRICTION2              , "HardFriction2"),
  GeomecStringTable::value_type(IDS_ET_HARD_FRICTION3              , "HardFriction3"),
  GeomecStringTable::value_type(IDS_ET_EQUIV_PLAST_STRAIN1         , "EquivalentPlasticStrain1"),
  GeomecStringTable::value_type(IDS_ET_EQUIV_PLAST_STRAIN2         , "EquivalentPlasticStrain2"),
  GeomecStringTable::value_type(IDS_ET_EQUIV_PLAST_STRAIN3         , "EquivalentPlasticStrain3"),
  GeomecStringTable::value_type(IDS_VALUENAME_HARD_COHESION1       , "Hardening Cohesion 1"),
  GeomecStringTable::value_type(IDS_VALUENAME_HARD_COHESION2       , "Hardening Cohesion 2"),
  GeomecStringTable::value_type(IDS_VALUENAME_HARD_COHESION3       , "Hardening Cohesion 3"),
  GeomecStringTable::value_type(IDS_VALUENAME_HARD_FRICTION1       , "Hardening Friction Angle 1"),
  GeomecStringTable::value_type(IDS_VALUENAME_HARD_FRICTION2       , "Hardening Friction Angle 2"),
  GeomecStringTable::value_type(IDS_VALUENAME_HARD_FRICTION3       , "Hardening Friction Angle 3"),
  GeomecStringTable::value_type(IDS_VALUENAME_EQUIV_PLAST_STRAIN1  , "Equivalent Plastic Strain 1"),
  GeomecStringTable::value_type(IDS_VALUENAME_EQUIV_PLAST_STRAIN2  , "Equivalent Plastic Strain 2"),
  GeomecStringTable::value_type(IDS_VALUENAME_EQUIV_PLAST_STRAIN3  , "Equivalent Plastic Strain 3"),
  GeomecStringTable::value_type(IDP_MAPPING_LOCKED_LOAD            , "The element-to-element mapping feature is locked in this version.\nThe mapping will be set to point interpolation."),
  GeomecStringTable::value_type(IDP_MATLIB_NOT_SAME                , "You can not use the same material library file for Casing Grade and Rock materials."),
  GeomecStringTable::value_type(IDP_NL_LARGEDEFORMWITHCSHE         , "You combined large deformations with enhanced assumed strain method. Enhanced assumed strain method will be ignored in a non-linear analysis.\nThe use of quadratic elements is advised."),
  GeomecStringTable::value_type(IDP_LOAD_CAMCLAY_LOCKED            , "The Cam-clay material model is locked in this version. The model you are loading contains Cam-clay material. The material(s) will be removed from the formation(s)."),
  GeomecStringTable::value_type(IDP_LOAD_FOKKER_LOCKED             , "The Salt Creep material model is locked in this version. The model you are loading contains Salt Creep material. The material(s) will be removed from the formation(s)"),
  GeomecStringTable::value_type(IDP_LOADLOCKED_LARGEDEF            , "Large deformations are locked in this version. The model you are loading has the large deformations option activated. It will be deactivated."),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_EDGE_RATIO      , "Min/Max edge ratio"),
  GeomecStringTable::value_type(IDS_DSB_NOT_CALCULATED             , "Optimum mudweight not calculated"),
  GeomecStringTable::value_type(IDS_DSB_UNKNOWN_ERROR              , "Unknown error in mudweight calculation"),
  GeomecStringTable::value_type(IDS_DSB_OPTIMUM_MUDWEIGHT_FOUND    , "Optimum mudweight found"),
  GeomecStringTable::value_type(IDS_DSB_WELL_ALWAYS_STABLE         , "Well always stable"),
  GeomecStringTable::value_type(IDS_DSB_PREMATURE_ANALYSIS_FAILURE , "Unknown"),
  GeomecStringTable::value_type(IDS_DSB_UNABLE_DETERMINE_STABLE_MUDWEIGHT
                                                                   , "Unable to determine stable mudweight"),
  GeomecStringTable::value_type(IDS_DSB_WELL_ALWAYS_UNSTABLE       , "Well always unstable"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_MAX_EDGE           , "MaxEdgeLength"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_AVERAGE_EDGE       , "AverageEdgeLength"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_VOLUME             , "ElementVolume"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_DEPTH              , "Depth"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_MIN_MAX_EDGE       , "MinMaxEdgeRatio"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_AREA               , "ElementArea"),
  GeomecStringTable::value_type(IDP_FAULTSLOCKED                   , "Faults are locked in this version. This database can not be loaded."),
  GeomecStringTable::value_type(IDP_SLIPPINGHORIZONSLOCKED         , "Slipping horizons are locked in this version for tetrahedron models. The horizons are modified to not slipping."),
  GeomecStringTable::value_type(IDP_VERSIONTOOLOW                  , "This file was saved with a GEOMEC version that was newer than this version. The file can not be loaded."),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_MAX_ANGLE       , "Maximum angle"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_MIN_ANGLE       , "Minimum angle"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_MAX_ANGLE          , "MaxAngle"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_MIN_ANGLE          , "MinAngle"),
  GeomecStringTable::value_type(IDS_ET_FAULT_SHEARCAPACITY         , "FaultShearCap"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_AHD                , "Along hole depth"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_TVD                , "True vertical depth"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_TRACK_COORD        , "Track coordinates"),
  GeomecStringTable::value_type(ID_INDICATOR_UNIT                  , "Unit"),
  GeomecStringTable::value_type(IDS_ET_DISPLACEMENT_X              , "Displacementx"),
  GeomecStringTable::value_type(IDS_ET_DISPLACEMENT_Y              , "Displacementy"),
  GeomecStringTable::value_type(IDS_ET_DISPLACEMENT_Z              , "Displacementz"),
  GeomecStringTable::value_type(IDS_ET_STRESS                      , "Stress"),
  GeomecStringTable::value_type(IDS_ECLIPSE_FILE                   , "Import eclipse file"),
  GeomecStringTable::value_type(IDS_ECLIPSE_HORIZON                , "Select eclipse horizon"),
  GeomecStringTable::value_type(ID_INDICATOR_LIN                   , "LIN"),
  GeomecStringTable::value_type(ID_INDICATOR_NON_LIN               , "NONLIN"),
  GeomecStringTable::value_type(IDS_NR_TIMESTEP_GREATER_INITIAL    , "Number of timesteps must be greater than one"),
  GeomecStringTable::value_type(IDS_NON_AND_LINEAR                 , "Linear/non-linear"),
  GeomecStringTable::value_type(IDS_ET_COORDINATE_X                , "Easting"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM3                    , "KNNDD"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM4                    , "KNNNE"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM5                    , "KNNED"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM6                    , "KNNDN"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM7                    , "KEEEE"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM8                    , "KEEDD"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM9                    , "KEENE"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM10                   , "KEEED"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM11                   , "KEEDN"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM12                   , "KDDDD"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM13                   , "KDDNE"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM14                   , "KDDED"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM15                   , "KDDDN"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM16                   , "KNENE"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM17                   , "KNEED"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM18                   , "KNEDN"),
  GeomecStringTable::value_type(IDS_ET_COORDINATE_Y                , "Northing"),
  GeomecStringTable::value_type(IDS_ET_COORDINATE_Z                , "Depth"),
  GeomecStringTable::value_type(IDS_LOCAL_COLORSCALE               , "Local"),
  GeomecStringTable::value_type(IDS_NEW_COLOR_GRADIENT             , "new colorgradient"),
  GeomecStringTable::value_type(IDS_NEW_HOTSPOT                    , "new hotspot"),
  GeomecStringTable::value_type(IDS_ET_STRESS_TENSOR               , "StressNN"),
  GeomecStringTable::value_type(IDS_ET_BULKSTIFFNESS               , "BulkStiffness"),
  GeomecStringTable::value_type(IDS_ET_SHEARMODULUS                , "ShearModulus"),
  GeomecStringTable::value_type(IDS_ET_RHOB                        , "Density"),
  GeomecStringTable::value_type(IDS_ET_CREEP_A1                    , "A1"),
  GeomecStringTable::value_type(IDS_ET_CREEP_N1                    , "N1"),
  GeomecStringTable::value_type(IDS_ET_CREEP_A2                    , "A2"),
  GeomecStringTable::value_type(IDS_ET_CREEP_N2                    , "N2"),
  GeomecStringTable::value_type(IDS_ET_VELOCITYP                   , "Vp"),
  GeomecStringTable::value_type(IDS_ET_VELOCITYS                   , "Vs"),
  GeomecStringTable::value_type(IDS_ET_INITFRICTION                , "InitFriction"),
  GeomecStringTable::value_type(IDS_UNIT_SI_DENSITY                , "kg/m3"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_DENSITY             , "lb/gal"),
  GeomecStringTable::value_type(IDS_RETRIEVE_RESULTS               , "Retrieving results ..."),
  GeomecStringTable::value_type(IDS_CREATE_NODEMAP                 , "Creating a node map ..."),
  GeomecStringTable::value_type(IDS_RETRIEVE_LINEAR_RESULTS        , "Retrieving linear results"),
  GeomecStringTable::value_type(IDS_RETRIEVE_NONLINEAR_RESULTS     , "Retrieving non-linear results"),
  GeomecStringTable::value_type(IDS_RETRIEVE_ELEMENT_RESULTS       , "Element results for %1"),
  GeomecStringTable::value_type(IDS_RETRIEVE_NODAL_RESULTS         , "Nodal results for %s"),
  GeomecStringTable::value_type(IDS_BUILD_COHESION_FRICTION_MAP    , "Build map"),
  GeomecStringTable::value_type(IDS_RG_DISPLACEMENT                , "Displacements"),
  GeomecStringTable::value_type(IDS_RG_ABSOLUTE                    , "Absolute"),
  GeomecStringTable::value_type(IDS_RG_CHANGE                      , "Change"),
  GeomecStringTable::value_type(IDS_RG_STRESSES                    , "Stresses"),
  GeomecStringTable::value_type(IDS_RG_TOTAL                       , "Total"),
  GeomecStringTable::value_type(IDS_RC_NORTHING                    , "Northing"),
  GeomecStringTable::value_type(IDS_RC_EASTING                     , "Easting"),
  GeomecStringTable::value_type(IDS_RC_DEPTH                       , "Depth"),
  GeomecStringTable::value_type(IDS_RC_LENGTH                      , "Length"),
  GeomecStringTable::value_type(IDS_RG_ROOT                        , "Results"),
  GeomecStringTable::value_type(IDS_RG_TENSOR_COMPONENTS           , "Components"),
  GeomecStringTable::value_type(IDS_RC_NN                          , "NN"),
  GeomecStringTable::value_type(IDS_RC_EE                          , "EE"),
  GeomecStringTable::value_type(IDS_RC_DD                          , "DD"),
  GeomecStringTable::value_type(IDS_RC_EN                          , "EN"),
  GeomecStringTable::value_type(IDS_RC_ED                          , "ED"),
  GeomecStringTable::value_type(IDS_RC_ND                          , "ND"),
  GeomecStringTable::value_type(IDS_RG_EFFECTIVE                   , "Effective"),
  GeomecStringTable::value_type(IDS_RG_PRINC_MAX                   , "max"),
  GeomecStringTable::value_type(IDS_RG_PRINC_MED                   , "med"),
  GeomecStringTable::value_type(IDS_RG_PRINC_MIN                   , "min"),
  GeomecStringTable::value_type(IDS_RG_PRINC_DIR                   , "Principal Directions"),
  GeomecStringTable::value_type(IDS_RG_PORE_PRESSURE               , "Pore Pressure"),
  GeomecStringTable::value_type(IDS_RG_STRAIN                      , "Strains"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_DEPTH           , "Depth"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_MAX_EDGE        , "Max edge length"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_MEAN_EDGE       , "Average edge length"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_SURFACE         , "Area"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_VOLUME          , "Volume"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT                 , "Mesh results"),
  GeomecStringTable::value_type(IDS_RG_PLASTIC                     , "Plastic"),
  GeomecStringTable::value_type(IDS_RG_GAMMA                       , "Gammas"),
  GeomecStringTable::value_type(IDS_RC_GAMMA_VERTICAL              , "Gamma vertical"),
  GeomecStringTable::value_type(IDS_RC_GAMMA_MIN                   , "Gamma minimum"),
  GeomecStringTable::value_type(IDS_RC_GAMMA_MED                   , "Gamma intermediate"),
  GeomecStringTable::value_type(IDS_RC_GAMMA_MAX                   , "Gamma maximum"),
  GeomecStringTable::value_type(IDS_RC_GAMMA_VOLUME                , "Gamma volume"),
  GeomecStringTable::value_type(IDS_RC_VOLUME_AVERAGE              , "Volume Average"),
  GeomecStringTable::value_type(IDS_RC_SHEAR_CAPACITY              , "Shear capacity"),
  GeomecStringTable::value_type(IDS_RC_COMPACTION_CAPACITY         , "Compaction capacity"),
  GeomecStringTable::value_type(IDS_RG_INVARIANTS                  , "Invariants"),
  GeomecStringTable::value_type(IDS_RG_REGISTRY_RESULT             , "User defined results"),
  GeomecStringTable::value_type(IDS_RG_FILE_RESULT                 , "Derived result"),
  GeomecStringTable::value_type(IDS_EXPORT_RESULT                  , "Export results"),
  GeomecStringTable::value_type(IDS_NO_EXPORT_GEOMETRY_SELECTED    , "No formations or point set selected for export"),
  GeomecStringTable::value_type(IDS_NO_ANALYSIS_TYPE_SELECTED      , "No analysis type selected for export"),
  GeomecStringTable::value_type(IDS_NO_TIMESTEP_SELECTED           , "No depletion stage selected for export"),
  GeomecStringTable::value_type(IDS_NO_RESULT_SELECTED             , "No result selected. Do you want to export anyway?"),
  GeomecStringTable::value_type(IDS_TOO_MANY_WELL_PATHS_SELECTED   , "Too many well-paths selected"),
  GeomecStringTable::value_type(IDS_ELEMENTSET                     , "Elementset"),
  GeomecStringTable::value_type(IDS_MESH_IMPORT_FILTER             , "GoCAD Solid Files (*.so)|*.so|All Files (*.*)|*.*||"),
  GeomecStringTable::value_type(IDS_MESH_IMPORT_FILTER_JEWEL_EARTH , "GoCAD Solid Files (*.so,*.ts)|*.so; *.ts|All Files (*.*)|*.*||"),
  GeomecStringTable::value_type(IDS_VALUENAME_COORDINATE           , "Coordinates"),
  GeomecStringTable::value_type(IDS_RG_FAULT                       , "Faults and interfaces"),
  GeomecStringTable::value_type(IDS_RG_FAULT_DISPLACEMENT          , "Relative displacement"),
  GeomecStringTable::value_type(IDS_RC_FAULT_DILATATION            , "Dilatation"),
  GeomecStringTable::value_type(IDS_RG_FAULT_DISPLACEMENT_VECTOR   , "Vector"),
  GeomecStringTable::value_type(IDS_RG_FAULT_STRESS                , "Stresses"),
  GeomecStringTable::value_type(IDS_RC_NORMAL                      , "Normal"),
  GeomecStringTable::value_type(IDS_RC_FAULT_EFFECTIVE_STRESS      , "Effective"),
  GeomecStringTable::value_type(IDS_RG_DSTABOR                     , "Optimum mudweight"),
  GeomecStringTable::value_type(IDS_RG_SHEAR_STRESS                , "Shear"),
  GeomecStringTable::value_type(IDS_TREE_MESH_REGIONS              , "Mesh regions"),
  GeomecStringTable::value_type(IDS_UNIT_SI_VOLUME                 , "m3"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_VOLUME              , "ft3"),
  GeomecStringTable::value_type(IDS_UNIT_SI_AREA                   , "m2"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_AREA                , "ft2"),
  GeomecStringTable::value_type(IDS_COMPONENT_NOT_IN_RANGE_MIN_MAX , "Value exceeds the minimum or maximum boundary of the component. Min and max should be between %f and %f."),
  GeomecStringTable::value_type(IDS_COMPONENT_NOT_IN_RANGE_MIN     , "Value exceeds the minimum boundary of the component. The value should be greater than %f."),
  GeomecStringTable::value_type(IDS_COMPONENT_NOT_IN_RANGE_MAX     , "Value exceeds the maximum boundary of the component. The value should be lower than %f."),
  GeomecStringTable::value_type(IDS_ET_CREEP                       , "Creep"),
  GeomecStringTable::value_type(IDS_RG_CREEP                       , "Creep"),
  GeomecStringTable::value_type(IDS_SELECT_TWO_HORIZON             , "At least two horizons should be selected"),
  GeomecStringTable::value_type(IDS_ROCK_MATERIAL                  , "Rock material"),
  GeomecStringTable::value_type(IDS_CASING_GRADE                   , "Casing Grade"),
  GeomecStringTable::value_type(IDS_RG_DCASING                     , "DCasint"),
  GeomecStringTable::value_type(IDS_TREE_ANALYSIS_POINT            , "Analysis Points"),
  GeomecStringTable::value_type(IDS_TREE_ANALYSIS_POINTS           , "Analysis Points"),
  GeomecStringTable::value_type(ID_INDICATOR_MESH                  , "MESH"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_RESET              , "Reset TMD range"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_MARKERS            , "Markers"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_RANGE              , "Set graph ranges"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_FORMATION_LINES    , "Formation lines"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_COPY_DATA          , "Copy data to clipboard"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_CLEAR_LEFT         , "Clear left axis"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_CLEAR_RIGHT        , "Clear right axis"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_CLEAR_BOTTOM       , "Clear bottom axis"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_CLEAR_TOP          , "Clear top axis"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_PREFER_LEFT_AXIS   , "Prefer left axis"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_PREFER_RIGHT_AXIS  , "Prefer right axis"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_PREFER_BOTTOM_AXIS , "Prefer bottom axis"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_PREFER_TOP_AXIS    , "Prefer top axis"),
  GeomecStringTable::value_type(IDS_GRAPH_SCENE_TOGGLE_DEPTH_AXIS  , "Switch depth axes"),
  GeomecStringTable::value_type(IDS_ET_FAULT_PRESSURE              , "FaultPressure"),
  GeomecStringTable::value_type(IDS_ET_FAULT_PRESSURE_CHANGE       , "Dlt_FaultPressure"),
  GeomecStringTable::value_type(IDP_INSUFFICIENT_MEMORY_FOR_CALCULATION
                                                                   , "There might be insufficient memory to read the results after the analysis has finished. Are you sure you want to continue?"),
  GeomecStringTable::value_type(ID_MERGE_HORIZONS                  , "Merge horizons\nMerge Horizons"),
  GeomecStringTable::value_type(IDP_SUPERMODELLOCKED               , "This model contains a super-model. Super-models are locked in this version. The model can not be loaded."),
  GeomecStringTable::value_type(IDP_GWC_CHECK_CONTACT_DEPTH_FAIL   , "The contact depth must be smaller than or equal to the contact depth of the previous stage.\nThe contact depth must be larger than or equal to the contact depth of the next stage.\nThe contact depth must be inside the formation."),
  GeomecStringTable::value_type(ID_RAW_HORIZON_DATA                , "Show raw horizon data for gm2 files\nRaw Horizon Data"),
  GeomecStringTable::value_type(IDP_GWC_CHECK_TRANS_DEPTH_FAIL     , "The transition depth must be larger than or equal to the contact depth.\nThe transition depth must be within the formation."),
  GeomecStringTable::value_type(IDS_GWC_NO_MESH                    , "Note: Depth values will not be checked, because there is no mesh"),
  GeomecStringTable::value_type(ID_VIEW_SQUARE                     , "View with an exaggerated vertical scale\nExaggerate vertical scale"),
  GeomecStringTable::value_type(IDS_GWC_HAS_MESH                   , "(Depth values will be checked)"),
  GeomecStringTable::value_type(IDP_TOGGLE_TETRAHORIZON_MULTIPLE_SURFACES
                                                                   , "Horizons or faults with more than one surface attached can not be converted.\nFirst remove or merge surfaces."),
  GeomecStringTable::value_type(ID_VIEW_NORMAL                     , "View normally\nView Normally"),
  GeomecStringTable::value_type(IDP_CALC_TETRA_FAULTS_NOT_VALIDATED, "Faults were found in this model, used in a non-linear analysis. This functionality has not yet been validated.\n\nAre you sure you want to continue?"),
  GeomecStringTable::value_type(IDS_TOP_HORIZON                    , "Top horizon"),
  GeomecStringTable::value_type(IDS_BOTTOM_HORIZON                 , "Bottom horizon"),
  GeomecStringTable::value_type(ID_SET_MESH_TOLERANCE              , "Set tolerance for tetrahedron mesher\nTetrahedron Mesher Tolerance"),
  GeomecStringTable::value_type(ID_INDICATOR_COOR                  , "Coordinate"),
  GeomecStringTable::value_type(IDS_RC_T                           , "T"),
  GeomecStringTable::value_type(IDS_RC_N                           , "N"),
  GeomecStringTable::value_type(ID_MERGE_HORIZON2                  , "Merge horizons\nMerge horizons\n"),
  GeomecStringTable::value_type(IDS_RC_TT                          , "TT"),
  GeomecStringTable::value_type(IDS_RC_TD                          , "TD"),
  GeomecStringTable::value_type(IDS_RC_TN                          , "TN"),
  GeomecStringTable::value_type(IDS_CALC_DENSITIES                 , "Calculating densities from initial stresses..."),
  GeomecStringTable::value_type(IDP_CONFIRMCLEARANALYSISLOG        , "Are you sure you want to clear the log?"),
  GeomecStringTable::value_type(IDS_ANALYSISLOGFILTER              , "Log Files (*.log)|*.log|All Files (*.*)|*.*||"),
  GeomecStringTable::value_type(IDP_EXPORTANALYSISLOGFAIL          , "Failed to export the analysis log to the selected location."),
  GeomecStringTable::value_type(IDP_ERRORRUNAPP                    , "There was an error starting GEOMEC with the 2D model."),
  GeomecStringTable::value_type(IDS_MERGINGHORIZONS                , "Merging horizons..."),
  GeomecStringTable::value_type(IDP_CANNOTIMPORT2DXSECASCII        , "Could not import the file named '%1' as a 2D cross section with results.\nReason:\n%2"),
  GeomecStringTable::value_type(IDS_TREE_XSECTIONS2D               , "2D Results"),
  GeomecStringTable::value_type(IDS_2DXSEC_FILTER                  , "ASCII Files (*.txt, *.dat, *.xyz)|*.txt; *.dat; *.xyz|Excel Files (*.xls;*.xls*)|*.xls;*.xls*|All Files (*.*)|*.*||"),
  GeomecStringTable::value_type(IDP_CANNOTIMPORTPOINTSETFOR2D      , "A pointset can not be used for 2D results."),
  GeomecStringTable::value_type(IDS_RIGI_PARAM19                   , "KEDED"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM20                   , "KEDDN"),
  GeomecStringTable::value_type(IDS_RIGI_PARAM21                   , "KDNDN"),
  GeomecStringTable::value_type(IDP_CANNOTIMPORT2DXSECEXCEL        , "Could not import the file named '%1' as a 2D cross section with results."),
  GeomecStringTable::value_type(IDS_MESH_RESULT_SHAPE_FACTOR       , "ShapeFactor"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_SHAPE_FACTOR    , "Shape Factor"),
  GeomecStringTable::value_type(IDS_VALUENAME_CREEP_QR1            , "Activation energy, Q1/R"),
  GeomecStringTable::value_type(IDS_VALUENAME_CREEP_QR2            , "Activation energy, Q2/R"),
  GeomecStringTable::value_type(IDS_VALUENAME_TENSILE_STRETCH      , "Tensile stretch"),
  GeomecStringTable::value_type(IDS_ET_CREEP_QR1                   , "Q1R"),
  GeomecStringTable::value_type(IDS_ET_CREEP_QR2                   , "Q2R"),
  GeomecStringTable::value_type(IDS_ET_TENSILE_STRETCH             , "Gamma"),
  GeomecStringTable::value_type(IDS_KW_IN_NUMBERS                  , "Found a keyword while reading points or elements"),
  GeomecStringTable::value_type(IDS_UNEXPECTED_VALUE               , "Unexpected value"),
  GeomecStringTable::value_type(IDS_DIMKW_IN_ELEMENTSET            , "DIM keyword found in elementset"),
  GeomecStringTable::value_type(IDS_TYPE_NOT_SET                   , "Tag found before POINTSET or ELEMENTSET keyword"),
  GeomecStringTable::value_type(IDS_ELEMENTSKW_IN_POINTSET         , "ELEMENTS keyword found in pointset"),
  GeomecStringTable::value_type(IDS_ELEMENTSKW_BEFORE_POINTS       , "ELEMENTS keyword before points"),
  GeomecStringTable::value_type(IDS_ELEMENTSKW_BEFORE_POINTHEADERS , "ELEMENTS keyword before point headers"),
  GeomecStringTable::value_type(IDS_ELEMENTSKW_BEFORE_POINTSSTART  , "ELEMENTS keyword before start of points"),
  GeomecStringTable::value_type(IDS_SECOND_TYPE                    , "Second type (POINTSET or ELEMENTSET) definition encountered"),
  GeomecStringTable::value_type(IDS_SECOND_DIM                     , "Second DIM keyword"),
  GeomecStringTable::value_type(IDS_SECOND_UNIT                    , "Second UNIT keyword"),
  GeomecStringTable::value_type(IDS_UNIT_AFTER_POINTSKW            , "UNIT keyword after POINTS keyword in an elementset"),
  GeomecStringTable::value_type(IDS_SECOND_POINTSKW                , "Second POINTS keyword"),
  GeomecStringTable::value_type(IDS_POINTSKW_IN_POINTSET           , "POINTS keyword in a POINTSET"),
  GeomecStringTable::value_type(IDS_SECOND_ELEMENTSKW              , "Second ELEMENTS keyword"),
  GeomecStringTable::value_type(IDS_SECOND_ELEMENTTYPE             , "Second element type definition"),
  GeomecStringTable::value_type(IDS_ELEMENTTYPE_BEFORE_ELEMENTSKW  , "Element type definition before ELEMENTS keyword"),
  GeomecStringTable::value_type(IDS_UNEXPECTED_END                 , "Unexpected END keyword"),
  GeomecStringTable::value_type(IDS_INVALID_CONTENT                , "Invalid cell content"),
  GeomecStringTable::value_type(IDS_UNITKW_AFTER_POINTSKW          , "UNIT after POINTS"),
  GeomecStringTable::value_type(IDS_PACKAGE_NAME                   , "Finite Element Geomechanical package"),
  GeomecStringTable::value_type(IDS_COPYRIGHT                      , "Copyright © 2000 - 2020"),
  GeomecStringTable::value_type(IDS_SUPPORT                        , "For technical support: geomec@shell.com"),
  GeomecStringTable::value_type(IDS_FAULT_EFF_NORMAL_STRESS        , "Effective normal stress"),
  GeomecStringTable::value_type(IDS_FAULT_TOTAL_NORMAL_STRESS      , "Total normal stress"),
  GeomecStringTable::value_type(ID_CLOSE_MODEL                     , "Close Model\nClose the current model"),
  GeomecStringTable::value_type(ID_ANALYSIS_LINEAR_ANALYSIS_SETTINGS
                                                                   , "Edit linear analysis settings\nLinear Analysis Settings"),
  GeomecStringTable::value_type(IDS_ET_VECTOR_2D_N                 , "N"),
  GeomecStringTable::value_type(IDS_ET_VECTOR_2D_T                 , "Show full elements\nFull Elements"),
  GeomecStringTable::value_type(ID_FORMATIONFULL                   , "Show full formations\nFull Formations"),
  GeomecStringTable::value_type(IDS_ET_VECTOR_2D_Z                 , "Show element center points\nCenter Points"),
  GeomecStringTable::value_type(ID_FORMATIONCENTER                 , "Show element center points only\nElement Center Points"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_2D_TT                , "DD"),
  GeomecStringTable::value_type(ID_ANALYSIS_CLEARHISTORY           , "Clears the analysis history\nClear Analysis History"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_2D_ZZ                , "TT"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_2D_NN                , "NN"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_2D_TZ                , "TD"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_2D_ZN                , "TN"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_2D_TN                , "DN"),
  GeomecStringTable::value_type(IDP_NO_STRESS_SUPPORT              , "You are loading a model that has a pressure support defined on one or more of the outer faces, which is no longer supported.\n\nThese supports have been set to 'normally'."),
  GeomecStringTable::value_type(IDP_CONFIRMCLEARBRANCH             , "This will clear all calculated results. The analysis will have to be started from the initial stage.\n\nContinue?"),
  GeomecStringTable::value_type(IDP_CONVERTBRANCHTOTETRA           , "This is a branched project, containing results from a branch analysis. The result history will not be available in the converted model.\n\nContinue?"),
  GeomecStringTable::value_type(IDS_UNIT_SI_PERTEMPER              , "1/C"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_PERTEMPER           , "1/C"),
  GeomecStringTable::value_type(IDS_ET_THERMAL_EXPANSION           , "VolThermExp"),
  GeomecStringTable::value_type(ID_OIV_TUTORIAL                    , "Visualization tutorial\nVisualization tutorial"),
  GeomecStringTable::value_type(IDS_VALUENAME_THERMAL_EXPANSION    , "Volumetric Thermal Expansion"),
  GeomecStringTable::value_type(ID_VIEW_SMOOTH_RESULTS             , "Smoothen the results in the view and exported files\nSmoothen results"),
  GeomecStringTable::value_type(IDS_ET_TEMPERATURE                 , "Temperature"),
  GeomecStringTable::value_type(IDS_VALUENAME_TEMPERATURE          , "Temperature"),
  GeomecStringTable::value_type(IDS_UNIT_TEMPERATURE               , "C"),
  GeomecStringTable::value_type(IDS_COMPONENT_TEMPERATURE_GRADIENT , "Gradient"),
  GeomecStringTable::value_type(IDS_COMPONENT_TEMPERATURE_REPEATER , "Same as previous"),
  GeomecStringTable::value_type(IDS_RG_TEMPERATURE                 , "Temperature"),
  GeomecStringTable::value_type(IDS_ET_TEMPERATURE_CHANGE          , "Dlt_Temperature"),
  GeomecStringTable::value_type(IDS_COMPONENT_PRESSURE_MINIMUM     , "Minimum"),
  GeomecStringTable::value_type(IDS_COMPONENT_PRESSURE_MAXIMUM     , "Maximum"),
  GeomecStringTable::value_type(IDS_COMPONENT_PRESSURE_MAXGRADIENT , "Maximum with gradient"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_NORTHING        , "Northing"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_EASTING         , "Easting"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_NORTHING           , "Northing"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_EASTING            , "Easting"),
  GeomecStringTable::value_type(IDS_SECOND_DSTAGE                  , "Second DEPL.STAGES keyword"),
  GeomecStringTable::value_type(IDS_64_EDITION                     , "(64 bits Edition)"),
  GeomecStringTable::value_type(IDS_32_EDITION                     , "(32 bits Edition)"),
  GeomecStringTable::value_type(IDS_NO_OBJECTS_SELECTED            , "No objects selected"),
  GeomecStringTable::value_type(IDS_ET_ELASTIC_HARDENING           , "ElasticHardening"),
  GeomecStringTable::value_type(IDS_VALUENAME_ELASTIC_HARDENING    , "Elastic Hardening Coefficient"),
  GeomecStringTable::value_type(ID_ANALYSIS_HEAT_FLOW              , "Perform a heat flow analysis\nHeat Flow Analysis"),
  GeomecStringTable::value_type(IDS_ET_SEC_PRECON                  , "SecondaryPreconsolidation"),
  GeomecStringTable::value_type(IDS_VALUENAME_SEC_PRECON           , "Secondary Preconsolidation Stress"),
  GeomecStringTable::value_type(IDS_ET_SEC_HARDENING               , "SecondaryHardening"),
  GeomecStringTable::value_type(IDS_VALUENAME_SEC_HARDENING        , "Secondary Hardening Parameter"),
  GeomecStringTable::value_type(IDS_RG_PRINC_STRESS                , "Principal Stresses"),
  GeomecStringTable::value_type(IDS_ET_FAULT_SHEAR_STRESS_CHANGE   , "Dlt_FaultStressShearL"),
  GeomecStringTable::value_type(IDP_CONFIRM_REPLACE_INITIAL_MATERIAL_MODEL
                                                                   , "The material model or locked parameter values of the dropped material differ from the subsequent material models. If you continue all subsequent materials will be removed.\n\nContinue?"),
  GeomecStringTable::value_type(IDS_CONSOL                         , "Consolidation Pressure"),
  GeomecStringTable::value_type(IDS_ET_CONSOL                      , "Consolidation"),
  GeomecStringTable::value_type(IDS_RG_CONSOL                      , "Consolidation Pressure"),
  GeomecStringTable::value_type(IDS_ET_CONSOL_CHANGE               , "Dlt_Consolidation"),
  GeomecStringTable::value_type(IDS_RG_POROSITY                    , "Porosity"),
  GeomecStringTable::value_type(IDS_ET_POROSITY_RES                , "PorosityRes"),
  GeomecStringTable::value_type(IDS_ET_POROSITY_RES_CHANGE         , "Dlt_PorosityRes"),
  GeomecStringTable::value_type(IDP_INVALIDATEIMPORTEDMESH         , "Are you sure you want to invalidate the imported mesh?\n\nAlthough a new mesh can be generated, the imported mesh can not be retrieved."),
  GeomecStringTable::value_type(IDS_RG_STRESSRATIOS                , "Stress ratios"),
  GeomecStringTable::value_type(IDS_ET_STRESSRATIOS                , "StressRatios"),
  GeomecStringTable::value_type(IDS_RC_SHTOTAZIMUTH                , "SHtot azimuth"),
  GeomecStringTable::value_type(IDS_ET_SHTOTAZIMUTH                , "SHtotAzimuth"),
  GeomecStringTable::value_type(IDS_RC_SHTOT_SVTOT                 , "SHtot / Svtot"),
  GeomecStringTable::value_type(IDS_ET_SHTOT_SVTOT                 , "SHtot/Svtot"),
  GeomecStringTable::value_type(IDS_RC_S_HTOT_SVTOT                , "Shtot / Svtot"),
  GeomecStringTable::value_type(IDS_ET_S_HTOT_SVTOT                , "Shtot/Svtot"),
  GeomecStringTable::value_type(IDS_ET_ELASCOMPRES                 , "UniaxialElasticCompressibility"),
  GeomecStringTable::value_type(IDS_ET_PLASCOMPRES                 , "UniaxialPlasticCompressibility"),
  GeomecStringTable::value_type(IDS_VALUENAME_ELASCOMPRES          , "Uniaxial Elastic Compressibility"),
  GeomecStringTable::value_type(IDS_VALUENAME_PLASCOMPRES          , "Uniaxial Plastic Compressibility"),
  GeomecStringTable::value_type(IDS_UNIT_SI_PERSTRESS              , "1/MPa"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_PERSTRESS           , "1/psi"),
  GeomecStringTable::value_type(IDS_MEASURED_TOP_DISPL_N           , "Measured Top Displacement N"),
  GeomecStringTable::value_type(IDS_MEASURED_TOP_DISPL_E           , "Measured Top Displacement E"),
  GeomecStringTable::value_type(IDS_MEASURED_TOP_DISPL_D           , "Measured Top Displacement D"),
  GeomecStringTable::value_type(IDS_RETRIEVE_HEAT_RESULTS          , "Retrieving heat transfer results"),
  GeomecStringTable::value_type(IDS_ANALYSISTYPE                   , "Analysis Type"),
  GeomecStringTable::value_type(ID_INDICATOR_HEAT                  , "HEAT"),
  GeomecStringTable::value_type(ID_INDICATOR_MIXTURE               , "MIX"),
  GeomecStringTable::value_type(ID_START_GVT                       , "Start a GVT Analysis"),
  GeomecStringTable::value_type(ID_ANALYSIS_MIXTURE                , "Perform a mixture analysis\nMixture Analysis"),
  GeomecStringTable::value_type(IDS_ET_FORMATIONTHICKNESS          , "FormationThickness"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_FORMATION_THICKNESS
                                                                   , "Formation Thickness"),
  GeomecStringTable::value_type(IDS_ET_FAULT_PLASTIC_SLIP          , "FaultPlasticSlip"),
  GeomecStringTable::value_type(IDS_RG_FAULT_PLASTIC_SLIP          , "Plastic Slip"),
  GeomecStringTable::value_type(IDS_RG_FAULT_PLASTIC_SLIP_VECTOR   , "Vector"),
  GeomecStringTable::value_type(ID_INVALIDATERESULTS_ALL           , "Invalidate all results\nInvalidate all results"),
  GeomecStringTable::value_type(ID_INVALIDATERESULTS_LINEAR        , "Invalidate linear results\nInvalidate linear results"),
  GeomecStringTable::value_type(ID_INVALIDATERESULTS_NONLINEAR     , "Invalidate non-linear results\nInvalidate non-linear results"),
  GeomecStringTable::value_type(ID_INVALIDATERESULTS_HEATFLOW      , "Invalidate heat flow results\nInvalidate heat flow results"),
  GeomecStringTable::value_type(ID_INVALIDATERESULTS_MIXTURE       , "Invalidate mixture results\nInvalidate mixture results"),
  GeomecStringTable::value_type(IDS_RETRIEVE_MIXTURE_RESULTS       , "Retrieving mixture results"),

  GeomecStringTable::value_type(IDS_TREE_EXPORT_MACROS             , "Export macros"),

  GeomecStringTable::value_type(IDS_RG_FRACTURE_MATRIX_PRESSURE    , "Fracture Matrix Pressure"),
  GeomecStringTable::value_type(IDS_ET_FRACTURE_MATRIX_PRESSURE    , "FractureMatrixPressure"),
  GeomecStringTable::value_type(IDS_ET_FRACTURE_MATRIX_PRESSURE_CHANGE
                                                                   , "Dlt_FractureMatrixPressure"),
  GeomecStringTable::value_type(IDS_RG_PRESSURE                    , "Pressure"),

  GeomecStringTable::value_type(ID_VIEW_MANUALREDRAW               , "Perform a manual redraw\nManual Redraw"),
  GeomecStringTable::value_type(ID_VIEW_USEMANUALREDRAWING         , "Use manual redrawing\nUse Manual Redrawing"),
  GeomecStringTable::value_type(ID_VIEW_ALLOWREDRAWING             , "Allow redrawing\nAllow Redrawing"),
  GeomecStringTable::value_type(ID_VIEW_AUTOMATICALLYDISABLEREDRAWING
                                                                   , "Automatically disable redrawing when view contents change\nAutomatically Disable Redrawing"),
  GeomecStringTable::value_type(ID_VIEW_REFRESHVIEW                , "Refresh the current view\nRefresh View"),
  GeomecStringTable::value_type(ID_FILE_MODELSUMMARY               , "Displays a summary of the current model\nModel Summary"),
  GeomecStringTable::value_type(ID_VIEW_STICKTOVIEW                , "Stick to the current view\nStick To View"),
  GeomecStringTable::value_type(ID_EXPORTCOMMANDFILESWITHDEFAULTS  , "Export command files with defaults\nExport Command Files With Defaults"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_APERTUREPARAM     , "ApertureParameter"),
  GeomecStringTable::value_type(IDS_VALUENAME_REFERENCESTRESS      , "Reference Stress"),
  GeomecStringTable::value_type(IDS_VALUENAME_APERTUREPARAM        , "Aperture Parameter"),
  GeomecStringTable::value_type(IDS_ET_CASINGINTERNALTEMPERATURE   , "CasingInternalTemperature"),
  GeomecStringTable::value_type(IDS_ET_CASINGINTERNALPRESSURE      , "CasingInternalPressure"),
  GeomecStringTable::value_type(IDP_LOAD_FRACTURE_APERTURE_LOCKED  , "The Fracture Aperture material model is locked in this version. The model you are loading contains Fracture Aperture material. The material(s) will be removed from the formation(s)"),
  GeomecStringTable::value_type(IDS_RG_RTCI                        , "RTCI"),
  GeomecStringTable::value_type(IDS_TREE_NEW_WELLPATHS             , "Wellpaths (ps)"),
  GeomecStringTable::value_type(IDS_RG_SURFACESTRESS               , "Surface Stress"),
  GeomecStringTable::value_type(IDS_RC_SHEAR_PLANE                 , "In-plane shear stress"),
  GeomecStringTable::value_type(IDS_RC_SHEAR_DIP_ANGLE             , "Shear stress angle with dip"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_GRAINSTIFFNESS    , "GrainBulkModulus"),
  GeomecStringTable::value_type(IDS_VALUENAME_GRAINSTIFFNESS       , "Grain Bulk Modulus"),
  GeomecStringTable::value_type(IDS_VALUENAME_YOUNGMODULUS_NORM_DECOMP
                                                                   , "Young's Modulus normal in decompaction"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_YOUNGMODULUS_NORM_DECOMP
                                                                   , "YoungModulusNormDecomp"),
  GeomecStringTable::value_type(IDS_VALUENAME_YOUNGMODULUS_TRANS_DECOMP
                                                                   , "Young's Modulus transverse in decompaction"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_YOUNGMODULUS_TRANS_DECOMP
                                                                   , "YoungModulusTransDecomp"),
  GeomecStringTable::value_type(IDS_VALUENAME_POISSONRATIO_NORM_DECOMP
                                                                   , "Poisson's Ratio normal in decompaction"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_POISSONRATIO_NORM_DECOMP
                                                                   , "PoissonRatioNormDecomp"),
  GeomecStringTable::value_type(IDS_VALUENAME_POISSONRATIO_TRANS_DECOMP
                                                                   , "Poisson's Ratio transverse in decompaction"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_POISSONRATIO_TRANS_DECOMP
                                                                   , "PoissonRatioTransDecomp"),
  GeomecStringTable::value_type(IDS_VALUENAME_SHEARMODULUS_DECOMP  , "Shear Modulus in decompaction"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_SHEARMODULUS_DECOMP
                                                                   , "ShearModulusDecomp"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_ANISOTROPIC_SHEARMODULUS
                                                                   , "AnisotropicShearModulus"),
  GeomecStringTable::value_type(IDS_VALUENAME_ANISOTROPIC_SHEARMODULUS
                                                                   , "Anisotropic Shear Modulus"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_ANISOTROPIC_SHEARMODULUS_DECOMP
                                                                   , "AnisotropicShearModulusDecomp"),
  GeomecStringTable::value_type(IDS_VALUENAME_ANISOTROPIC_SHEARMODULUS_DECOMP
                                                                   , "Anisotropic Shear Modulus in decompaction"),
  GeomecStringTable::value_type(IDS_DIANAX                         , "DianaX Control"),
  GeomecStringTable::value_type(IDS_DIANAX_PPG                     , "DianaX Property Page"),
  GeomecStringTable::value_type(IDS_TREE_FAULTS_FRACTURES          , "Faults & Fractures"),
  GeomecStringTable::value_type(IDS_DIANAX_PPG_CAPTION             , "General"),
  GeomecStringTable::value_type(IDP_CONFIRM_STOP                   , "Do you really want to stop?"),
  GeomecStringTable::value_type(IDS_VALUENAME_THOMSEN_EPSILON      , "Thomsen Epsilon"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_THOMSEN_EPSILON   , "ThomsenEpsilon"),
  GeomecStringTable::value_type(IDS_VALUENAME_THOMSEN_GAMMA        , "Thomsen Gamma"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_THOMSEN_GAMMA     , "ThomsenGamma"),
  GeomecStringTable::value_type(IDS_VALUENAME_THOMSEN_DELTA        , "Thomsen Delta"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_THOMSEN_DELTA     , "ThomsenDelta"),
  GeomecStringTable::value_type(IDS_VALUENAME_ANISOTROPIC_VP       , "Anisotropic Vp"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_ANISOTROPIC_VP    , "AnisotropicVp"),
  GeomecStringTable::value_type(IDS_VALUENAME_ANISOTROPIC_VS       , "Anisotropic Vs"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_ANISOTROPIC_VS    , "AnisotropicVs"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_V0_ME             , "V0Interm"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_V0_LO             , "V0Low"),
  GeomecStringTable::value_type(IDS_ET_APERTURE_HI_CHANGE          , "Dlt_V0High"),
  GeomecStringTable::value_type(IDS_ET_APERTURE_ME_CHANGE          , "Dlt_V0Interm"),
  GeomecStringTable::value_type(IDS_ET_APERTURE_LO_CHANGE          , "Dlt_V0Low"),
  GeomecStringTable::value_type(IDS_RG_FRACTURE_APERTURE           , "Fracture Aperture"),
  GeomecStringTable::value_type(IDS_APERTURE_HI                    , "Aperture in highest fracture density direction"),
  GeomecStringTable::value_type(IDS_VALUENAME_V0_HI                , "V0 in highest fracture density direction"),
  GeomecStringTable::value_type(IDS_VALUENAME_V0_ME                , "V0 in intermediate fracture density direction"),
  GeomecStringTable::value_type(IDS_VALUENAME_V0_LO                , "V0 in lowest fracture density direction"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_V0_HI             , "V0High"),
  GeomecStringTable::value_type(IDS_APERTURE_ME                    , "Aperture in intermediate fracture density direction"),
  GeomecStringTable::value_type(IDS_APERTURE_LO                    , "Aperture in lowest fracture density direction"),
  GeomecStringTable::value_type(IDS_ET_APERTURE_HI                 , "ApertureHigh"),
  GeomecStringTable::value_type(IDS_ET_APERTURE_ME                 , "ApertureInterm"),
  GeomecStringTable::value_type(IDS_ET_APERTURE_LO                 , "ApertureLow"),
  GeomecStringTable::value_type(IDS_RG_PERMEABILITY_MULTIPLIER     , "Permeability Multiplier"),
  GeomecStringTable::value_type(IDS_PERMEABILITY_MULTIPLIER_HI     , "Permeability Multiplier in highest fracture density direction"),
  GeomecStringTable::value_type(IDS_PERMEABILITY_MULTIPLIER_ME     , "Permeability Multiplier in intermediate fracture density direction"),
  GeomecStringTable::value_type(IDS_PERMEABILITY_MULTIPLIER_LO     , "Permeability Multiplier in lowest fracture density direction"),
  GeomecStringTable::value_type(IDS_ET_PERMEABILITY_MULTIPLIER_HI  , "PermeabilityMultiplierHigh"),
  GeomecStringTable::value_type(IDS_ET_PERMEABILITY_MULTIPLIER_ME  , "PermeabilityMultiplierInterm"),
  GeomecStringTable::value_type(IDS_ET_PERMEABILITY_MULTIPLIER_LO  , "PermeabilityMultiplierLow"),
  GeomecStringTable::value_type(IDS_VALUENAME_REFERENCE_APERTURE   , "Reference Aperture"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_REFERENCE_APERTURE, "ReferenceAperture"),
  GeomecStringTable::value_type(IDS_VALUENAME_DYNUNISTIFFNESS      , "Dynamic Uniaxial Stiffness"),
  GeomecStringTable::value_type(IDS_ET_DYNUNISTIFFNESS             , "DynamicUniaxialStiffness"),
  GeomecStringTable::value_type(IDS_VALUENAME_DYNSHEARSTIFFNESS    , "Dynamic Shear Stiffness"),
  GeomecStringTable::value_type(IDS_ET_DYNSHEARSTIFFNESS           , "DynamicShearStiffness"),
  GeomecStringTable::value_type(IDS_ET_VALUETYPE_CREEP_ALPHA       , "CreepAlpha"),
  GeomecStringTable::value_type(IDS_VALUENAME_CREEP_ALPHA          , "Creep Alpha"),
  GeomecStringTable::value_type(IDS_VALUENAME_DUMMY                , "Dummy"),
  GeomecStringTable::value_type(IDS_ET_DUMMY                       , "Dummy"),
  GeomecStringTable::value_type(IDS_VALUENAME_NRMSTRESS            , "Normal Stress"),
  GeomecStringTable::value_type(IDS_ET_NRMSTRESS                   , "NormalStress"),
  GeomecStringTable::value_type(IDS_VALUENAME_MEANSTRESS           , "Mean Stress"),
  GeomecStringTable::value_type(IDS_ET_MEANSTRESS                  , "MeanStress"),
  GeomecStringTable::value_type(IDS_VALUENAME_TIMESTRAIN           , "Time Strain"),
  GeomecStringTable::value_type(IDS_ET_TIMESTRAIN                  , "TimeStrain"),
  GeomecStringTable::value_type(IDS_VALUENAME_DELTAV               , "Delta v"),
  GeomecStringTable::value_type(IDS_ET_DELTAV                      , "DeltaV"),
  GeomecStringTable::value_type(IDS_VALUENAME_DELTAT               , "Delta t"),
  GeomecStringTable::value_type(IDS_ET_DELTAT                      , "DeltaT"),
  GeomecStringTable::value_type(IDS_VALUENAME_DISPLACEMENTZ        , "Displacement Z"),
  GeomecStringTable::value_type(IDS_ET_DISPLACEMENTZ               , "DisplacementZ"),

  GeomecStringTable::value_type(AFX_IDS_IDLEMESSAGE                , "For Help, press F1"),
  GeomecStringTable::value_type(IDS_PETRELIMPORT                   , "Import From Petrel"),
  GeomecStringTable::value_type(IDS_RG_PLASTIC_ENERGY              , "Plastic Energy"),
  GeomecStringTable::value_type(IDS_ET_PLASTIC_ENERGY              , "PlasticEnergy"),
  GeomecStringTable::value_type(IDS_UNIT_SI_ENERGY                 , "MJ/m3"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_ENERGY              , "lbin/in3"),
  GeomecStringTable::value_type(IDS_RG_FAULT_PLASTIC_ENERGY        , "Fault Plastic Energy"),
  GeomecStringTable::value_type(IDS_ET_FAULT_PLASTIC_ENERGY        , "FaultPlasticEnergy"),
  GeomecStringTable::value_type(IDS_UNIT_SI_FAULT_PLASTIC_ENERGY   , "MJ/m2"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_FAULT_PLASTIC_ENERGY, "lbft/in2"),
  GeomecStringTable::value_type(IDS_RG_VERTICALSTRESSGRADIENT      , "Vertical stress gradient"),
  GeomecStringTable::value_type(IDS_RC_VONMIS_GRADIENT             , "Von Mises stress gradient"),
  GeomecStringTable::value_type(IDS_RC_MEANSTR_GRADIENT            , "Mean stress gradient"),
  GeomecStringTable::value_type(IDS_RC_VERTICALSTRESSGRADIENT      , "Vertical stress gradient"),
  GeomecStringTable::value_type(IDS_RG_GRADIENT                    , "Gradient"),
  GeomecStringTable::value_type(IDS_ET_PORE_PRESSURE_GRADIENT      , "Pore pressure gradient"),
  GeomecStringTable::value_type(IDS_ET_TEMPERATURE_GRADIENT        , "Temperature gradient"),
  GeomecStringTable::value_type(IDS_UNIT_SI_TEMPERATUREGRADIENT    , "C/m"),
  GeomecStringTable::value_type(IDS_UNIT_FIELD_TEMPERATUREGRADIENT , "C/ft"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_VON_MISES_GRADIENT, "InvVonMisesGradient"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_INV_MEAN_GRADIENT    , "InvMeanGradient"),
  GeomecStringTable::value_type(IDS_VALUENAME_FAULT_PRESSURE       , "Fault Pressure"),
  GeomecStringTable::value_type(IDS_ERROR					       , "_E_R_R_O_R"),
  GeomecStringTable::value_type(IDS_ET_TENSOR_FT				   , "Full_Tensor"),
  GeomecStringTable::value_type(IDS_RG_INPUT                       , "Input"),
  GeomecStringTable::value_type(IDS_RG_OUTPUT                      , "Output"),
  GeomecStringTable::value_type(IDS_ET_VOLUMETRICSTRAIN_CHANGE     , "VolumetricStrainChange"),
  GeomecStringTable::value_type(IDS_CHECK_FOR_ANALYSIS_WARNING     , "This model contains branches and/or phases.\n\nIf you run in %1 mode, only parameters from the initial stage (%2)\nare used. Parameter changes are ignored.\n\n"),
  GeomecStringTable::value_type(IDS_CHECK_FOR_ANALYSIS_QUESTION    , "Is this what you want?"),
  GeomecStringTable::value_type(IDS_CONSISTENCY_GUARD              , "Model consistency"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_AHD             , "Along hole depth"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_AHD                , "AHD"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_AZIMUTH         , "Azimuth"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_AZIMUTH            , "Azimuth"),
  GeomecStringTable::value_type(IDS_RG_MESH_RESULT_INCLINATION     , "Inclination"),
  GeomecStringTable::value_type(IDS_MESH_RESULT_INCLINATION        , "Inclination"),
  GeomecStringTable::value_type(IDS_VALUENAME_GVT_FACTOR_R_C       , "FactorR C"),
  GeomecStringTable::value_type(IDS_ET_GVT_FACTOR_R_C              , "FactorR_C"),
  GeomecStringTable::value_type(IDS_VALUENAME_GVT_FACTOR_R_EX      , "FactorR EX"),
  GeomecStringTable::value_type(IDS_ET_GVT_FACTOR_R_EX             , "FactorR_EX"),
  GeomecStringTable::value_type(IDS_VALUENAME_GVT_FACTOR_S_NB      , "FactorS NB"),
  GeomecStringTable::value_type(IDS_ET_GVT_FACTOR_S_NB             , "FactorS_NB"),
  GeomecStringTable::value_type(IDS_VALUENAME_GVT_FACTOR_S_S       , "FactorS S"),
  GeomecStringTable::value_type(IDS_ET_GVT_FACTOR_S_S              , "FactorS_S"),
  GeomecStringTable::value_type(IDS_RG_CYLINDRICAL                 , "Cylindrical"),
  GeomecStringTable::value_type(IDS_RC_RADIAL                      , "Radial"),
  GeomecStringTable::value_type(IDS_RC_TANGENTIAL                  , "Tangential"),
  GeomecStringTable::value_type(IDS_RG_BOUNDARY_INPUT              , "Boundary"),
  GeomecStringTable::value_type(IDS_RG_PARENT_STRESS               , "Parent Stress"),
  GeomecStringTable::value_type(IDS_VALUENAME_KRAD                 , "Krad"),
  GeomecStringTable::value_type(IDS_ET_KRAD                        , "Krad"),
  GeomecStringTable::value_type(IDS_VALUENAME_KTAN                 , "Ktan"),
  GeomecStringTable::value_type(IDS_ET_KTAN                        , "Ktan"),
  GeomecStringTable::value_type(IDS_ET_PARENT_STRESS               , "ParentStress"),
  GeomecStringTable::value_type(IDS_ET_PARENT_EFFECTIVE            , "ParentEffectiveStress"),
  GeomecStringTable::value_type(IDS_ET_PARENT_EFFECTIVE_CHANGE     , "ParentEffectiveStressChange"),
  GeomecStringTable::value_type(IDS_ET_BOUNDARY_DISPLACEMENT       , "ParentDisplacement"),
  GeomecStringTable::value_type(IDS_ET_BOUNDARY_PRESSURE           , "ParentPressure"),
  GeomecStringTable::value_type(IDS_RG_BOUNDARY_DISPLACEMENT       , "Parent Displacement"),
  GeomecStringTable::value_type(IDS_RG_BOUNDARY_PRESSURE           , "Parent Pressure"),
};

const int elements = sizeof(rawData) / sizeof(rawData[0]);
static GeomecStringTable geomecStringTable(rawData, rawData + elements);

} // anonymous namespace

const char *getStringTableEntry(unsigned int stringTableEntry)
{
  GeomecStringTable::const_iterator iterator = geomecStringTable.find(stringTableEntry);

  if (iterator != geomecStringTable.end())
  return iterator->second;

  assert(false);
  return 0;
}

//QString getStringTableEntry(unsigned int stringTableEntry)
//{
//  return getStringTableEntryRaw(stringTableEntry);
//}
