#if !defined(AFX_FGVVIEW_H__DD1E0DBD_738D_42F0_B050_6792D6AB7776__INCLUDED_)
#define AFX_FGVVIEW_H__DD1E0DBD_738D_42F0_B050_6792D6AB7776__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFgvView wrapper class

//##ModelId=3DDA0C5401E7
class CFgvView : public CWnd
{
protected:
	DECLARE_DYNCREATE(CFgvView)
public:
	//##ModelId=3DDA0C5401E9
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd95e68a6, 0x5004, 0x11d2, { 0xb4, 0x6c, 0x0, 0x60, 0x97, 0x49, 0x2f, 0xd7 } };
		return clsid;
	}
	//##ModelId=3DDA0C5401F7
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

	//##ModelId=3DDA0C540200
    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	//##ModelId=3DDA0C540209
	CString GetFgvFileName();
	//##ModelId=3DDA0C54020A
	void SetFgvFileName(LPCTSTR);
	//##ModelId=3DDA0C54020C
	BOOL GetShowModel();
	//##ModelId=3DDA0C54020D
	void SetShowModel(BOOL);
	//##ModelId=3DDA0C54020F
	BOOL GetShowFrame();
	//##ModelId=3DDA0C540210
	void SetShowFrame(BOOL);
	//##ModelId=3DDA0C540216
	BOOL GetShowTableHeaders();
	//##ModelId=3DDA0C540217
	void SetShowTableHeaders(BOOL);
	//##ModelId=3DDA0C540219
	BOOL GetShowTableContents();
	//##ModelId=3DDA0C54021A
	void SetShowTableContents(BOOL);
	//##ModelId=3DDA0C54021C
	BOOL GetShowResults();
	//##ModelId=3DDA0C54021D
	void SetShowResults(BOOL);
	//##ModelId=3DDA0C54021F
	BOOL GetShowContourLegend();
	//##ModelId=3DDA0C540226
	void SetShowContourLegend(BOOL);
	//##ModelId=3DDA0C540228
	BOOL GetShowResultsMonitor();
	//##ModelId=3DDA0C540229
	void SetShowResultsMonitor(BOOL);
	//##ModelId=3DDA0C54022B
	BOOL GetShowMeshLabels();
	//##ModelId=3DDA0C54022C
	void SetShowMeshLabels(BOOL);
	//##ModelId=3DDA0C54022E
	BOOL GetShowAxes();
	//##ModelId=3DDA0C54022F
	void SetShowAxes(BOOL);
	//##ModelId=3DDA0C540231
	BOOL GetShowStatusMonitor();
	//##ModelId=3DDA0C540235
	void SetShowStatusMonitor(BOOL);
	//##ModelId=3DDA0C540237
	BOOL GetShowAdded();
	//##ModelId=3DDA0C540238
	void SetShowAdded(BOOL);
	//##ModelId=3DDA0C54023A
	double GetFgvBorderRatio();
	//##ModelId=3DDA0C54023B
	void SetFgvBorderRatio(double);
	//##ModelId=3DDA0C54023D
	double GetZoomFactor();
	//##ModelId=3DDA0C54023E
	void SetZoomFactor(double);
	//##ModelId=3DDA0C540245
	double GetZoomCenterX();
	//##ModelId=3DDA0C540246
	void SetZoomCenterX(double);
	//##ModelId=3DDA0C540248
	double GetZoomCenterY();
	//##ModelId=3DDA0C540249
	void SetZoomCenterY(double);
	//##ModelId=3DDA0C54024B
	double GetFgvUnitsFactor();
	//##ModelId=3DDA0C54024C
	void SetFgvUnitsFactor(double);
	//##ModelId=3DDA0C54024E
	BOOL GetFgvWhiteBackground();
	//##ModelId=3DDA0C54024F
	void SetFgvWhiteBackground(BOOL);
	//##ModelId=3DDA0C540256
	BOOL GetDebug();
	//##ModelId=3DDA0C540257
	void SetDebug(BOOL);
	//##ModelId=3DDA0C540259
	long GetHDCWidth();
	//##ModelId=3DDA0C54025A
	void SetHDCWidth(long);
	//##ModelId=3DDA0C54025C
	BOOL GetShowContextMenu();
	//##ModelId=3DDA0C54025D
	void SetShowContextMenu(BOOL);
	//##ModelId=3DDA0C540264
	BOOL GetMirrorDrawing();
	//##ModelId=3DDA0C540265
	void SetMirrorDrawing(BOOL);
	//##ModelId=3DDA0C540267
	BOOL GetUseDefaultPallette();
	//##ModelId=3DDA0C540268
	void SetUseDefaultPallette(BOOL);

// Operations
public:
	//##ModelId=3DDA0C54026A
	void LoadPicture();
	//##ModelId=3DDA0C54026B
	void CopyToClipboard();
	//##ModelId=3DDA0C54026C
	void Refresh();
	//##ModelId=3DDA0C54026D
	double GetWidthHeightRatio();
	//##ModelId=3DDA0C540274
	void DrawToHDC(long hDC, const VARIANT& RelX, const VARIANT& RelY);
	//##ModelId=3DDA0C540278
	void ColorPalletteToUse(long Index);
	//##ModelId=3DDA0C54027A
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FGVVIEW_H__DD1E0DBD_738D_42F0_B050_6792D6AB7776__INCLUDED_)
