//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DSealect.rc
//
#define IDC_btnOK                       3
#define IDC_btnCancel                   4
#define IDD_ABOUTBOX                    100
#define IDD_DEFAULT_VIEW                101
#define IDD_Info                        101
#define IDD_DIALOGBAR                   103
#define IDD_DIALOGBAR_UNITS             103
#define IDC_BUTTON_NEXT                 106
#define IDC_BUTTON_PREVIOUS             107
#define IDC_BUTTON_HELP                 108
#define IDR_MAINFRAME                   128
#define IDR_DSEALETYPE                  129
#define IDR_MAINFRAME2                  129
#define IDI_ICGraphFolder               133
#define IDI_ICWildFolder37              135
#define IDI_ICAppsStop                  139
#define IDI_ICBeCardStack               140
#define IDI_ICBeEdit                    141
#define IDI_ICBeGenericFile             142
#define IDI_ICBeKaleidoscope            143
#define IDI_ICRecycling                 144
#define IDI_ICBeMagnify                 145
#define IDI_ICBeScript                  146
#define IDI_ICBeBounce                  147
#define IDI_ICCalculator3D              148
#define IDI_ICControlFolders            149
#define IDI_ICDropFolder                150
#define IDI_ICExpand                    152
#define IDI_ICPurpleTabFolder           153
#define IDI_ICShadedReports             154
#define IDI_ICSphere                    155
#define IDI_ICStonedFolder              156
#define IDI_ICSunburst                  157
#define IDI_ICTime                      158
#define IDI_ICTools                     159
#define IDI_ICWeight                    160
#define IDI_ICShadedUtilities           161
#define IDD_Formations                  162
#define IDD_FormationDefinition         163
#define IDD_InsituStresses              164
#define IDD_FormationProperties         165
#define IDI_ICTubeEmptyM                167
#define IDI_ICShieldM                   168
#define IDI_ICInkJet                    169
#define IDD_EditFormationMaterial       170
#define IDD_FormationLibrary            171
#define IDD_DrillingOperation           172
#define IDD_CasingOperation             173
#define IDD_EditCasingOperation         174
#define IDD_EditCasingMaterial          174
#define IDD_CasingLibrary               175
#define IDD_CasingStresses              176
#define IDD_CementingOperation          177
#define IDD_DepthsForAnalysis           178
#define IDD_CementProperties            179
#define IDD_EditCementMaterial          180
#define IDD_CementLibrary               181
#define IDD_CompletionAndTesting        182
#define IDD_ProductionAndInjection      183
#define IDD_ExtremeOperations           184
#define IDD_MeshRefinement              185
#define IDD_SteppingScheme              186
#define IDD_OutputSelection             187
#define IDD_Analysis                    188
#define IDD_ResultsOverview             189
#define IDD_DetailedResults             190
#define IDD_DrillingAndCompletion       191
#define IDD_DepthsCementsForAnalysis    192
#define IDD_OperationalRegimes          193
#define IDD_AnalysisControl             194
#define IDD_ResultsReport               195
#define IDI_ICON_DISABLE                196
#define IDI_ICON_ENABLE                 197
#define IDD_frmAddFormation             199
#define IDD_AddAnalysisPoint            200
#define IDI_ICON1                       202
#define IDI_DIANA                       203
#define IDI_ICON2                       204
#define IDB_SHELL_BITMAP                206
#define IDB_BITMAP_HALLIBURTON          207
#define IDI_ICOHalliburton              208
#define IDI_ICONShell                   209
#define IDI_ICOTNO                      210
#define IDB_BITMAP1                     214
#define IDB_SPLASH2                     217
#define IDD_SPLASH                      219
#define IDI_ICON3                       220
#define IDB_BITMAP3                     222
#define IDD_CalculationWindow           223
#define IDB_BITMAP2                     224
#define IDB_BITMAP4                     225
#define IDD_Options                     227
#define IDR_POPUPMENU_COPY              228
#define IDB_SPLASHWELL                  229
#define IDB_CASING_DEBONDING            230
#define IDB_FORMATION_DEBONDING         231
#define IDD_DIALOG1                     232
#define IDD_ImportSurvey                232
#define IDB_SPLASH                      233
#define IDD_FemgvProgress               234
#define IDD_DIALOG2                     235
#define IDD_TVDDataImport               235
#define IDC_BUTTON1                     1000
#define IDC_btnCalcTVD                  1000
#define IDS_OILPRODUCER                 1000
#define IDC_bttnStart                   1000
#define IDC_btnBrowseWorkDir            1000
#define IDC_btnBrowseTempDir            1000
#define IDC_ButtonImport                1000
#define IDC_ButtonImportPressure        1000
#define IDC_fraOnshoreDefinition        1001
#define IDC_btnSaveProject              1001
#define IDS_GASPRODUCER                 1001
#define IDC_btnBrowseFormLib            1001
#define IDC_ButtonImportDensity         1001
#define IDC_fraOffShoreDefinition       1002
#define IDC_btnReviewDiagnostic         1002
#define IDS_GASSTORAGE                  1002
#define IDC_btnBrowseCemLib             1002
#define IDC_ButtonImportTemperature     1002
#define IDC_optDefaultSteppingScheme    1003
#define IDC_fraDetailedResults          1003
#define IDS_WATERINJECTOR               1003
#define IDC_btnBrowseCasLib             1003
#define IDC_optOffshoreDefinition       1004
#define IDC_fraDrillingFluidWeight      1004
#define IDC_optRiskOfDamageBarChart     1004
#define IDS_STEAMINJECTOR               1004
#define IDC_ebNrOfTimeSteps             1005
#define IDS_THERMALWELL                 1005
#define IDC_ebCasingRefinementLevel     1006
#define IDS_WATERSOURCE                 1006
#define IDC_ebMaxNumberOfIterations     1007
#define IDS_COPYRIGHT                   1007
#define IDC_lstAnalysis                 1009
#define IDC_chkConversionToInjector     1010
#define IDC_chkConversion               1010
#define IDC_chkConversionToProjector    1011
#define IDC_lstCementLibraryParams      1011
#define IDC_chkSaveDiagnostic           1012
#define IDC_chkNoCalculationMonitoring  1013
#define IDC_ebSurfaceUndisturbedTemp    1013
#define IDC_ebGeothermalGradient        1014
#define IDC_ebAverageDensity            1015
#define IDC_ebGeothermalGradientF       1016
#define IDC_ebVerticalStressGradient    1017
#define IDC_ebMaxHorizontalStressRatio  1018
#define IDC_ebMinHorizontalStressRatio  1019
#define IDC_ebNumberOfCementScenarios   1022
#define IDC_ebBottomHoleFlowingTemp     1024
#define IDC_cmbIterationScheme          1024
#define IDC_optAdvancedOptionsForSteppingScheme 1025
#define IDC_optOverview3                1026
#define IDC_ebInjectionTemperature      1026
#define IDC_cmbConvergenceNorm          1026
#define IDC_ebTimeOfContinuousInjection 1027
#define IDC_cmbWellComponent            1027
#define IDC_optPresentResultAgainstLoadDamageTypes 1027
#define IDC_ebCompFractureEnergy        1028
#define IDC_sldRockRefinementLevel      1028
#define IDC_ebVolumetricShrinkage       1029
#define IDC_sldCasingRefinementLevel    1029
#define IDC_lbUMeanGroundLevel          1029
#define IDC_optPresentResultAgainstSpaceTime 1029
#define IDC_ebWorkStringPackersTMD      1030
#define IDC_sldCementRefinementLevel    1030
#define IDC_ebHydrationHeat             1030
#define IDC_ebNewFluidStressGrad        1031
#define IDC_ebNewFluidOverpressure      1032
#define IDC_cmbResultType               1032
#define IDC_ebNewFluidCompressibility   1033
#define IDC_cmbLoadType                 1033
#define IDC_ebTopOfCementTMD            1034
#define IDC_cmbPlotSpace                1034
#define IDC_lbUMeanSeaLevel             1034
#define IDC_lbUSeaBedTVD                1035
#define IDC_ebPressureFromFluidsAbove   1035
#define IDC_cmbTypeOfDamage             1035
#define IDC_lbUWaterDepth               1035
#define IDC_lbUOverburdenBottomTVD      1036
#define IDC_ebTopOfCementTVD            1036
#define IDC_lbUModelBottomTVD           1037
#define IDC_ebMeanGroundLevel           1038
#define IDC_lbUModelTopTVD              1039
#define IDC_ebModelBottomTVD            1041
#define IDC_ebOverburdenBottomTVD       1042
#define IDC_ebSeaBedTVD                 1043
#define IDC_ebWaterDepth                1043
#define IDC_ebMeanSeaLevel              1044
#define IDC_ebModelTopTVD               1045
#define IDC_optOnshoreDefinition        1046
#define IDC_btnAddFormation             1047
#define IDC_btnRemoveFormation          1048
#define IDC_btnHelp                     1049
#define IDC_btnNext                     1050
#define IDC_btnPrevious                 1051
#define IDC_btnRunAnalysis              1052
#define IDC_chkStopBatchRunIfDivergence 1053
#define IDC_chkAllowFurtherPostProcessing 1054
#define IDC_lbUPercentageEccentricity   1055
#define IDC_ebPercentageEccentricity    1056
#define IDC_ebGuideShoeDepth            1057
#define IDC_lbUGuideShoeDepth           1058
#define IDC_btnFromLibrary              1059
#define IDC_btnToLibrary                1060
#define IDC_btnEdit                     1061
#define IDC_btnNew                      1062
#define IDC_fraCementWeightAndPlacement 1063
#define IDC_fraAdvanced                 1064
#define IDC_optAutomatic                1065
#define IDC_optAdvanced                 1066
#define IDC_ebHookLoad                  1067
#define IDC_lbUHookLoad                 1068
#define IDC_fraCrossSectionalStresses   1069
#define IDC_fraNoWorkString             1070
#define IDC_optNoWorkString             1071
#define IDC_ebPorePressAtFormationTop   1072
#define IDC_lbUPorePressAtFormationTop  1073
#define IDC_ebAzimuthOfSHWithNorth      1074
#define IDC_lbUAzimuthOfSHWithNorth     1075
#define IDC_fraWorkStringUsed           1076
#define IDC_optWorkStringUsed           1077
#define IDC_ebDispFluidStressGrad       1078
#define IDC_lbUDispFluidStressGrad      1079
#define IDC_ebDispFluidCompressibility  1080
#define IDC_lbUDispFluidCompressibility 1081
#define IDC_lbUWorkStringPackersTMD     1082
#define IDC_lbUNewFluidStressGrad       1083
#define IDC_lbUNewFluidOverpressure     1084
#define IDC_lbUNewFluidCompressibility  1085
#define IDC_ebDispFluidOverpressure     1086
#define IDC_lbUPressureFromFluidsAbove  1087
#define IDC_lbUDispFluidOverpressure    1087
#define IDC_optLeadTailCementsYes       1088
#define IDC_ebTopOfTailCementTMD        1089
#define IDC_lbUTopOfTailCementTMD       1090
#define IDC_ebLeadCementStressGrad      1091
#define IDC_lbULeadCementStressGrad     1092
#define IDC_ebTailCementStressGrad      1093
#define IDC_lbUTailCementStressGrad     1094
#define IDC_optLeadTailCementsNo        1095
#define IDC_fraLeadTailCementsNo        1096
#define IDC_ebCementStressGradient      1097
#define IDC_lbUCementStressGradient     1098
#define IDC_fraLeadTailCementsYes       1099
#define IDC_lbLeadCementStressGrad      1100
#define IDC_cmbWellType                 1102
#define IDC_optBalancedCompletion       1103
#define IDC_optUnderbalancedCompletion  1104
#define IDC_optOverbalancedCompletion   1105
#define IDC_fraAnalysisPoint            1106
#define IDC_fraBottomHoleSituationPrior 1107
#define IDC_ebDrillingFluidTemperature  1108
#define IDC_lbUDrillingFluidTemperature 1109
#define IDC_ebTimeOfExposToTreatFluid   1110
#define IDC_lbUTimeOfExposToTreatFluid  1111
#define IDC_fraPressureTest             1112
#define IDC_ebTestPressure              1113
#define IDC_lbUTestPressure             1114
#define IDC_fraCompletion               1115
#define IDC_edPressureDifference        1116
#define IDC_ebPressureDifference        1116
#define IDC_lbUPressureDifference       1117
#define IDC_btnAddAnalysisPoint         1118
#define IDC_ebFluidPressureGradient     1118
#define IDC_btnRemoveAnalysisPoint      1119
#define IDC_lbUFluidPressureGradient    1119
#define IDC_cmbCementScenario           1120
#define IDC_fraCompareResults           1121
#define IDC_fraViewResults              1122
#define IDC_ebTMDAtOverburdenBottom     1123
#define IDC_lbUTMDAtOverburdenBottom    1124
#define IDC_ebWellInclination           1125
#define IDC_lbUWellInclination          1126
#define IDC_ebAzimuthWithNorth          1127
#define IDC_lbUAzimuthWithNorth         1128
#define IDC_ebBoreholeDiameter          1129
#define IDC_lbUBoreholeDiameter         1130
#define IDC_ebMudStressGradAtSurface    1131
#define IDC_lbUMudStressGradAtSurface   1132
#define IDC_edMudCompressibility        1133
#define IDC_ebMudCompressibility        1133
#define IDC_lbUMudCompressibility       1134
#define IDC_ebCasingType                1135
#define IDC_ebMudDensityAtSurface       1135
#define IDC_ebCasingOuterDiameter       1136
#define IDC_lbUMudDensityAtSurface      1136
#define IDC_lbUCasingOuterDiameter      1137
#define IDC_ebCasingInnerDiameter       1138
#define IDC_lbUCasingInnerDiameter      1139
#define IDC_ebYoungsModulus             1140
#define IDC_lbUYoungsModulus            1141
#define IDC_ebPoissonRatio              1142
#define IDC_lbUPoissonRatio             1143
#define IDC_ebVolumetricSpecificHeat    1144
#define IDC_lbUVolumetricSpecificHeat   1145
#define IDC_ebThermalConductivity       1146
#define IDC_lbUThermalConductivity      1147
#define IDC_ebThermalExpansion          1148
#define IDC_lbUThermalExpansion         1149
#define IDC_ebHardeningGradient         1150
#define IDC_lbUHardeningGradient        1151
#define IDC_ebFractureEnergy            1152
#define IDC_lbUFractureEnergy           1153
#define IDC_ebCementName                1154
#define IDC_ebDensity                   1154
#define IDC_ebTensileStrenght           1155
#define IDC_ebTensileStrength           1155
#define IDC_lbUDensity                  1155
#define IDC_lbUTensileStrenght          1156
#define IDC_ebTensFractureEnergy        1157
#define IDC_lbUTensFractureEnergy       1158
#define IDC_ebCohesion                  1159
#define IDC_lbUCohesion                 1160
#define IDC_ebFrictionAngle             1161
#define IDC_lbUFrictionAngle            1162
#define IDC_cmbCompHardeningType        1163
#define IDC_ebCompHardeningGradient     1164
#define IDC_lbUCompHardeningGradient    1165
#define IDC_lbUCompFractureEnergy       1166
#define IDC_lbUVolumetricShrinkage      1167
#define IDC_lbUHydrationHeat            1168
#define IDC_ebName                      1170
#define IDC_fraPlasticity               1171
#define IDC_chkPlasticity               1172
#define IDC_cmbHardeningType            1173
#define IDC_ebChosenWellType            1174
#define IDC_chkFracturingHighRateKilling 1175
#define IDC_chkEvacuationUnloading      1176
#define IDC_fraFracturingHighRateKilling 1177
#define IDC_fraEvacuationUnloading      1178
#define IDC_ebMaximumInjectionPressure  1179
#define IDC_lbUMaximumInjectionPressure 1180
#define IDC_ebTreatingFluidTemperature  1181
#define IDC_lbUTreatingFluidTemperature 1182
#define IDC_ebBottomHoleTreatingPres    1183
#define IDC_lbUBottomHoleTreatingPres   1184
#define IDC_ebTreatingFluidTemperatureEU 1185
#define IDC_lbUTreatingFluidTemperatureEU 1186
#define IDC_ebTimeOfExposToTreatFluidEU 1187
#define IDC_lbUTimeOfExposToTreatFluidEU 1188
#define IDC_fraOverburden               1189
#define IDC_lbUSurfaceUndisturbedTemp   1190
#define IDC_lbUGeothermalGradient       1191
#define IDC_lbUAverageDensity           1192
#define IDC_fraFormationInsituStresses  1193
#define IDC_lbUGeothermalGradientF      1194
#define IDC_lbUMaxHorizontalStressRatio 1196
#define IDC_lbUMinHorizontalStressRatio 1197
#define IDC_chkPorousFormation          1198
#define IDC_fraPorousFormation          1199
#define IDC_ebPorePressFormationBottom  1200
#define IDC_lbUPorePressFormationBottom 1201
#define IDC_optDefaultMeshRefinement    1202
#define IDC_optAdvancedTuningOfMeshRefinement 1203
#define IDC_fraAdvancedTuningOfMeshRefinement 1204
#define IDC_ebRockRefinementLevel       1205
#define IDC_ebCementRefinementLevel     1206
#define IDC_optOverview1                1207
#define IDC_optOverview2                1208
#define IDC_fraProduction               1209
#define IDC_fraInjection                1210
#define IDC_ebPorePressure              1211
#define IDC_lbUPorePressure             1212
#define IDC_ebBottomHoleFlowingPress    1213
#define IDC_lbUBottomHoleFlowingPress   1214
#define IDC_lbUBottomHoleFlowingTemp    1215
#define IDC_lbUInjectionTemperature     1216
#define IDC_lbUTimeOfContinuousInjection 1217
#define IDC_cmbDepthAlongWell           1218
#define IDC_optDamageStatusOverviewTable 1219
#define IDC_fraAdvancedOptionsForSteppingScheme 1220
#define IDC_lbNumberOfTimeSteps         1221
#define IDC_lbIterationScheme           1222
#define IDC_lbMaxNumberOfIterations     1223
#define IDC_lbConvergenceNorm           1224
#define IDC_lbPorePressure              1225
#define IDC_lbBottomHoleFlowingPress    1226
#define IDC_lbBottomHoleFlowingTemp     1227
#define IDC_lbTimeOfExposToTreatFluid   1228
#define IDC_lbMaximumInjectionPressure  1229
#define IDC_lbInjectionTemperature      1230
#define IDC_lbTimeOfContinuousInjection 1231
#define IDC_lbRockRefinementLevel       1232
#define IDC_lbCasingRefinementLevel     1233
#define IDC_lbCementRefinementLevel     1234
#define IDC_lbPorePressFormationBottom  1235
#define IDC_lbPorePressAtFormationTop   1236
#define IDC_lbAzimuthOfShWithNorth      1237
#define IDC_lbMinHorizontalStressRatio  1238
#define IDC_lbMaxHorizontalStressRatio  1239
#define IDC_lbVerticalStressGradient    1240
#define IDC_lbGeothermalGradientF       1241
#define IDC_lbAverageVerticalStressGrad 1242
#define IDC_lbAverageDensity            1242
#define IDC_lbGeothermalGradient        1243
#define IDC_lbSurfaceUndisturbedTemp    1244
#define IDC_lbModelBottomTVD            1245
#define IDC_lbOverburdenBottomTVD       1246
#define IDC_lbSeaBedTVD                 1247
#define IDC_lbWaterDepth                1247
#define IDC_lbMeanSeaLevel              1248
#define IDC_lbModelTopTVD               1249
#define IDC_lbMeanGroundlevel           1253
#define IDC_lbTimeOfExposToTreatFluidEU 1254
#define IDC_lbTreatingFluidTemperatureEU 1255
#define IDC_lbBottomHoleTreatingPres    1256
#define IDC_lbTreatingFluidTemperature  1257
#define IDC_lbCohesion                  1258
#define IDC_lbFrictionAngle             1259
#define IDC_lbHardeningGradient         1260
#define IDC_lbHardeningType             1261
#define IDC_lbFractureEnergy            1262
#define IDC_lbPlotSpace                 1263
#define IDC_lbLoadType                  1264
#define IDC_lbResultType                1265
#define IDC_lbDepthAlongWellResult      1266
#define IDC_lbCorrespondingCementMaterial 1267
#define IDC_lbCementScenario            1268
#define IDC_lbTopOfTailCementTMD        1269
#define IDC_lbTailCementStressGrad      1270
#define IDC_lbCementStressGradient      1271
#define IDC_lbHookLoad                  1272
#define IDC_lbDispFluidStressGrad       1273
#define IDC_lbDispFluidCompressibility  1274
#define IDC_lbWorkStringPackersTMD      1275
#define IDC_lbNewFluidStressGrad        1276
#define IDC_lbNewFluidOverpressure      1277
#define IDC_lbNewFluidCompressibility   1278
#define IDC_fraModelRange               1279
#define IDC_lbDispFluidOverpressure     1279
#define IDC_fraWellPathAboveModelRange  1280
#define IDC_fraWellPathWithinModelRange 1281
#define IDC_fraWellPathDefinition       1281
#define IDC_optDensityDefinition        1282
#define IDC_optStressGradientDefinition 1283
#define IDC_lbMudDensityAtSurface       1284
#define IDC_lbMudStressGradAtSurface    1285
#define IDC_lbPercentageEccentricity    1286
#define IDC_lbUWeightPerUnitLength      1288
#define IDC_lbUYieldStrength            1289
#define IDC_fraAxialStresses            1290
#define IDC_lbDispFluidStressGradientNWS 1291
#define IDC_lbDispFluidCompressibilityNWS 1292
#define IDC_optMud                      1293
#define IDC_optNewFluid                 1294
#define IDC_lbHydrationHeat             1295
#define IDC_fraFormationDefinition      1296
#define IDC_lstFormationDefinition      1297
#define IDC_lstFormationName            1298
#define IDC_lstFormationMaterial        1299
#define IDC_lstFormationMaterialParams  1300
#define IDC_fraEditFormationMaterial    1301
#define IDC_fraElasticity               1302
#define IDC_lbName                      1303
#define IDC_lbYoungsModulus             1304
#define IDC_lbPoissonRatio              1305
#define IDC_lbVolumetricSpecificHeat    1306
#define IDC_ThermalConductivity         1307
#define IDC_lbThermalExpansion          1308
#define IDC_lstFormationLibrary         1309
#define IDC_lbDensity                   1309
#define IDC_lbTMDAtOverburdenBottom     1311
#define IDC_lbWellInclination           1312
#define IDC_lbAzimuthWithNorth          1313
#define IDC_fraWellGeometry             1314
#define IDC_lbBoreholeDiameter          1315
#define IDC_lbMudCompressibility        1316
#define IDC_fraCasingPlacement          1317
#define IDC_lbGuideShoeDepth            1318
#define IDC_lstCasingParams             1319
#define IDC_fraCasingDetails            1320
#define IDC_lbCasingType                1321
#define IDC_lbCasingOuterDiameter       1322
#define IDC_lbCasingInnerDiameter       1323
#define IDC_lbThermalConductivity       1324
#define IDC_lbWeightPerUnitLength       1325
#define IDC_ebWeightPerUnitLength       1326
#define IDC_lbYieldStrength             1327
#define IDC_ebYieldStrength             1328
#define IDC_lstCasingLibrary            1329
#define IDC_lstCasingLibraryParams      1330
#define IDC_ebDispFluidStressGradientNWS 1331
#define IDC_lbUDispFluidStressGradientNWS 1332
#define IDC_ebDispFluidCompressibilityNWS 1333
#define IDC_lbUDispFluidCompressibilityNWS 1334
#define IDC_lbFluidInCasingWorkStringA  1335
#define IDC_fraNewFluid                 1336
#define IDC_lbTopOfCement               1337
#define IDC_lbTMD                       1338
#define IDC_lbTVD                       1339
#define IDC_lbPressureFromFluidsAbove   1340
#define IDC_lbEnterTheBottomLTY         1341
#define IDC_lbEnterTheBottomLTN         1342
#define IDC_fraAnalysisPointTMD         1343
#define IDC_lbTopOfCement2              1343
#define IDC_lstAnalysisPoint            1344
#define IDC_lbUAnalysisPointTMD         1345
#define IDC_lbNumberOfCementScenarios   1346
#define IDC_lbUNumberOfCementScenarios  1347
#define IDC_lbSelectCementToDisplay     1348
#define IDC_lstCementProperties         1349
#define IDC_lstCementPropertiesParams   1350
#define IDC_fraEditCementMaterial       1351
#define IDC_lbCementName                1352
#define IDC_lbTensileStrenght           1353
#define IDC_lbTensFractureEnergy        1354
#define IDC_lbCompHardeningType         1355
#define IDC_lbCompHardeningGradient     1356
#define IDC_lbCompFractureEnergy        1357
#define IDC_lbVolumetricShrinkage       1358
#define IDC_lstCementLibrary            1359
#define IDC_lbWellType                  1360
#define IDC_fraCompletionBalance        1361
#define IDC_lbSelectAnalysisPoint       1362
#define IDC_lstAnalysisPoints           1363
#define IDC_fraDrillingFluidTemperature 1364
#define IDC_lbTimeOfExposToDrilFluid    1365
#define IDC_ebTimeOfExposToDrilFluid    1366
#define IDC_lbUTimeOfExposToDrilFluid   1367
#define IDC_lbTestPressure              1368
#define IDC_lbPressureDifference        1369
#define IDC_lbChosenWellType            1370
#define IDC_lbTimeOfContinuousProd      1371
#define IDC_ebTimeOfContinuousProd      1372
#define IDC_lbUTimeOfContinuousProd     1373
#define IDC_lbSelectExtremeOperations   1374
#define IDC_lstselectAnalysisPoint      1375
#define IDC_lbUNumberOfTimeSteps        1376
#define IDC_lbUMaxNumberOfIterations    1377
#define IDC_fraSelectOutputLevel        1378
#define IDC_lbCheckBoxForSelectingBatchRuns 1379
#define IDC_fraCalculationOptions       1380
#define IDC_fraOptions                  1381
#define IDC_lbDepthAlongWell            1382
#define IDC_lbWellComponenet            1383
#define IDC_fraPresentation             1384
#define IDC_ebCorrespondingCementMaterial 1385
#define IDC_fraSelectVariationCase      1386
#define IDC_lbTypeOfDamage              1387
#define IDC_PICTURE                     1388
#define IDC_lbUTopOfCementsTMD          1391
#define IDC_lbUTopOfCementsTVD          1392
#define IDC_lbBottomTVD                 1394
#define IDC_lbFormationName             1395
#define IDC_ebBottomTVD                 1396
#define IDC_ebFormationName             1397
#define IDC_lbUBottomTVD                1398
#define IDC_COMBO_UNITS                 1399
#define IDC_debAddAnalysisPointTMD      1400
#define IDC_debAddAnalysisPointTVD      1401
#define IDC_lblAddAnalysisPointTMD      1402
#define IDC_lbUAddAnalysisPointTMD      1402
#define IDC_lblAddAnalysisPointTVD      1403
#define IDC_lbUAddAnalysisPointTVD      1403
#define IDC_lbAttention                 1404
#define IDC_lstFormationLibraryParams   1408
#define IDC_btnDelete                   1414
#define IDC_fraDirLibAccess             1415
#define IDC_optFullyUndrained           1416
#define IDC_optFullyDrained             1417
#define IDC_chkShutIn                   1418
#define IDC_bttnCancel                  1419
#define IDC_ebLoadType                  1420
#define IDC_lbWorkingDir                1421
#define IDC_lbTempDir                   1421
#define IDC_lbFormationLibrary          1422
#define IDC_lbCementLibrary             1423
#define IDC_lbCasingLibrary             1424
#define IDC_ebWorkingDir                1425
#define IDC_ebTempDir                   1425
#define IDC_ebFormationLibrary          1426
#define IDC_ebCementLibrary             1427
#define IDC_ebCasingLibrary             1428
#define IDC_lbWorkDir                   1429
#define IDC_ebWorkDir                   1430
#define IDC_btnBrowseWorkDirOptions     1431
#define IDC_CALC_HELP                   1432
#define IDC_optFluidDensityDefinition   1435
#define IDC_optFluidPressureGradientDefinition 1436
#define IDC_ebDispFluidDensityNWS       1437
#define IDC_lbUDispFluidDensityNWS      1438
#define IDC_ebDispFluidDensity          1439
#define IDC_lbUDispFluidDensity         1440
#define IDC_ebNewFluidDensity           1443
#define IDC_fraShutIn                   1444
#define IDC_ebTailCementDensity         1447
#define IDC_ebCementDensity             1448
#define IDC_ebLeadCementDensity         1449
#define IDC_Warning                     1450
#define IDC_OptVertical                 1551
#define IDC_OptDeviated                 1552
#define IDC_LabelFileName               1553
#define IDC_EditFileName                1555
#define IDC_EditStartRow                1556
#define IDC_SpinStartRow                1557
#define IDC_EditEndRow                  1558
#define IDC_SpinEndRow                  1559
#define IDC_EditMDColumn                1560
#define IDC_SpinMDColumn                1561
#define IDC_EditInclinationColumn       1562
#define IDC_SpinInclinationColumn       1563
#define IDC_EditAzimuthColumn           1564
#define IDC_SpinAzimuthColumn           1565
#define IDC_ComboMDUnit                 1566
#define IDC_ListPreview                 1567
#define IDC_FramePreview                1568
#define IDC_ButtonReset                 1569
#define IDC_VERSION                     1570
#define IDC_COPYRIGHT                   1571
#define IDC_PROGRESS1                   1575
#define IDC_EditDataColumn              1576
#define IDC_lbFluidPressureGradient     1577
#define IDC_SpinDataColumn              1577
#define IDC_ExclTrajectoryWarning       1578
#define IDC_ComboDataUnit               1578
#define IDC_LblTrajectoryWarning        1579
#define IDC_LabelDataColumn             1580
#define IDC_ComboTVDUnit                1581
#define IDC_SpinTVDColumn               1582
#define IDC_EditTVDColumn               1583
#define IDC_EditPressureFileName        1584
#define IDC_BUTTON2                     1585
#define IDC_ButtonRemovePressure        1585
#define IDC_EditDensityFileName         1586
#define IDC_ButtonRemoveDensity         1587
#define IDC_EditTemperatureFileName     1588
#define IDC_ButtonRemoveTemperature     1589
#define IDS_CONSTANT                    2000
#define IDS_REGULARNR                   2001
#define IDS_MODIFIEDNR                  2002
#define IDS_FORCE                       3000
#define IDS_DISPLACEMENT                3001
#define IDS_ENERGY                      3002
#define IDS_HARDENING_NONE              4000
#define IDS_LINEAR_HARD                 4001
#define IDS_LINEAR_SOFT                 4002
#define IDS_PARABOLIC_SOFT              4003
#define IDS_CEM_YOUNGS_MODULUS          7000
#define IDS_CEM_POISSON_RATIO           7001
#define IDS_CEM_VOLUMETRIC_SPEC_HEAT    7002
#define IDS_CEM_THERMAL_CONDUCTIVITY    7003
#define IDS_CEM_TERMAL_EXPANSION        7004
#define IDS_CEM_TENSILE_STRENGTH        7005
#define IDS_CEM_TENS_FRACTURE_ENERGY    7006
#define IDS_CEM_COHESION                7007
#define IDS_CEM_FRICTION_ANGLE          7008
#define IDS_CEM_HARDENING_TYPE          7009
#define IDS_CEM_HARDENING_GRADIENT      7010
#define IDS_CEM_COMP_FRACTURE_ENERGY    7011
#define IDS_CEM_VOLUMETRIC_SHRINKAGE    7012
#define IDS_CEM_HYDRATION_HEAT          7013
#define IDS_YOUNGS_MODULUS              8000
#define IDS_POISSON_RATIO               8001
#define IDS_VOLUMETRIC_SPEC_HEAT        8002
#define IDS_THERMAL_CONDUCTIVITY        8003
#define IDS_THERMAL_EXPANSION           8004
#define IDS_DENSITY                     8005
#define IDS_PLASTICITY                  8006
#define IDS_COHESION                    8007
#define IDS_FRICTION_ANGLE              8008
#define IDS_HARDENING_TYPE              8009
#define IDS_HARDENING_GRADIENT          8010
#define IDS_FRACTURE_ENERGY             8011
#define IDS_CAS_OUTER_DIAMETER          9000
#define IDS_CAS_INNER_DIAMETER          9001
#define IDS_CAS_YOUNGS_MODULUS          9002
#define IDS_CAS_POISSON_RATIO           9003
#define IDS_CAS_VOLUMETRIC_SPEC_HEAT    9004
#define IDS_CAS_THERMAL_CONDUCTIVITY    9005
#define IDS_CAS_THERMAL_EXPANSION       9006
#define IDS_CAS_WEIGHT_PER_UNIT_LENGTH  9007
#define IDS_CAS_PLASTICITY              9008
#define IDS_CAS_YIELD_STRENGTH          9009
#define IDS_MATLIB_NO_MATERIAL          20000
#define ID_TEST                         32771
#define ID_TEST2                        32772
#define ID_ACTIONS_FORMATIONLIBRARY     32773
#define ID_ACTIONS_CEMENTLIBRARY        32774
#define ID_ACTIONS_CASINGLIBRARY        32775
#define ID_APP_RUN                      32776
#define ID_ACTIONS_OPTIONS              32778
#define ID_POPUP_COPY                   32779
#define ID_APP_TOOLTIP                  32780
#define IDTT_FRA_GUIDESHOE              40000
#define IDTT_AAP_debAddAnalysisPointTMD 40001
#define IDTT_AAP_debAddAnalysisPointTVD 40002
#define IDTT_ANA_btnRunAnalysis         40100
#define IDTT_ANA_lstAnalysis            40101
#define IDTT_CAL_ebPoissonRatio         40200
#define IDTT_CAL_ebThermalConductivity  40201
#define IDTT_CAL_ebThermalExpansion     40202
#define IDTT_CAL_ebVolumetricSpecificHeat 40203
#define IDTT_CAL_ebYoungsModulus        40204
#define IDTT_CAO_ebGuideShoeDepth       40300
#define IDTT_CAO_ebPercentageEccentricity 40301
#define IDTT_CAO_lstCasingParams        40302
#define IDTT_CAS_ebDispFluidCompressibility 40400
#define IDTT_CAS_ebDispFluidCompressibilityNWS 40401
#define IDTT_CAS_ebDispFluidStressGrad  40402
#define IDTT_CAS_ebDispFluidStressGradientNWS 40403
#define IDTT_CAS_ebHookLoad             40404
#define IDTT_CAS_fraAxialStresses       40405
#define IDTT_CAS_fraNewFluid            40406
#define IDTT_CAW_bttnStart              40500
#define IDTT_CAW_chkAllowFurtherPostProcessing 40501
#define IDTT_CAW_chkSaveDiagnostic      40502
#define IDTT_CAW_fraAdvancedOptionsForSteppingScheme 40503
#define IDTT_CEL_cmbCompHardeningType   40600
#define IDTT_CEL_ebCohesion             40601
#define IDTT_CEL_ebCompFractureEnergy   40602
#define IDTT_CEL_ebCompHardeningGradient 40603
#define IDTT_CEL_ebFrictionAngle        40604
#define IDTT_CEL_ebHydrationHeat        40605
#define IDTT_CEL_ebPoissonRatio         40606
#define IDTT_CEL_ebTensFractureEnergy   40607
#define IDTT_CEL_ebTensileStrength      40608
#define IDTT_CEL_ebThermalConductivity  40609
#define IDTT_CEL_ebThermalExpansion     40610
#define IDTT_CEL_ebVolumetricShrinkage  40611
#define IDTT_CEL_ebVolumetricSpecificHeat 40612
#define IDTT_CEL_ebYoungsModulus        40613
#define IDTT_CEO_ebLeadCementStressGrad 40700
#define IDTT_CEO_ebTailCementStressGrad 40701
#define IDTT_CEP_ebNumberOfCementScenarios 40801
#define IDTT_COT_chkShutIn              40900
#define IDTT_COT_cmbWellType            40901
#define IDTT_COT_ebDrillingFluidTemperature 40902
#define IDTT_COT_ebTestPressure         40903
#define IDTT_COT_fraCompletion          40904
#define IDTT_COT_fraCompletionBalance   40905
#define IDTT_COT_fraPressureTest        40906
#define IDTT_COT_lstAnalysisPoints      40907
#define IDTT_DER_cmbPlotSpace           41000
#define IDTT_DER_cmbResultType          41001
#define IDTT_DER_cmbTypeOfDamage        41002
#define IDTT_DER_ebLoadType             41003
#define IDTT_DFA_fraAnalysisPointTMD    41100
#define IDTT_DRO_ebAzimuthWithNorth     41200
#define IDTT_DRO_ebBoreholeDiameter     41201
#define IDTT_DRO_ebWellInclination      41202
#define IDTT_DRO_fraDrillingFluidWeight 41203
#define IDTT_EXO_chkEvacuationUnloading 41300
#define IDTT_EXO_chkFracturingHighRateKilling 41301
#define IDTT_EXO_ebBottomHoleTreatingPres 41302
#define IDTT_EXO_ebMaximumInjectionPressure 41303
#define IDTT_EXO_ebTimeOfExposToTreatFluid 41304
#define IDTT_EXO_ebTimeOfExposToTreatFluidEU 41305
#define IDTT_EXO_ebTreatingFluidTemperature 41306
#define IDTT_EXO_ebTreatingFluidTemperatureEU 41307
#define IDTT_EXO_lstAnalysisPoint       41308
#define IDTT_FOD_ebMeanGroundLevel      41400
#define IDTT_FOD_ebMeanSeaLevel         41401
#define IDTT_FOD_ebModelBottomTVD       41402
#define IDTT_FOD_ebModelTopTVD          41403
#define IDTT_FOD_ebOverburdenBottomTVD  41404
#define IDTT_FOD_lstFormationDefinition 41405
#define IDTT_FOD_optOffshoreDefinition  41406
#define IDTT_FOD_optOnshoreDefinition   41407
#define IDTT_FOL_chkPlasticity          41500
#define IDTT_FOL_cmbHardeningType       41501
#define IDTT_FOL_ebFractureEnergy       41502
#define IDTT_FOL_ebFrictionAngle        41503
#define IDTT_FOL_ebHardeningGradient    41504
#define IDTT_FOL_ebPoissonRatio         41505
#define IDTT_FOL_ebThermalConductivity  41506
#define IDTT_FOL_ebThermalExpansion     41507
#define IDTT_FOL_ebVolumetricSpecificHeat 41508
#define IDTT_FOL_ebYoungsModulus        41509
#define IDTT_INS_ebAzimuthOfSHWithNorth 41600
#define IDTT_INS_ebGeothermalGradient   41601
#define IDTT_INS_ebGeothermalGradientF  41602
#define IDTT_INS_ebSurfaceUndisturbedTemp 41603
#define IDTT_INS_ebVerticalStressGradient 41604
#define IDTT_PRI_ebBottomHoleFlowingPress 41700
#define IDTT_PRI_ebBottomHoleFlowingTemp 41701
#define IDTT_PRI_ebInjectionTemperature 41702
#define IDTT_PRI_ebMaximumInjectionPressure 41703
#define IDTT_PRI_ebTimeOfContinuousInjection 41704
#define IDTT_PRI_ebTimeOfContinuousProd 41705
#define IDTT_PRI_lstAnalysisPoint       41706
#define IDTT_REO_optDamageStatusOverviewTable 41800
#define IDTT_REO_optRiskOfDamageBarChart 41801
#define IDTT_MORE_AnalysisPoint         42000
#define IDTT_MORE_BottomHolePressure    42001
#define IDTT_MORE_BottomHoleTemperature 42002
#define IDTT_MORE_Cohesion              42003
#define IDTT_MORE_Completion            42004
#define IDTT_MORE_Cracking              42005
#define IDTT_MORE_Curing                42006
#define IDTT_MORE_DisplacementFluid     42007
#define IDTT_MORE_Elasticity            42008
#define IDTT_MORE_Elevation             42009
#define IDTT_MORE_FiniteElementAnalysis 42010
#define IDTT_MORE_FrictionAngle         42011
#define IDTT_MORE_HardeningBehaviour    42012
#define IDTT_MORE_ModelRange            42013
#define IDTT_MORE_ThermalConductivity   42014
#define IDTT_MORE_ThermalExpansion      42015
#define IDTT_MORE_ExposureTimeToFluid   42016
#define IDTT_MORE_VolumetricSpecificHeat 42017
#define ID_MATLIBX                      61446
#define IDP_FGVPATHNOTFOUND             61447
#define IDP_DIANAPATHNOTFOUND           61448
#define IDP_CANNOTCREATELIBRARYDIR      61449
#define IDP_MSG_SELECTNEWTEMP           61450
#define IDP_MSG_NOTEMPFOLDER            61451
#define IDP_CANNOTCREATETEMPDIR         61452
#define IDP_INSTALLLOCATIONNOTFOUND     61453

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1586
#define _APS_NEXT_SYMED_VALUE           134
#endif
#endif
