// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "dsbx.h"

// Dispatch interfaces referenced by this interface
#include "Well.h"
#include "rock.h"
#include "insitu.h"
#include "proc.h"
#include "MudWeight.h"
#include "timepoints.h"
#include "Mesh.h"
#include "Output.h"

/////////////////////////////////////////////////////////////////////////////
// CDsbX

IMPLEMENT_DYNCREATE(CDsbX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDsbX properties

long CDsbX::GetAnalysisType()
{
	long result;
	GetProperty(0x14, VT_I4, (void*)&result);
	return result;
}

void CDsbX::SetAnalysisType(long propVal)
{
	SetProperty(0x14, VT_I4, propVal);
}

CWell CDsbX::GetWell()
{
	LPDISPATCH pDispatch;
	GetProperty(0x15, VT_DISPATCH, (void*)&pDispatch);
	return CWell(pDispatch);
}

void CDsbX::SetWell(LPDISPATCH propVal)
{
	SetProperty(0x15, VT_DISPATCH, propVal);
}

CRock CDsbX::GetRock()
{
	LPDISPATCH pDispatch;
	GetProperty(0x16, VT_DISPATCH, (void*)&pDispatch);
	return CRock(pDispatch);
}

void CDsbX::SetRock(LPDISPATCH propVal)
{
	SetProperty(0x16, VT_DISPATCH, propVal);
}

CInSitu CDsbX::GetInSitu()
{
	LPDISPATCH pDispatch;
	GetProperty(0x17, VT_DISPATCH, (void*)&pDispatch);
	return CInSitu(pDispatch);
}

void CDsbX::SetInSitu(LPDISPATCH propVal)
{
	SetProperty(0x17, VT_DISPATCH, propVal);
}

CProc CDsbX::GetProc()
{
	LPDISPATCH pDispatch;
	GetProperty(0x18, VT_DISPATCH, (void*)&pDispatch);
	return CProc(pDispatch);
}

void CDsbX::SetProc(LPDISPATCH propVal)
{
	SetProperty(0x18, VT_DISPATCH, propVal);
}

CMudWeight CDsbX::GetMudWeight()
{
	LPDISPATCH pDispatch;
	GetProperty(0x19, VT_DISPATCH, (void*)&pDispatch);
	return CMudWeight(pDispatch);
}

void CDsbX::SetMudWeight(LPDISPATCH propVal)
{
	SetProperty(0x19, VT_DISPATCH, propVal);
}

CTimePoints CDsbX::GetTimePoints()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1a, VT_DISPATCH, (void*)&pDispatch);
	return CTimePoints(pDispatch);
}

void CDsbX::SetTimePoints(LPDISPATCH propVal)
{
	SetProperty(0x1a, VT_DISPATCH, propVal);
}

CMesh CDsbX::GetMesh()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1b, VT_DISPATCH, (void*)&pDispatch);
	return CMesh(pDispatch);
}

void CDsbX::SetMesh(LPDISPATCH propVal)
{
	SetProperty(0x1b, VT_DISPATCH, propVal);
}

COutput CDsbX::GetOutput()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1c, VT_DISPATCH, (void*)&pDispatch);
	return COutput(pDispatch);
}

void CDsbX::SetOutput(LPDISPATCH propVal)
{
	SetProperty(0x1c, VT_DISPATCH, propVal);
}

BOOL CDsbX::GetThermalAnalysis()
{
	BOOL result;
	GetProperty(0x24, VT_BOOL, (void*)&result);
	return result;
}

void CDsbX::SetThermalAnalysis(BOOL propVal)
{
	SetProperty(0x24, VT_BOOL, propVal);
}

double CDsbX::GetStabilityCalibrationFactor()
{
	double result;
	GetProperty(0x28, VT_R8, (void*)&result);
	return result;
}

void CDsbX::SetStabilityCalibrationFactor(double propVal)
{
	SetProperty(0x28, VT_R8, propVal);
}

double CDsbX::GetOvalisationFactor()
{
	double result;
	GetProperty(0x29, VT_R8, (void*)&result);
	return result;
}

void CDsbX::SetOvalisationFactor(double propVal)
{
	SetProperty(0x29, VT_R8, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CDsbX operations

BOOL CDsbX::FullMeshRequired(BOOL* FullMeshRequired)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBOOL;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FullMeshRequired);
	return result;
}

BOOL CDsbX::CalculateFailure(double MudWeight, BOOL* ShearFailure, BOOL* TensileFailure, double* TauRatio)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8 VTS_PBOOL VTS_PBOOL VTS_PR8;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		MudWeight, ShearFailure, TensileFailure, TauRatio);
	return result;
}

BOOL CDsbX::RunFem(BOOL Verbose, BOOL Debug)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Verbose, Debug);
	return result;
}

BOOL CDsbX::ResultExtremes(long Component, BOOL Maximum, VARIANT* Results)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_BOOL VTS_PVARIANT;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Component, Maximum, Results);
	return result;
}

long CDsbX::GetVersion()
{
	long result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CDsbX::GetRevision()
{
	long result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::SetDianaPath(LPCTSTR Path)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Path);
	return result;
}

BOOL CDsbX::SetWorkingDirectory(LPCTSTR Path)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Path);
	return result;
}

BOOL CDsbX::ReadParameterFile(LPCTSTR Path)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Path);
	return result;
}

BOOL CDsbX::WriteParameterFile(LPCTSTR Path)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Path);
	return result;
}

CString CDsbX::GetCurrentParameterFilePath()
{
	CString result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::StopFem()
{
	BOOL result;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::FemCleanup()
{
	BOOL result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::ExpandMesh()
{
	BOOL result;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::FullResults(long Component, long Step, VARIANT* XCoord, VARIANT* YCoord, VARIANT* Results)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Component, Step, XCoord, YCoord, Results);
	return result;
}

BOOL CDsbX::CriticalPlasticStrain(double CalibrationFactor, double* CriticalPlasticStrain)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8 VTS_PR8;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		CalibrationFactor, CriticalPlasticStrain);
	return result;
}

BOOL CDsbX::GetRequiredFrictionAngle(double* FrictionAngle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FrictionAngle);
	return result;
}

BOOL CDsbX::GetTauRatio(double* TauRatio)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		TauRatio);
	return result;
}

BOOL CDsbX::PlotContours(LPCTSTR Name, long Component, long Step, VARIANT* Contours)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_PVARIANT;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, Component, Step, Contours);
	return result;
}

void CDsbX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CDsbX::CleanUpWorkingDir()
{
	BOOL result;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CDsbX::GetDianaPath()
{
	CString result;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CDsbX::GetWorkingDir()
{
	CString result;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::GetVersionInfo(LPCTSTR FileName, short* version, short* revision)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName, version, revision);
	return result;
}

BOOL CDsbX::NeedToUpdateFemGVDatabase()
{
	BOOL result;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::UpdateFemGVDatabase()
{
	BOOL result;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::GetDianaPathVersion(short* version, short* revision)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PI2;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		version, revision);
	return result;
}

BOOL CDsbX::RadialResults(long Component, long Step, double Angle, long NrOfPoints, VARIANT* XCoord, VARIANT* YCoord, VARIANT* Results)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_R8 VTS_I4 VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Component, Step, Angle, NrOfPoints, XCoord, YCoord, Results);
	return result;
}

BOOL CDsbX::TangentialResults(long Component, long Step, double Radius, long NrOfPoints, VARIANT* XCoord, VARIANT* YCoord, VARIANT* Results)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_R8 VTS_I4 VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Component, Step, Radius, NrOfPoints, XCoord, YCoord, Results);
	return result;
}

BOOL CDsbX::InquireTauRatio(double* FailureOnset, BOOL* FailureOnsetFound, double* FailureOffset, BOOL* FailureOffsetFound, double* Extreme, BOOL* ExtremeFound, double* TensileFailure, BOOL* TensileFailureFound, double* p1, double* pn, 
		short* Inquirecase)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8 VTS_PBOOL VTS_PR8 VTS_PBOOL VTS_PR8 VTS_PBOOL VTS_PR8 VTS_PBOOL VTS_PR8 VTS_PR8 VTS_PI2;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FailureOnset, FailureOnsetFound, FailureOffset, FailureOffsetFound, Extreme, ExtremeFound, TensileFailure, TensileFailureFound, p1, pn, Inquirecase);
	return result;
}

BOOL CDsbX::CriticalPlasticStrainEx(double* CriticalPlasticStrain)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		CriticalPlasticStrain);
	return result;
}

double CDsbX::GetFailedSurface(long iStepNr)
{
	double result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		iStepNr);
	return result;
}

double CDsbX::GetFailedSurfaceAtMudweight(double dMudweight)
{
	double result;
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		dMudweight);
	return result;
}


CString CDsbX::GetKeyFile()
{
	CString result;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CDsbX::SetKeyFile(LPCTSTR FileName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName);
	return result;
}
