// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "mesh.h" //FIXME: MCR
#include "stdafx.h"

/////////////////////////////////////////////////////////////////////////////
// CMesh properties

double CMesh::GetBoreholeRadius() {
  double result;
  GetProperty(0x1, VT_R8, (void *)&result);
  return result;
}

void CMesh::SetBoreholeRadius(double propVal) { SetProperty(0x1, VT_R8, propVal); }

double CMesh::GetModelRadius() {
  double result;
  GetProperty(0x2, VT_R8, (void *)&result);
  return result;
}

void CMesh::SetModelRadius(double propVal) { SetProperty(0x2, VT_R8, propVal); }

long CMesh::GetNrTangential() {
  long result;
  GetProperty(0x3, VT_I4, (void *)&result);
  return result;
}

void CMesh::SetNrTangential(long propVal) { SetProperty(0x3, VT_I4, propVal); }

long CMesh::GetNrRadial() {
  long result;
  GetProperty(0x4, VT_I4, (void *)&result);
  return result;
}

void CMesh::SetNrRadial(long propVal) { SetProperty(0x4, VT_I4, propVal); }

double CMesh::GetSizeFactor() {
  double result;
  GetProperty(0x5, VT_R8, (void *)&result);
  return result;
}

void CMesh::SetSizeFactor(double propVal) { SetProperty(0x5, VT_R8, propVal); }

BOOL CMesh::GetQuarterMesh() {
  BOOL result;
  GetProperty(0x6, VT_BOOL, (void *)&result);
  return result;
}

void CMesh::SetQuarterMesh(BOOL propVal) { SetProperty(0x6, VT_BOOL, propVal); }

/////////////////////////////////////////////////////////////////////////////
// CMesh operations

BOOL CMesh::SetDefault() {
  BOOL result;
  InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void *)&result, NULL);
  return result;
}
