// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "output.h"
#include "stdafx.h"

/////////////////////////////////////////////////////////////////////////////
// COutput properties

BOOL COutput::GetTabulated() {
  BOOL result;
  GetProperty(0x1, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetTabulated(BOOL propVal) { SetProperty(0x1, VT_BOOL, propVal); }

BOOL COutput::GetFemview() {
  BOOL result;
  GetProperty(0x2, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetFemview(BOOL propVal) { SetProperty(0x2, VT_BOOL, propVal); }

BOOL COutput::GetNeutral() {
  BOOL result;
  GetProperty(0x3, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetNeutral(BOOL propVal) { SetProperty(0x3, VT_BOOL, propVal); }

BOOL COutput::GetPlasticity() {
  BOOL result;
  GetProperty(0x4, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetPlasticity(BOOL propVal) { SetProperty(0x4, VT_BOOL, propVal); }

BOOL COutput::GetStress() {
  BOOL result;
  GetProperty(0x5, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetStress(BOOL propVal) { SetProperty(0x5, VT_BOOL, propVal); }

BOOL COutput::GetStrain() {
  BOOL result;
  GetProperty(0x6, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetStrain(BOOL propVal) { SetProperty(0x6, VT_BOOL, propVal); }

BOOL COutput::GetDisplacement() {
  BOOL result;
  GetProperty(0x7, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetDisplacement(BOOL propVal) { SetProperty(0x7, VT_BOOL, propVal); }

BOOL COutput::GetPressure() {
  BOOL result;
  GetProperty(0x8, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetPressure(BOOL propVal) { SetProperty(0x8, VT_BOOL, propVal); }

BOOL COutput::GetTemperature() {
  BOOL result;
  GetProperty(0x9, VT_BOOL, (void *)&result);
  return result;
}

void COutput::SetTemperature(BOOL propVal) { SetProperty(0x9, VT_BOOL, propVal); }

/////////////////////////////////////////////////////////////////////////////
// COutput operations
