// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "proc.h"


/////////////////////////////////////////////////////////////////////////////
// CProc properties

long CProc::GetMaxIter()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CProc::SetMaxIter(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

double CProc::GetCriterium()
{
	double result;
	GetProperty(0x2, VT_R8, (void*)&result);
	return result;
}

void CProc::SetCriterium(double propVal)
{
	SetProperty(0x2, VT_R8, propVal);
}

long CProc::GetScheme()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CProc::SetScheme(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CProc::GetTypeCrit()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CProc::SetTypeCrit(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CProc operations

BOOL CProc::SetDefault()
{
	BOOL result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}
