<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <OIVPATH>$(OIVHOME)\arch-Windows-x86_64-msvc14-$(Configuration)\bin</OIVPATH>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="OIVPATH">
      <Value>$(OIVPATH)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>