/*
 */
 /* Copyright (c) 2012 TNO DIANA BV                              Confidential */
#include "SurfaceDesc.h"
#include "TetMeshBase.h"
#include "ElementGroup.h"
#include "InterfaceElement.h"

namespace geo {

/*!
  Constructor for surface ....
*/
CSurfaceDesc::CSurfaceDesc( CTetMeshBase&      mesh,
              const ISurface&    surface,
              const std::string& sName,
              bool               bSlip )
: m_mesh(mesh),
  m_vcTetSurface(0),
  m_pElementGroup(0),
  m_surface(surface),
  m_name(sName)
{
  mesh.m_vcSurfaceDesc.push_back(this);
  if(bSlip)
  m_pElementGroup = new CElementGroup(mesh, false);
}

/*!
  Returns the name of the surface.
*/
const std::string& CSurfaceDesc::Name() const
{
  return m_name;
}

/*!
  Returns true when the surface is slipping.
  \sa Front(), Back()
*/
bool CSurfaceDesc::Slip() const
{

  return m_pElementGroup != 0;
}

/*!
  Set whether the surface is slipping or not
  \sa Slip()
 */
void CSurfaceDesc::Slip( bool bSlip )
{
  if ( bSlip == Slip() ) return;

  if ( bSlip ) {
  assert ( m_pElementGroup == 0 );
  m_pElementGroup = new CElementGroup(m_mesh, false);
  } else {
  assert( m_pElementGroup != 0 );
  delete m_pElementGroup;
  m_pElementGroup = 0;
  }
}


/*!
  Returns the front-surface generated by the mesher
  Slip must be enabled otherwise an assertion is failed.
*/
const CElementGroup& CSurfaceDesc::interfaceElements() const
{
  assert(Slip());
  return *m_pElementGroup;
}


void CSurfaceDesc::AddInterfaceElement(CInterfaceElement& element)
{
  assert(Slip());
  m_pElementGroup->AddMeshElement(element);
}


/*!
  Returns a surface
  Slip must be disenabled otherwise an assertion is failed.
*/
const ISurface &CSurfaceDesc::Surface() const
{
  return m_surface;
}

/*!
  Returns the number of avaible generated tet surfaces
*/
int CSurfaceDesc::TetSurfaceSize() const
{
  return (int)m_vcTetSurface.size();
}

/*!
  Returns the generated tet surface based on the index
*/
const CTetSurface& CSurfaceDesc::TetSurface(int nIndex) const
{
  return *m_vcTetSurface[nIndex];
}

}
