@ECHO OFF
SET VARIABLE=DIAPATH
IF "%DIAPATH%" == "" GOTO NOT.DEFINED
SET VARIABLE=DIASRC
IF "%DIASRC%" == "" GOTO NOT.DEFINED
SET VARIABLE=INTEL
IF "%INTEL%" == "" GOTO NOT.DEFINED
SET VARIABLE=QTDIR
IF "%QTDIR%" == "" GOTO NOT.DEFINED
EXIT 0
:NOT.DEFINED
ECHO %VARIABLE% not defined
rem EXIT 1
