#if !defined(AFX_FGVRUNCTR_H__E58CE132_87C3_4C82_8337_48537E70F870__INCLUDED_)
#define AFX_FGVRUNCTR_H__E58CE132_87C3_4C82_8337_48537E70F870__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFgvRunCtr wrapper class

class CFgvRunCtr : public CWnd
{
protected:
	DECLARE_DYNCREATE(CFgvRunCtr)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x575b1a9, 0x7631, 0x4484, { 0x94, 0xd5, 0x7e, 0xba, 0x92, 0x2b, 0x1c, 0xba } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL RunFemView();
	CString GetFgvPath();
	void SetFgvPath(LPCTSTR lpszNewValue);
	CString GetFgvKey();
	void SetFgvKey(LPCTSTR lpszNewValue);
	CString GetWorkingDir();
	void SetWorkingDir(LPCTSTR lpszNewValue);
	BOOL GetMonitorLogfile();
	void SetMonitorLogfile(BOOL bNewValue);
	void AbortProcess();
	long GetParentHwnd();
	void SetParentHwnd(long nNewValue);
	BOOL GetAutoCloseDialog();
	void SetAutoCloseDialog(BOOL bNewValue);
	CString GetMonitorCaption();
	void SetMonitorCaption(LPCTSTR lpszNewValue);
	CString GetExeName();
	void SetExeName(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FGVRUNCTR_H__E58CE132_87C3_4C82_8337_48537E70F870__INCLUDED_)
