#if !defined(AFX_LABEL_H__CC1BE134_C4D2_4ECB_A6B0_345F9957D028__INCLUDED_)
#define AFX_LABEL_H__CC1BE134_C4D2_4ECB_A6B0_345F9957D028__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLabel wrapper class

class CLabel : public COleDispatchDriver
{
public:
	CLabel() {}		// Calls COleDispatchDriver default constructor
	CLabel(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLabel(const CLabel& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetText();
	void SetText(LPCTSTR);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LABEL_H__CC1BE134_C4D2_4ECB_A6B0_345F9957D028__INCLUDED_)
