#if !defined(AFX_MARKERCOLLECTION_H__CB9F4023_1FEF_4739_A09E_80B5318C57D9__INCLUDED_)
#define AFX_MARKERCOLLECTION_H__CB9F4023_1FEF_4739_A09E_80B5318C57D9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMarker;

/////////////////////////////////////////////////////////////////////////////
// CMarkerCollection wrapper class

class CMarkerCollection : public COleDispatchDriver
{
public:
	CMarkerCollection() {}		// Calls COleDispatchDriver default constructor
	CMarkerCollection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMarkerCollection(const CMarkerCollection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	LPDISPATCH GetParent();

// Operations
public:
	CMarker GetItem(const VARIANT& Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MARKERCOLLECTION_H__CB9F4023_1FEF_4739_A09E_80B5318C57D9__INCLUDED_)
