#if !defined(AFX_MARKER_H__57A08EF4_9C16_4420_B96C_2652FD594C64__INCLUDED_)
#define AFX_MARKER_H__57A08EF4_9C16_4420_B96C_2652FD594C64__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLineStyle;
class CDataIndex;
class CDataCoord;

/////////////////////////////////////////////////////////////////////////////
// CMarker wrapper class

class CMarker : public COleDispatchDriver
{
public:
	CMarker() {}		// Calls COleDispatchDriver default constructor
	CMarker(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMarker(const CMarker& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetName();
	BOOL GetIsShowing();
	void SetIsShowing(BOOL);
	long GetMethod();
	void SetMethod(long);
	BOOL GetIsStyleDefault();
	void SetIsStyleDefault(BOOL);
	CLineStyle GetStyle();
	CDataIndex GetIndex();
	CDataCoord GetValue();
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MARKER_H__57A08EF4_9C16_4420_B96C_2652FD594C64__INCLUDED_)
