#if !defined(AFX_SYMBOLSTYLE_H__3A3602F1_FB0D_4EC6_A1EE_E30123EE7A81__INCLUDED_)
#define AFX_SYMBOLSTYLE_H__3A3602F1_FB0D_4EC6_A1EE_E30123EE7A81__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSymbolStyle wrapper class

class CSymbolStyle : public COleDispatchDriver
{
public:
	CSymbolStyle() {}		// Calls COleDispatchDriver default constructor
	CSymbolStyle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSymbolStyle(const CSymbolStyle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetShape();
	void SetShape(long);
	unsigned long GetColor();
	void SetColor(unsigned long);
	long GetSize();
	void SetSize(long);
	LPDISPATCH GetParent();
	BOOL GetIsDefault();
	void SetIsDefault(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SYMBOLSTYLE_H__3A3602F1_FB0D_4EC6_A1EE_E30123EE7A81__INCLUDED_)
