#!/bin/bash

# $1: release / debug
# $2: geomec_cora (binary) 
# $3: model (.gm4)
# $4: file version (.txt,.xml) (most of the times is not needed)

DEBUG_RELEASE=$1
BINARY=$2
MODEL=$3
FILE_VERSION=$4

echo "cmd : get : $0 $@"

#cd $DEBUG_RELEASE

CODE_ROOT=../..

LD_LIBRARY_PATH_=\
$CODE_ROOT/third_party/tbb/linux/lib/intel64/gcc4.7:\
$CODE_ROOT/UserDLLs

#MCR: UserDLLs ? Release and debug or just release (in run model script is considered)

FILENAME=$(basename $MODEL .gm4)

OUTPUT_FOLDER=test_output

LD_LIBRARY_PATH=\
$LD_LIBRARY_PATH_:$LD_LIBRARY_PATH \
./$BINARY \
$MODEL \
getmodelinfo \
$FILE_VERSION \
$OUTPUT_FOLDER/$FILENAME.getmodelinfo \
$OUTPUT_FOLDER/$FILENAME.summary_result_file \
> $OUTPUT_FOLDER/$FILENAME.get.log 2>&1

if [ $? -eq 0 ]; then
	echo "TEST SUCCEEDED"
else
	echo "TEST FAILED"
	exit 1
fi
#cd ..
