#ifndef _resourceIDI_h_
#define _resourceIDI_h_

/*
 * This file should contain the constants defining all icons.
 */

#define IDI_MESH                        124
#define IDI_SURFACE                     128
#define IDI_HORIZON                     129
#define IDI_GEOMETRY                    130
#define IDI_MAP                         132
#define IDI_MODEL                       133
#define IDI_RESULT                      134
#define IDI_REPORT                      135
#define IDI_SURFACES                    136
#define IDI_POINTSETS                   137
#define IDI_POINTSET                    138
#define IDI_HORIZONS                    139
#define IDI_FAULTS                      142
#define IDI_FAULT                       143
#define IDI_FORMATION                   145
#define IDI_FORMATIONS                  146
#define IDI_BODY                        147
#define IDI_WELLPATHS                   152
#define IDI_WELLPATH                    153
#define IDI_BOUNDARY                    154
#define IDI_MATERIAL                    155
#define IDI_ROCK_MATERIAL               156
#define IDI_BIRDEYES                    157
#define IDI_BIRDEYE                     158
#define IDI_COLOR_GRADIENT              159
#define IDI_HOTSPOT                     160
#define IDI_GOCAD                       161
#define IDI_UNDEFINED                   178
#define IDI_GENERAL                     179
#define IDI_HORIZON_MODEL               180
#define IDI_UNCHECKED                   183
#define IDI_DEPLETION_STAGE             184
#define IDI_GEN_PRESS                   185
#define IDI_HORIZON_CONST_DEPTH         191
#define IDI_RADIO_UNCHECKED             193
#define IDI_RADIO_CHECKED               194
#define IDI_STRESS_DISTR                195
#define IDI_STRESS                      196
#define IDI_CHECKED                     197
#define IDI_VALUE_SET                   198
#define IDI_TRI_CHECKED                 199
#define IDI_PRESSURES                   203
#define IDI_SLIP_HORIZON                204
#define IDI_SLIP_CONST_HORIZON          205
#define IDI_PRESSURE_PREVIOUS           206
#define IDI_COMPONENT_PRESSURE_REPEAT   207
#define IDI_DEPLETING_FORMATION         208
#define IDI_PRES_GWC                    209
#define IDI_COMPONENT_PRESSURE_GWC      210
#define IDI_ARROW                       216
#define IDI_MATERIAL_NONE               217
#define IDI_VALUETYPE_YOUNGS_MODULUS    223
#define IDI_VALUETYPE_POISSONS_RATIO    224
#define IDI_COHESION                    225
#define IDI_FRICTION_ANGLE              226
#define IDI_VALUETYPE_POROSITY          227
#define IDI_VALUETYPE_BULK_DENSITY      228
#define IDI_VALUETYPE_COMPRESSIONAL_VELOCITY 229
#define IDI_VALUETYPE_SHEAR_VELOCITY    230
#define IDI_MINIMAL_PRINCIPAL_STRESS    231
#define IDI_COMPONENT_STRESS_VERTICAL   232
#define IDI_MAXIMAL_PRINCIPAL_STRESS    233
#define IDI_STRESS_TENSOR               234
#define IDI_VALUETYPE_VERTICAL_PERMEABILITY 236
#define IDI_VALUETYPE_HORIZONTAL_PERMEABILITY 237
#define IDI_VALUETYPE_DISPLACEMENT      238
#define IDI_VALUETYPE_FRICTION_COEFFICIENT 239
#define IDI_COMPONENT_XX                240
#define IDI_COMPONENT_DEFAULT           242
#define IDI_ECLIPSE_MODEL               244
#define IDI_MESH_REGION                 247
#define IDI_MESH_MASTER                 250
#define IDI_ELEMENT_VALUESET            251
#define IDI_ELEMENT_SET                 252
#define IDI_GLOBAL_INITIAL_STRESS       256
#define IDI_RADIO_DISABLED              257
#define IDI_XSECTION                    258
#define IDI_XSECTIONS                   259
#define IDI_GRAPHS                      266
#define IDI_FORMATIONPLANE              269
#define IDI_NON_LINEAR                  271
#define IDI_LINEAR                      272
#define IDI_FORMATIONPLANES             274
#define IDI_NON_AND_LINEAR              282
#define IDI_TOP_HORIZON                 283
#define IDI_BOTTOM_HORIZON              284
#define IDI_SIDE_SURFACES               285
#define IDI_TOP_HORIZON_DISABLED        286
#define IDI_BOTTOM_HORIZON_DISABLED     287
#define IDI_SURFACE_USED                292
#define IDI_VALUETYPE_INITFRICTION      297
#define IDI_VALUETYPE_HARDENING         298
#define IDI_VALUETYPE_PRECONSOLIDATION  299
#define IDI_VALUETYPE_CAPSHAPE          300
#define IDI_VALUETYPE_DILATATION        301
#define IDI_VALUETYPE_LATRATIO_MAX      302
#define IDI_VALUETYPE_LATRATIO_MIN      303
#define IDI_VALUETYPE_AZIMUTH           304
#define IDI_VALUETYPE_INIPORO           305
#define IDI_VALUETYPE_INISTRAINRATE     306
#define IDI_VALUETYPE_VPPROCPARAM       307
#define IDI_VALUETYPE_CREEP_A1          308
#define IDI_VALUETYPE_CREEP_A2          309
#define IDI_VALUETYPE_CREEP_N1          310
#define IDI_VALUETYPE_CREEP_N2          311
#define IDI_VALUETYPE_SHEARMODULUS      312
#define IDI_VALUETYPE_DYNUNISTIFFNESS   313
#define IDI_VALUETYPE_DYNSHEARSTIFFNESS 314
#define IDI_VALUETYPE_RHOB              315
#define IDI_VALUETYPE_VELOCITYP         316
#define IDI_VALUETYPE_VELOCITYS         317
#define IDI_DATA_STORE                  320
#define IDI_CHECK_DISABLED              322
#define IDI_RESULT_MAP                  328
#define IDI_RPN_VALUESET                329
#define IDI_NODALSUPPORT                334
#define IDI_FACESUPPORT                 335
#define IDI_FACESUPPORT_DISABLED        336
#define IDI_NODALSUPPORT_DISABLED       337
#define IDI_CHECK_RED                   341
#define IDI_CROSS_BLACK                 342
#define IDI_CROSS_RED                   343
#define IDI_VALUETYPE_COORDINATE        344
#define IDI_TETRA_MODEL                 345
#define IDI_VIEW                        350
#define IDI_DATA_STORAGE                352
#define IDI_PRES_UNDEF                  355
#define IDI_COMPONENT_PRESSURE_UNDEFINED 356
#define IDI_COMPONENT_PRESSURE_GLOBAL   357
#define IDI_PRES_CONSTANT               359
#define IDI_COMPONENT_PRESSURE_CONSTANT 360
#define IDI_PRES_DISTRI                 361
#define IDI_COMPONENT_PRESSURE_DISTRIBUTED 362
#define IDI_NODAL_VALUESET              368
#define IDI_VALUETYPE_COHESION          370
#define IDI_VALUETYPE_FRICTION_ANGLE    371
#define IDI_VALUETYPE_BULKSTIFFNESS     372
#define IDI_VALUETYPE_FLUID_BULK_MOD    373
#define IDI_VALUETYPE_STRESS_TENSOR     374
#define IDI_VALUETYPE_SURFACE           377
#define IDI_CHECK_GREEN                 381
#define IDI_NEW_ITEM                    382
#define IDI_ISRESERVOIR                 383
#define IDI_VALUETYPE_HARD_COHESION1    389
#define IDI_VALUETYPE_HARD_COHESION2    390
#define IDI_VALUETYPE_HARD_COHESION3    391
#define IDI_VALUETYPE_EQUIV_PLAST_STRAIN1 392
#define IDI_VALUETYPE_EQUIV_PLAST_STRAIN2 393
#define IDI_VALUETYPE_EQUIV_PLAST_STRAIN3 394
#define IDI_VALUETYPE_HARD_FRICTION1    395
#define IDI_VALUETYPE_HARD_FRICTION2    396
#define IDI_VALUETYPE_HARD_FRICTION3    397
#define IDI_CASING_GRADE                401
#define IDI_ANALYSIS_POINT_ENTRY        406
#define IDI_ANALYSIS_POINT              407
#define IDI_INITIAL_TEMPERATURE         408
#define IDI_XSEC_LINES                  415
#define IDI_2D_MODEL                    417
#define IDI_COMPARTMENT                 419
#define IDI_2D_XSEC                     424
#define IDI_FORMATION_DEPL_TEMP         426
#define IDI_FORMATION_TEMP              427
#define IDI_SCALINGBOX                  428
#define IDI_HOMGENBOX                   429
#define IDI_VALUETYPE_RIGID_1           432
#define IDI_VALUETYPE_RIGID_2           433
#define IDI_VALUETYPE_RIGID_3           434
#define IDI_VALUETYPE_RIGID_4           435
#define IDI_VALUETYPE_RIGID_5           436
#define IDI_VALUETYPE_RIGID_6           437
#define IDI_VALUETYPE_RIGID_7           438
#define IDI_VALUETYPE_RIGID_8           439
#define IDI_VALUETYPE_RIGID_9           440
#define IDI_VALUETYPE_RIGID_10          441
#define IDI_VALUETYPE_RIGID_11          442
#define IDI_VALUETYPE_RIGID_12          443
#define IDI_VALUETYPE_RIGID_13          444
#define IDI_VALUETYPE_RIGID_14          445
#define IDI_VALUETYPE_RIGID_15          446
#define IDI_VALUETYPE_RIGID_16          447
#define IDI_VALUETYPE_RIGID_17          448
#define IDI_VALUETYPE_RIGID_18          449
#define IDI_VALUETYPE_RIGID_19          450
#define IDI_VALUETYPE_RIGID_20          451
#define IDI_VALUETYPE_RIGID_21          452
#define IDI_3D_RESULT                   453
#define IDI_2D_RESULT                   454
#define IDI_2D_3D_RESULT                455
#define IDI_FAULTLD                     459
#define IDI_FAULTLU                     460
#define IDI_RPN_FORMULAS                462
#define IDI_PROPERTY                    463
#define IDI_XSECTION2D                  464
#define IDI_XSECTIONS2D                 465
#define IDI_SCALING_BOX                 468
#define IDI_VALUETYPE_CREEP_QR1         470
#define IDI_VALUETYPE_CREEP_QR2         471
#define IDI_VALUETYPE_CREEP_Q2R         472
#define IDI_VALUETYPE_TENSILE_STRETCH   473
#define IDI_COMPONENT_PRESSURE_REPEAT_CHANGE 474
#define IDI_DEPLETION_STAGE_INITIAL     475
#define IDI_DEPLETION_STAGE_INITIALDEF  476
#define IDI_DEPLETION_STAGE_BRANCH      479
#define IDI_DEPLETION_STAGE_NONE        481
#define IDI_DEPLETION_STAGE_INITIAL_NONE 482
#define IDI_DEPLETION_STAGE_INITIAL_BRANCH 483
#define IDI_VALUETYPE_THERMAL_EXPANSION 484
#define IDI_TEMPERATURES                485
#define IDI_COMPONENT_TEMPERATURE_DISTRIBUTED 486
#define IDI_COMPONENT_TEMPERATURE_GRADIENT 487
#define IDI_COMPONENT_TEMPERATURE_REPEATER 488
#define IDI_COMPONENT_TEMPERATURE_REPEATER_CHANGE 489
#define IDI_COMPONENT_PRESSURE_MINIMUM  491
#define IDI_COMPONENT_PRESSURE_MAXIMUM  492
#define IDI_XSECTION_HORIZONTAL         494
#define IDI_RPN_VALUESET_USED           498
#define IDI_VALUETYPE_ELASTIC_HARDENING 499
#define IDI_VALUETYPE_SEC_PRECON        500
#define IDI_VALUETYPE_SEC_HARDENING     501
#define IDI_ROCK_MATERIALS              503
#define IDI_MATERIAL_NONE_PREV          504
#define IDI_MATERIAL_PREV               505
#define IDI_ROCK_MATERIAL_LOCKED        506
#define IDI_ROCK_MATERIAL_FIXED         507
#define IDI_WELLZOOMIN_MODEL            508
#define IDI_ICON4                       511
#define IDI_VALUETYPE_ELASCOMPRES       512
#define IDI_VALUETYPE_PLASCOMPRES       513
#define IDI_VALUETYPE_YOUNGMODULUS_NORM 516
#define IDI_VALUETYPE_YOUNGMODULUS_TRANS 517
#define IDI_VALUETYPE_POISSONRATIO_NORM 518
#define IDI_VALUETYPE_POISSONRATIO_TRANS 519
#define IDI_VALUETYPE_THERM_LIN_EXP_NORM 520
#define IDI_VALUETYPE_THERM_LIN_EXP_LAT 521
#define IDI_VALUETYPE_HIGH_FRACT_DENS_AZI 522
#define IDI_VALUETYPE_LOW_FRACT_DENS_AZI 523
#define IDI_VALUETYPE_HIGH_FRACT_DENS   524
#define IDI_VALUETYPE_LOW_FRACT_DENS    525
#define IDI_VALUETYPE_INT_FRACT_DENS    526
#define IDI_VALUETYPE_HIGH_FRACT_DENS_INCL 527
#define IDI_VALUETYPE_LOW_FRACT_DENS_INCL 528
#define IDI_VALUETYPE_FRACT_STIFF_NORMAL 529
#define IDI_VALUETYPE_FRACT_STIFF_SHEAR 530
#define IDI_VALUETYPE_LAYER_NORMAL_INCL 531
#define IDI_VALUETYPE_LAYER_NORMAL_AZI  532
#define IDI_VALUETYPE_THERM_CONDUCT     533
#define IDI_VALUETYPE_THERM_CAPAC       534
#define IDI_VALUETYPE_THERM_CAPACI      535
#define IDI_VALUETYPE_FRACT_TENSOR      536
#define IDI_MEASURED_DISPLACEMENT       538
#define IDI_HEAT                        539
#define IDI_MIXTURE                     540
#define IDI_CALC_TEMPER                 543
#define IDI_CALC_TEMPERS                544
#define IDI_FAULTPARAMETERS             545
#define IDI_ICON5                       546
#define IDI_VALUETYPE_PERMEA            548
#define IDI_FORMATION_THICKNESS         550
#define IDI_VALUETYPE_YOUNG_DECOMP      551
#define IDI_VALUETYPE_POISSON_DECOMP    552
#define IDI_VALUETYPE_VISCOSITY         555
#define IDI_UPSCALING                   556
#define IDI_COMPONENT_CORRECTIONSTRAIN_DISTRIBUTED 561
#define IDI_COMPONENT_VOLUMETRICSTRAIN_DISTRIBUTED 562
#define IDI_VOLUMETRIC_STRAINS          564
#define IDI_COMPONENT_VOLSTRAIN_GRADIENT 566
#define IDI_INITIAL_VOLSTRAIN           567
#define IDI_COMPONENT_VOLSTRAIN_REPEATER_CHANGE 568
#define IDI_COMPONENT_VOLSTRAIN_REPEATER 569
#define IDI_VALUETYPE_STRAIN_TENSOR     570
#define IDI_FLUID_DENSITY               575
#define IDI_VALUETYPE_FLUID_DENSITY     576
#define IDI_VALUETYPE_REFERENCESTRESS   580
#define IDI_WELLCASINGMODEL             582
#define IDI_SIGMA_EPSILON               585
#define IDI_VALUETYPE_APERTUREPARAM     586
#define IDI_ICON6                       589
#define IDI_WELLCASINGRTCI              589
#define IDI_GRAINSTIFFNESS              591
#define IDI_VALUETYPE_GRAINSTIFFNESS    591
#define IDI_VALUETYPE_YOUNGMODULUS_NORM_DECOMP 594
#define IDI_VALUETYPE_YOUNGMODULUS_TRANS_DECOMP 595
#define IDI_VALUETYPE_POISSONRATIO_NORM_DECOMP 596
#define IDI_VALUETYPE_POISSONRATIO_TRANS_DECOMP 597
#define IDI_VALUETYPE_SHEARMODULUS_DECOMP 598
#define IDI_VALUETYPE_ANISOTROPIC_SHEARMODULUS 600
#define IDI_VALUETYPE_ANISOTROPIC_SHEARMODULUS_DECOMP 601
#define IDI_VALUETYPE_THOMSEN_EPSILON   603
#define IDI_VALUETYPE_THOMSEN_GAMMA     604
#define IDI_VALUETYPE_THOMSEN_DELTA     605
#define IDI_VALUETYPE_ANISOTROPIC_VP    606
#define IDI_VALUETYPE_ANISOTROPIC_VS    607
#define IDI_VALUETYPE_V0_HI             608
#define IDI_VALUETYPE_V0_ME             609
#define IDI_VALUETYPE_V0_LO             610
#define IDI_ZOOMIN_MODELS               611
#define IDI_EXPORT_MACROS               612
#define IDI_VALUETYPE_REFERENCE_APERTURE 613
#define IDI_COMPONENT_PRESSURE_FRACTURE_PRESSURE_REPEAT 617
#define IDI_COMPONENT_PRESSURE_MAXGRADIENT 619
#define IDI_NONMESHEDSURFACEPARAMETERS  620
#define IDI_EMPTY                       621
#define IDI_VALUETYPE_STRAIN 622
#define IDI_COMPONENT_NRMSTRAIN_GRADIENT        623
#define IDI_INITIAL_NRMSTRAIN                   624
#define IDI_COMPONENT_NRMSTRAIN_REPEATER_CHANGE 625
#define IDI_COMPONENT_NRMSTRAIN_REPEATER        626
#define IDI_COMPONENT_NRMSTRAIN_DISTRIBUTED     627
#define IDI_COMPONENT_LATSTRAIN_GRADIENT        628
#define IDI_INITIAL_LATSTRAIN                   629
#define IDI_COMPONENT_LATSTRAIN_REPEATER_CHANGE 630
#define IDI_COMPONENT_LATSTRAIN_REPEATER        631
#define IDI_COMPONENT_LATSTRAIN_DISTRIBUTED     632
#define IDI_VALUETYPE_CREEP_ALPHA       633
#define IDI_MIXTURE_CONTAINMENT         635
#define IDI_COMPONENT_FRACTURE_MATRIX_PRESSURE_DISTRIBUTED  636
#define IDI_FAULTPARAMETERS_REPEAT      778
#define IDI_CHANGE_UNSELECTED           779
#define IDI_CHANGE_SELECTED             780
#define IDI_COMPONENT_PRESSURE_PARENT     782
#define IDI_COMPONENT_TEMPERATURE_PARENT  783
#define IDI_COMPONENT_VOLSTRAIN_PARENT    784
#define IDI_EXCLAMATION_POINT           793
#define IDI_NODALSUPPORT_PARENT         794
#define IDI_FACESUPPORT_PARENT          795

#define IDI_XSECTION_ANY                620
#define IDI_ICON_TRUE                   40224
#define IDI_ICON_NA                     40227
#define IDI_ICON_FORCE_TRUE             40228
#define IDI_ICON1                       40461
#define IDI_MATLIB                      40461

#define IDI_CG_OK                       636
#define IDI_CG_UNKNOWN                  637
#define IDI_CG_MESSY                    638
#define IDI_CG_INVALID                  639
#define IDI_CG_BROKEN                   640

#define IDI_VALUETYPE_DUMMY             641
#define IDI_VALUETYPE_NRMSTRESS         642
#define IDI_VALUETYPE_MEANSTRESS        643
#define IDI_VALUETYPE_TIMESTRAIN        644
#define IDI_VALUETYPE_DELTAV            645
#define IDI_VALUETYPE_DELTAT            646
#define IDI_VALUETYPE_DISPLACEMENTZ     647

#define IDI_VALUETYPE_GVT_FACTOR_R_C    648
#define IDI_VALUETYPE_GVT_FACTOR_R_EX   649
#define IDI_VALUETYPE_GVT_FACTOR_S_NB   650
#define IDI_VALUETYPE_GVT_FACTOR_S_S    651

#define IDI_VALUETYPE_KRAD              652
#define IDI_VALUETYPE_KTAN              653

#define IDI_GROUPNODE                   654

#endif  // _resourceIDI_h_
