#ifndef _resourceIDP_h_
#define _resourceIDP_h_

/*
 * This file should contain all IDP_... constants.
 */

#define IDP_ZOOMINNOBOUNDARYLOADS       61
#define IDP_ONLYSMOOTHEDRESULTS         71
#define IDP_LOAD_FRACTURE_APERTURE_LOCKED 85
#define IDP_NODIAPATHFOUND              33154
#define IDP_SAVE_BEFORE_ANALYSIS        33158
#define IDP_EXCELNOTAVAILABLE_EXPORT    33329
#define IDP_EXCELNOTINSTALLED           33333
#define IDP_CANNOTOPENFILE              33335
#define IDP_NOVALIDSHEETS               33336
#define IDP_INVALIDFORMATEXCELSHEET     33338
#define IDP_INVALIDFORMATEXCELCELL      33341
#define IDP_INVALIDFORMATEXCELHEADER    33342
#define IDP_ERRORRUNNINGANALYSIS        33345
#define IDP_GLOBALTENSORVERTICAL        33349
#define IDP_SUPPORT_NODE_APPLYTOALL     33351
#define IDP_SUPPORT_RESETGLOBALTENSOR   33353
#define IDP_SUPPORT_FACE_APPLYTOALL     33354
#define IDP_MULTIPLEDEPLETIONSTAGESNEEDED 33356
#define IDP_INVALIDTEMPPATH             33358
#define IDP_TEMPVARINVALID              33359
#define IDP_LINEARCALCWITHFAULTS        33360
#define IDP_EXCELILLEGALUNITVALUE       33361
#define IDP_EXCELILLEGALDIMVALUE        33362
#define IDP_EXCELINVALIDHEADER          33363
#define IDP_EXCELILLEGALELEMENTTYPE     33364
#define IDP_NOHELPAVAILABLE             33399
#define IDP_DEPLETINGWITHUNDRAINEDMAT   33403
#define IDP_UNKNOWNFILEEXTENSIONIMPORT  33406
#define IDP_FAILUREPARSING              33409
#define IDP_LOAD_QUADRATIC_WITH_CSHE    33415
#define IDP_CANNOTOVERWRITE             33416
#define IDP_ERRORDURINGANALYSIS         33419
#define IDP_MAPPING_LOCKED_LOAD         33442
#define IDP_MATLIB_NOT_SAME             33443
#define IDP_NL_LARGEDEFORMWITHCSHE      33444
#define IDP_LOAD_CAMCLAY_LOCKED         33446
#define IDP_LOAD_FOKKER_LOCKED          33447
#define IDP_LOADLOCKED_LARGEDEF         33448
#define IDP_FAULTSLOCKED                33463
#define IDP_SLIPPINGHORIZONSLOCKED      33464
#define IDP_VERSIONTOOLOW               33465
#define IDP_INSUFFICIENT_MEMORY_FOR_CALCULATION 33626
#define IDP_SUPERMODELLOCKED            33628
#define IDP_GWC_CHECK_CONTACT_DEPTH_FAIL 33629
#define IDP_GWC_CHECK_TRANS_DEPTH_FAIL  33631
#define IDP_TOGGLE_TETRAHORIZON_MULTIPLE_SURFACES 33635
#define IDP_CALC_FOKKER_NOT_VALIDATED   33637
#define IDP_CALC_TETRA_FAULTS_NOT_VALIDATED 33639
#define IDP_CONFIRMCLEARANALYSISLOG     33651
#define IDP_EXPORTANALYSISLOGFAIL       33653
#define IDP_ERRORRUNAPP                 33658
#define IDP_CANNOTIMPORT2DXSECASCII     33660
#define IDP_CANNOTIMPORTPOINTSETFOR2D   33663
#define IDP_CANNOTIMPORT2DXSECEXCEL     33664
#define IDP_NO_STRESS_SUPPORT           33715
#define IDP_CONFIRMCLEARBRANCH          33716
#define IDP_CONVERTBRANCHTOTETRA        33717
#define IDP_CONFIRM_REPLACE_INITIAL_MATERIAL_MODEL 33754
#define IDP_INVALIDATEIMPORTEDMESH      33766

#endif  // _resourceIDP_h_
