@ECHO OFF
START /B ..\..\x64\%1\geomec_rgi_lock.exe %3
IF "%4" == "" GOTO SINGLE.ARGUMENT
..\..\x64\%1\geomec_rgi.exe /ROCKMECHFILE:%3 %4
IF ERRORLEVEL 1 GOTO TEST.FAILED
GOTO TEST.SUCCEEDED
:SINGLE.ARGUMENT
..\..\x64\%1\geomec_rgi.exe /ROCKMECHFILE:%3
IF ERRORLEVEL 1 GOTO TEST.FAILED
GOTO TEST.SUCCEEDED
:TEST.SUCCEEDED
@ECHO "TEST SUCCEEDED"
EXIT /B 0
:TEST.FAILED
SET ERROR.LEVEL=%ERRORLEVEL%
@ECHO "ERRORLEVEL = %ERROR.LEVEL%"
IF %ERROR.LEVEL%==%2 GOTO TEST.SUCCEEDED
@ECHO "TEST FAILED"
EXIT /B 1
:END
